### ISSUE TITLE
MusicXML: no export for repeat sign + shifted notes

### ISSUE THREAD

**Issue by maximumspatium** [Audiveris/audiveris#118]
[This score](https://github.com/Audiveris/audiveris/files/1799441/Over.zip) exposes two bugs in the integrated MusicXML exporter:

1. shifted notes
2. missing repeat sign

The pictures below visualize these issues:

![over correct](https://user-images.githubusercontent.com/6561800/37243328-c8e42bba-2477-11e8-9646-a0c8c95f6672.png)
![over wrong musicxml](https://user-images.githubusercontent.com/6561800/37243329-c9092456-2477-11e8-999c-ae73d93b1118.png)

To reproduce the first case, do the following steps:

- open the image
- transcribe it
- export the sheet as MusicXML
- import it in MuseScore. Measure 7 should have shifted notes as shown in the 2nd picture above.
- save the book
- close the book
- reopen the book
- export the sheet again

Importing it again in MuseScore after saving will magically correct the notes. So it looks like something is left in an inconsistent state during recognition. Saving seems to auto-fix it somehow.

**UPDATE**: it looks like an invalid clef (TREBLE_CLEF) will be reported for the measure 7...

Regarding the 2nd case, repeat export will be prevented by this check:
https://github.com/Audiveris/audiveris/blob/3d8ede51397e39d29ada1bb0999ea47c2e5697c7/src/main/org/audiveris/omr/score/PartwiseBuilder.java#L920-L927

I have no clue why it doesn't work. This compound if-statement is almost ungrokable to me. It cries out for refactoring!

**Comment by hbitteur** [comment]
Shifted notes were caused by a bug in measure merge, resulting in a removed measure still being referenced by its formerly contained chords (while restoring data from the .omr file indeed restored proper containment). This is now fixed by commit 21bc29b715f8a9266608d210b683167c11717982

Repeats incorrect export was also a consequence of the same measure merge, since the repeat sign was then located in the middle of the measure, rather than the left side. Repeats are now better computed and exported by commit 74079343f59be9b10e98610af85c5964c2452311

And in the generation code of MusicXML data, the decision to actually export a barline element should now be more understandable, as follows: 
https://github.com/Audiveris/audiveris/blob/74079343f59be9b10e98610af85c5964c2452311/src/main/org/audiveris/omr/score/PartwiseBuilder.java#L919-L938

**Comment by maximumspatium** [comment]
Awesome! It's time to close this issue. Many thanks!
