### ISSUE TITLE
Exception in removeInters java.lang.NullPointerException

### ISSUE THREAD

**Issue by Bacchushlg** [Audiveris/audiveris#123]
![beatles - if i fell in love 3-1](https://user-images.githubusercontent.com/33522630/37392321-16467860-276e-11e8-86cf-b2b272cd8583.jpg)

when I remove the wrong detected half note in measure 3, bass line, I get
Exception in removeInters java.lang.NullPointerException

Half of the notes of measure 3 keep black in the colored output view and the rhythm check seems not to have been completed.

**Comment by hbitteur** [comment]
This happens when the voices are recomputed across all systems in the page.
Since there is a tie between head 1996 (head of chord 4157), at the very end of staff 3 first system and the corresponding staff in the next system, voice from this chord should be carried over to the tied chord.

But chord 4157 has **no** voice assigned, because the rhythm resolution failed on this measure (you can see that the last time slots don't exist in this measure, preventing voice assignment). Hence the null pointer exception.
I can use a protection to catch such exception, but the real problem to solve is to compute needed slots and voices...
Stay tuned.

**Comment by Bacchushlg** [comment]
So the failed rhythm calculation is the reason for the problem. 
But why does it fail? After deletion of the half note the rhythm check should be ok, or not?

**Comment by hbitteur** [comment]
Done in commit 5089ceab7557833d400b74cc87eb5abc6b46cb5e
Voices computation is now protected. And it works once measure rhythm has been manually fixed.
I'm closing this issue

**Comment by hbitteur** [comment]
"_So the failed rhythm calculation is the reason for the problem._"
Indirectly yes, because some information in the failed measure are not available.
So, modify the symbols in the faulty measure, it will turn white, and the voices will correctly be linked across the systems.

Actually, I did it manually for the whole page: I made the modifications so that all measures turned white (no longer pink)

**Comment by hbitteur** [comment]
"_But why does it fail? After deletion of the half note the rhythm check should be ok, or not?_"
There are many possible reasons, most of them are due to misrecognized symbols.
The RHYTHMS step works on one measure stack after the other, trying to fill detected time slots. It stops as soon as any incorrect alignment (abscissa & time offset) is detected.

For some time, I tried to play with adding/removing FRAT entities (FRAT stands for Flag, Rest, AugmentationDot and Tuplet). It took ages for no satisfactory result.
So now, I take the reduced symbols  and consider them as a given. And if ever a correct rhythm cannot be found in a measure, it is simply signaled as such, so that the user can make the corrections.
