### ISSUE TITLE
give "complex inters" higher score in matching algorithm

### ISSUE THREAD

**Issue by Bacchushlg** [Audiveris/audiveris#125]
I observe a certain behaviour for a couple of time:
there are some inters that have "false friends" (parts of a complex inter) and often these friends "win the race".
typical examples:

- mf <-> f (mezzo forte)
- mp <-> p (mezzo piano)
-  (applies to all combinations with "p" and "f")
- G-clef with 8 below/above <-> G-Clef simple
- tuplet_3 <-> digit_3 (not really the same problem...)

In many cases the I get the simple inter recognized instead of the correct (complex) one. If I put a lassow around the complete glyph, the complex inter is recognized immediately (highest position in basic classifier). But if I put the lasso only over the false friend, it has a slightly higher value - and is the winner!
Concrete example: 
- mf: 0.9952
- f:  0.9997

My idea would be to give "complex" inters a certain bonus during verification. That would assure that they are not superseded by the simple ones.

**Comment by hbitteur** [comment]
Good question. 

Let's take the case mf <-> f
Today, we just have "mf" and "f" defined in Shape class. And they would overlap (hence are mutually exclusive) in the case of a real mf symbol. So, today:
- **f** competes with mf
- **mf** competes with f

The higher grade wins, and it's often "f" over "mf", certainly because we have many more "f" than "mf" symbols in the training set. 

Rather than trying to cheat by artificially boosting "mf" against "f", perhaps we could re-introduce the "m" symbol in the Shape class (and have to retrain the classifiers, unfortunately...). Doing so, instead of f vs mf, we would have mf, m and f. Chances are, that in the case of a real mf, the SIG reducer would have 3 candidates:
- **m** _which could support mf_, instead of competing with mf
- **f** _which could support mf_, instead of competing with mf
- **mf** _which could support both m and f_, instead of competing with m and f

By SIG definition, if mf is supported by m and f, there is no exclusion as in current case today. But we could check the "mf" candidate and discover that it is linked by support relation to an m inter and to an f inter, and decide to remove these m & f that are kinds of sub-symbols of super-symbol mf.

Doing so, we would not cheat (as in boosting mf over f), but rely on the presence of "m" right before "f". And this is information we bring to the sig.

We would have to implement this trick for pp, mp, ff, mf, fp, sf.
Perhaps sfz as well??? (is this a common dynamic sign?)

**Comment by Bacchushlg** [comment]
ok, it seems that this is the best way! I did not know that there is an algorithm that provides this later combination.
About sfz: I say this once - and I had to ask Mr. Google what it means (and already forgot again...).

**Comment by hbitteur** [comment]
Do you have an example that we could test upon?

**Comment by Bacchushlg** [comment]
![for the longest time 1](https://user-images.githubusercontent.com/33522630/37478280-1514c228-287a-11e8-9072-3a291c6f902f.jpg)

This one has a lot of it...

**Comment by hbitteur** [comment]
Before I embark in creation of an "m" shape, I would check the support idea with existing shapes (p and f): do you have an example with some of: pp, fp, pf, ff

**Comment by hbitteur** [comment]
Done with commit df12f3afa3572232ce545497430459b14844a96d
I finally chose a simpler approach, with on-the-fly decision: any complex sign is compared with shorter ones which are "swallowed" if the area of their intersection with the larger one is close to their own area.
This saves us the burden of dealing with new inters and new relations.
I checked with your examples.
Issue closed.
