### ISSUE TITLE
keyboard short cuts for manual editing

### ISSUE THREAD

**Issue by Bacchushlg** [Audiveris/audiveris#138]
I think it would be a fine feature to support keyboard short cuts during editing of the score.
My general idea would be a 2 step short cut (2 keystrokes):
1st: selection of the classifier group
2nd: selection of the item

So the user would select a glyph and then performs these 2 keystrokes.

In case of bad scans editing sometimes is a mouse-marathon actually. Key strokes would be a fine helper, and I assume that it is not very complicated to support this (hopefully). Only the most common classifiers should be supported - for the rest the selection must be by mouse actions.

In concrete the short cuts could be like this:
a (ccidental)
- b, n, s (ignore the rest)

b (eams)
- f(ull), h(alf), 3(triplet)  (ignore the rest)

d (ynamics)
- p, m(f), f  (ignore the rest)

f (lags)
- u(p), d(own)  (ignore the rest)

h (eads)
- w(hole), v(oid), b(lack), d(ot)

r (ests)
- 1, 2, 4, 8

p (hysicals)
- l(yrics), t(ext), a(rc - slur), s(tem)

**Comment by hbitteur** [comment]
What about using MuseScore similar commands if at all possible?
So that users don't get lost.

**Comment by hbitteur** [comment]
I am away from home.
We are free to use whatever letter combinations, but  once users get used to them, it's more difficult to change...

**Comment by Bacchushlg** [comment]
This was my first idea, too.
But then I saw, that editing is rather different than when working with MuseScore.

MuseScore sets note after note. The letter keys select the tone hight, the number keys the duration.

Audiveris constructs the notes by defining the elements of a note (head, stem, flag,...) and setting them at the correct position. It has (at this point) no information about tone hight nor direct relation between head type and note length.

My idea - when providing my proposual - was the follow the logic in the classifier groups and then selecting "logical" letters/numbers.

What I had forgotten to mention: there should be two different way of usage:
- select a glyph, then short cut -> direct insertion of the classifier to the glyph position
- without selected glyph: add the classifier to the cursor so that the user can drop it at the correct position.

**Comment by hbitteur** [comment]
Here is where I am:
- _select a glyph, then short cut -> direct insertion of the classifier to the glyph position._ I just implemented this point.
- _without selected glyph: add the classifier to the cursor so that the user can drop it at the correct position._ I need some more information for this second point.
    - Should I insert an inter (of proper shape) centered on the current location pointed by the mouse? Easy to implement but the user cannot move the inter, just delete it.
    - Should I "position the mouse onto the proper shape button" so that the user just have to drag from this button to the desired location. Easier for the user, much less for the implementer... :-)

Just tell me. Meanwhile I will investigate how to artificially position the mouse somewhere...

**Comment by Bacchushlg** [comment]
about the 2nd: my idea was to have the inter "at the mouse cursor" similar to drag-n-drop, but only drop. So the user can move the inter to the correct position and drop it there. 
Alternatively - if easier to implement: the inter is placed (after key strokes) at the place of the actual cursor position and can be moved to the correct position. Not so elegant, but might work to.

One "extension" to the general idea: it would be fine, if the first key stroke activates the classifier group in the shape pane. This could then also be used for normal drag-n-drop actions.

**Comment by hbitteur** [comment]
The problem is to be able to move the inter until it's at the desired location and then drop it there. Once it has been dropped you can no longer move it (nor resize it by the way). This would require more significant improvements in Audiveris UI, and could not be available in the short term.

The proposal I have in mind is the following (when we have no selected glyph): display the proper set panel, and pre-select the proper shape button in this set panel. Then the user only has to drag this pre-selected button to the desired location.
Even better: pre-update the button history, so that the button for the desired shape appears in first place in shape history, which means the selected shape (whatever it is) would always appear at the same location in the shape board. And the user simply has to drag from always the same location in shape board to the desired location in sheet. I will complete this today so that you can test it.

If this does not fit your expectations, I will have to investigate the idea of simulating a drag that would start near the target location. No guarantee of success however.

**Comment by Bacchushlg** [comment]
I never had such an idea - and it sounds good. 
Yes, I think this is a valuable access and will work almost as efficient as my initial idea.

**Comment by hbitteur** [comment]
Implementation is now available in commit 46a89a015f00e60857ff6706ab73d6f73aa4a9bc

Char pairs are defined as follows (I only replaced 'ab' by 'af' for Alterations/Flat):
https://github.com/Audiveris/audiveris/blob/46a89a015f00e60857ff6706ab73d6f73aa4a9bc/src/main/org/audiveris/omr/sig/ui/ShapeBoard.java#L253-L293

**Comment by Bacchushlg** [comment]
great great!!
What a difference in editing!
This gives at least a time advantage of 200% in editing, if not more! Really!

It's really a pity that I have forwarded this idea so late, because I had it in mind already for a couple of time. But: better late than never!
Thank you for this!

**Comment by hbitteur** [comment]
On top of this, I just added the ability to drag a stem symbol (commit c056c71d179888fab2dd6c87a288de38da69255e)
The stem is of a standard length and not yet resizable, but this should help when no underlying glyph is readily available.
