### ISSUE TITLE
adding barline disorders rhythm analysis 

### ISSUE THREAD

**Issue by Bacchushlg** [Audiveris/audiveris#155]
[I can see clearly now.zip](https://github.com/Audiveris/audiveris/files/1950199/I.can.see.clearly.now.zip)

In the appended score I had a problem with measure 7: it was discarded in the rhythm check (all notes black in output view).
I assumed that the missing barline in the top voice was the reason. So I added a barline. And then I see a lot of diagonal grey lines (the rhythm lines). I assume the the rhythm check tries to bring together measure 7 top and measure 6 bottom line.
I tried several delete and re-adding of the barline. But I find no way how to repair.

**Comment by Bacchushlg** [comment]
seems to be solved with version 5.1.0:7ce607783

**Comment by Bacchushlg** [comment]
no - wrong exultation. I did not finish the test correctly - and got the same problem again

**Comment by hbitteur** [comment]
@Bacchushlg The provided .omr (within the .zip archive) seems corrupted.
It does not contain any BINARY.xml part, hence I'm not able to load the example.
Could you simply post the initial image?

**Comment by Bacchushlg** [comment]
[I can see clearly now.pdf](https://github.com/Audiveris/audiveris/files/2030057/I.can.see.clearly.now.pdf)

**Comment by hbitteur** [comment]
Well, you can add a barline (actually a full column of barlines) but not yet for the starting barline, because it has a special role in the staff system. Sorry, not yet implemented.

However, I did not experience any problem with measure 7, see below:
![image](https://user-images.githubusercontent.com/22053634/40414900-d2a1db0c-5e79-11e8-8b81-5a8b5d868ad2.png)

**Comment by Bacchushlg** [comment]
it seems that the initial problem is solved - I don't get the problem any more either.
