### ISSUE TITLE
Audiveris stucks while analyzing this image and doesn't generate any logs (both in desktop and bash mode)

### ISSUE THREAD

**Issue by FatihEbibelot** [Audiveris/audiveris#157]
Hi,
I'm trying to use Audiveris in my server and when I send this image(in bash mode);
![img_9194](https://user-images.githubusercontent.com/31078763/39328376-093c6b76-4950-11e8-8508-f4b0431c67af.JPG)
It stucks and doesn't generate any log. Also I tried it in desktop version it again stucked and gave timeout error after 120 seconds. Here is the logs;

<img width="1626" alt="screen shot 2018-04-26 at 12 51 05 pm" src="https://user-images.githubusercontent.com/31078763/39328548-90c9a32e-4950-11e8-8e67-f19e0ea8c3b2.png">
<img width="1610" alt="screen shot 2018-04-26 at 12 52 40 pm" src="https://user-images.githubusercontent.com/31078763/39328627-c208b6b4-4950-11e8-9542-108adeeb13d0.png">

**Comment by maximumspatium** [comment]
Can you post the precise image you're trying to recognize right here or provide us with a link where we can download it from?

**Comment by maximumspatium** [comment]
BTW, I noticed that you're using the v5.0.0. We're currently preparing the 5.1 release.

There's a good chance that your issue has been already fixed. I therefore encourage you to switch to the `development` branch and try from there. Here comes the list of the corresponding terminal commands just for sure:

```
cd [your audiveris source dir]
git checkout development
git pull origin development
gradle clean run
```

**Comment by FatihEbibelot** [comment]
I'm using latest development branch. Here is the access url for the image;
https://ibb.co/ieE9Gx

**Comment by Bacchushlg** [comment]
This looks like a camera picture, taken from a monitor screen. 
Rather impossible to do an analysis from this!

You should create a real screen shot instead, or better save the image directly as jpg, png or pdf.

**Comment by FatihEbibelot** [comment]
But it stucks during the analysis, shouldn't it throw an exception? Also I'm getting the same timeout problem for this image as well.
![image2](https://user-images.githubusercontent.com/31078763/39418851-92e299f4-4c11-11e8-98e2-fe838f7d3328.jpeg)
access url;
https://ibb.co/noT6Wx

**Comment by Bacchushlg** [comment]
again a camera picture - with very low resolution.
You should use a digital scanner, or a camera with stand and flash. The proposed resolution is 300 dpi, that means about 2000*3000 pixel for a DIN-A4 page. This image has just 480*640 pixels - much too low.
And the "white" is very shady, due to bad illumination.

**Comment by hbitteur** [comment]
@FatihEbibelot , just to add on @Bacchushlg answer.

Trying your example, I do get the following warning dialog, which tells you to discard this unusable image:

![image](https://user-images.githubusercontent.com/22053634/39420017-e249926c-4c62-11e8-9c04-02b2bf2b144b.png)

If you press the "**Yes**" button, the processing stops for the image at hand. Here is the end of the log:
[Issue-157] Issue-157 With an interline value of 5 pixels, either this sheet contains no staves, or the picture resolution is too low (try 300 DPI).
[Issue-157] Sheet Issue-157 flagged as invalid.
[Issue-157] StepException cause detected in [SCALE]
[Issue-157] End of sheet step SCALE

If you press the "**No**" button, you do so at your own risks, which here led to some endless processing, interrupted by the guarding timeout. What else could the program do?

What _you_ should do, is to provide the program with a more suitable input image.

**Comment by hbitteur** [comment]
Please keep in mind that a human brain is much more capable than a computer program!
Some score that may look OK for your eyes can in fact go beyond the capabilities of the OMR program.

From what I saw, here the problem is not the illumination, but simply the much too low resolution.

**Comment by hbitteur** [comment]
@FatihEbibelot 
FYI, here are the black & white pixels that OMR has to fight with:

![image](https://user-images.githubusercontent.com/22053634/39420914-07c311cc-4c67-11e8-9356-dc5db9d69cbd.png)

**Comment by maximumspatium** [comment]
The attached images speak for themselves - the latter one is challenging even to the human being.

I'm going to add a description on how to proceed in the case of low-resolution warning to the upcoming user guide.

The only solution to this problem is to acquire another image at a higher resolution.

**Comment by hbitteur** [comment]
Well, I mostly disagree.

The book is created upfront so that processing of its sheet(s) can take place.
Plus a book may contain more than one sheet.

Generally, I hate deciding for the user unless we can't do otherwise. I think it's not a real burden to let the user close the book with just an invalid image in it.

The clean way for the user may well be to store the book (with some of its sheet(s) now flagged as invalid). He can always go back to it with different processing parameters.
In a batch job for example, I think it's a clean way to leave information about what has been done.
