### ISSUE TITLE
Is it possible to have a chat with one of project collaborators?

### ISSUE THREAD

**Issue by FatihEbibelot** [Audiveris/audiveris#161]
I wonder if I can have a chat with one of the collaborators? I want to talk about possibility of contribution to the project.

Thanks.

**Comment by hbitteur** [comment]
Sure, let's do this on this thread in public, because other potential contributors might be interested.

You could tell us what your main motivations, competencies, areas of interest, etc are.
Are you already familiar with Audiveris as an end-user, or as a developer?
Are you more software oriented or more music oriented? (or both) because both would be interesting.

For the short term, we would appreciate contribution on:
- Coming release (5.1): Help review and complete the end-user documentation. Help generate all-in-one packages (for Windows OS mainly)
- Next release (6.0, being worked in parallel with 5.x): Help integrate new classifiers (patch classifier and page classifier) to replace use of current glyph classifier and of template matching. Help organize the transfer of learning from neural network (pre-trained on synthetic scores) to fiine-training on real validated scores.

These are just "hot" examples, there are other tasks of interest. For example, in the "issues" tracker, there are many formalized requests for enhancement.

**Comment by FatihEbibelot** [comment]
I'm more of a software guy but I'm interested in how we can improve the scan time. Currently it takes about  45-120 seconds. I wonder if we can reduce this time. Also maybe can we have a live session to go over the code?

**Comment by hbitteur** [comment]
I would suggest you use a profiling tool to measure in which parts of the code the cpu is mostly used. Personally, I use NetBeans as my favorite IDE, and it provides several profiling possibilities.

I'm afraid you won't find any singular "hot spot" though. The program goes through the 20 steps of the processing pipeline, and these steps are not equal in terms of CPU needs. IIRC, the most costly ones are:
- BEAMS, which runs a morphological closing on the whole image
- HEADS, which applies template matching along staff lines and ledgers
- CURVES, which retrieves and merges arcs into slurs and segments.
- TEXTS, which calls Tesseract OCR library

I don't expect better performances (CPUwise) from the coming patch/page classifiers, it may even get worse. But I expect a better recognition quality, which would save on human time spent on OMR correction. After all, human time is more valuable that plain CPU time.

**Comment by FatihEbibelot** [comment]
1- Can you please provide us the Audiveris guideline for the quality of image and pdf files that can be processed by Audiveris properly?
2- Could we have a conference call tomorrow or the day after so we can discuss this live and show you the issues we are observing with PDF and high quality images. We really like to solve this issue and maybe able to help and contribute to the community as well.

**Comment by hbitteur** [comment]
I don't think we need a live discussion (and I'm really overbooked right now, sorry). 
I just commented this PDF problem in issue #162 so let's move forward in writing.

**Comment by maximumspatium** [comment]
> show you the issues we are observing with PDF and high quality images

I cannot remember when we (i.e. the audiveris dev team) experienced any issues with PDF import since we switched to [JPodRenderer](https://sourceforge.net/projects/jpodrenderer). Although it does an excellent job catching known PDF corner cases, it's still possible that some PDFs cannot be rendered correctly.
The best solution is to share the problematical file with us using the issue tracker so we can can investigate it...
