### ISSUE TITLE
Part Barline with no proper StaffBarline

### ISSUE THREAD

**Issue by Bacchushlg** [Audiveris/audiveris#164]
[Ich weiss es wird einmal ein Wunder geschehn 1 hell.zip](https://github.com/Audiveris/audiveris/files/2015908/Ich.weiss.es.wird.einmal.ein.Wunder.geschehn.1.hell.zip)

I dared to try this bad and complex score.
The transcription was better than I expected (I tried a couple of time before and always rejected...)
I was able to edit almost everything inside Audiveris. Unfortunately I get no valid export, and after re-opening the saved OMR file, there appear some errors. One of them is:

RubberPanel paintComponent java.lang.IllegalStateException: Part Barline with no proper StaffBarline

Maybe it's something with memory handling?

**Comment by hbitteur** [comment]
@Bacchushlg Could you retry your example with latest pull, because I think I corrected this bug while investigating on octave shifts

**Comment by Bacchushlg** [comment]
The described error is solved!
But I still have a problem in measure 4: it is completely ignored in rhythm check - and exported as empty measure.
Any idea?

**Comment by hbitteur** [comment]
This was the result of competition between barline and chord, fixed by commit 3ac5983cfb0035a8f5d4c874bb6fd72448072180 which freezes some barlines (the ones aligned with connectors). A _frozen_ Inter cannot be discarded by any overlapping competitor, the competitor gets discarded.

I used this to improve note head retrieval by excluding close neighborhood of such frozen barlines and connectors. Done in commit 37b61b05e2e0785dca35fec026f6d061e23e1597
In this particular example, this avoid several false head candidates (especially whole heads).
