### ISSUE TITLE
Make new Audiveris work with MuseScore

### ISSUE THREAD

**Issue by JalonSolov** [Audiveris/audiveris#169]
MuseScore had a plugin that was supposed to work with the old-style Audiveris, to pass a PDF file to Audiveris and get the transcribed book back.  I don't pretend to know how it worked - I never used it.

However, it seems like before you put extra effort into creating your own score editor as part of the new Audiveris, it might be nice to at least explore tying into MuseScore again.

Just a suggestion.

**Comment by Bacchushlg** [comment]
This feature of MuseScore was my first contact to Audiveris, and I used it for a while - with very different results ;-))
I would support this suggestion. The actual detection quality is much better than what is provided by the "old" version - while the usage of Audiveris is still a bit tricky.

**Comment by hbitteur** [comment]
@JalonSolov I'm not sure to really understand your question. Please correct me if I am wrong.

If you are referring to the MuseScore import feature which, to my knowledge, still uses an Audiveris 4.x version, then you should ask MuseScore folks about it. They know that 5.0 is out and that 5.1 is about to be released, with improvement in recognition quality (plus a basic end-user interface that MuseScore is not directly interested in, because they have their own and better one).

The problem from going from (Audiveris) OMR to (MuseScore) editor is that today it goes through MusicXML data. And reality is that poor scores often lead to very poor, if not unusable, MusicXML data.
Hence the need to have some editing capabilities on Audiveris side.

There are other reasons for this, such as the goal to populate a representative OMR data set. For a rather global view on the problem, please refer to https://github.com/Audiveris/audiveris/wiki/Perspective

**Comment by Bacchushlg** [comment]
As I mentioned above, I had used this feature from MuseScore a couple of times (with the old version). I think it is really worthy to switch to the actual version - it will for sure give better results than the old one.

**Comment by JalonSolov** [comment]
My goal for this request was to suggest using MuseScore as the score editor, while using Audiveris as the OMR engine.  How this is accomplished doesn't really matter.

The idea is that they have a fairly complete score editing program already.  They did have a way (however well or badly it worked) to use Audiveris as the OMR engine with the old version of Audiveris, but I would rather use the (much, much better!) new version instead.

If you could integrate them in a useful fashion, you would not have to implement your own score editing functionality in the Audiveris code. - a classic case of "reinventing the wheel".

It may be that you don't like the way MuseScore works, in which case it won't happen.  This is just a suggestion of a way to make use of something that already exists.

**Comment by maximumspatium** [comment]
> If you could integrate them in a useful fashion, you would not have to implement your own score editing functionality in the Audiveris code. - a classic case of "reinventing the wheel".

Back in 2015, we already investigated such a coupling between Audiveris and Musescore with several developers. The problem is that we can't just replace Audiveris UI with Musescore editor because these apps build upon different underlying models: Audiveris uses a graphical model to express relationships between score objects (that's what the ol' famous [Score](https://en.wikipedia.org/wiki/SCORE_(software)) does) while Musescore utilizes a semantic model of musical notation. The reason for this difference lays in the purpose of these applications.

While it is still possible to convert between these two models, such a conversion is always **lossy**, i.e.

1. converting from graphical representation to a semantic one means throwing away precise object geometry
2. starting with a semantic model implies implementing complex layout algorithms to recreate precise object geometry

That's exactly what Audiveris (1) and Musescore (2) currently do.

_The only way to overcome this problem is to hack Musescore to bypass their internal layout algorithms and to use the layout information supplied by Audiveris instead. As you understand, Musescore devs aren't happy about this scenario._

So we decided to resume development of Audiveris editor and offer two different output formats:
 * OMR format retains the precise layout information
 * MusicXML tries to derive semantic information from OMR

While converting from OMR to MusicXML, we need a way to cope with recognition errors. Let's assume we're trying to convert a score with a lot of graphical details to a score that keeps only important musical information (keys, notes, beams etc). Let's also assume that our score contains a quarter note triplet but the only difference between such a triplet and usual quarter notes is the bracket that said failed to be recognized properly. Conversion of this score to MusicXML (that uses a semantical model) will produce an erroneous score. There is no way to tell Musescore that the original contains a triplet at the precise position because graphical information has been discarded.

Do you see the dilemma?
