### ISSUE TITLE
idea: provide a try-and-error algorithm in rhythm check

### ISSUE THREAD

**Issue by Bacchushlg** [Audiveris/audiveris#178]
There are a couple of score where a common problem appears: the rhythm check fails due to miss-positioning of notes, missing detection of flags and detect-or-not augmentation points.

My idea: 
- mark unclear elements as "weak" during detection (also weak assignment to voices resp. ticks)
- provide a sort of try-and-error algorithm that tries all combinations of weak-detected elements (flags, aug.dots, note heads) and select the one with the best fitting rhythm check score.

I assume that even with the new page detection there will always be problems to properly detect everything properly - esp. in case of bad scans.

This feature would be esp. interesting for the batch usage of the program (e.g. through the channel that is actually used by MuseScore).

**Comment by hbitteur** [comment]
Great minds think alike... I tried this approach about a year ago.

The RHYTHMS step was driven by what I call "**FRAT**" symbols (**F**lags, **R**ests, **A**ugmentation dots, **T**uplets). These symbols were, among the additional ones detected by the SYMBOLS step, the only ones that could impact rhythm correctness in a measure (since all note heads and beams had already been detected and validated in the previous steps)

The idea was, right after the SYMBOLS step, to try all possible combinations of weak FRATs, until a satisfactory rhythm result was found. This was very costly, because we had to run the rhythm algorithm on each and every combination of FRATs for each measure stack. It use to take ages, often leading to timeout, and for no usable results in the end.

So, I decided to step back to something more straightforward: first reduce symbols conflicts based on their contextual grades (performed in the LINKS step), and then use the surviving FRAT items to build measure rhythm and simply signal the measure in pink if an error could be detected. This is still the approach we use today.

**Comment by Bacchushlg** [comment]
I could imagine that now - with all the improvements that you have realized in the last months - the algorithm might be worthy to be retried. Especially after the improvement in the voices separation, which is almost perfect now!
Maybe you could control this as separate step that can be disabled by the user. In my opinion it's esp. worthy for batch runs... And there the speed of transcription is of lower priority

**Comment by hbitteur** [comment]
In French we say "chat échaudé craint l'eau froide", which translates litterally as "scalded cat fears cold water", which means that once you've been bitten you are more prudent than ever before.

Right now, I prefer investing in better recognition means because this is really the key topic and the new classifiers are the path to investigate in that respect. Because, if your initial items are poorly recognized, it's often a waste of time to try to reconstruct the truth out of them. GIGO: Garbage In, Garbage Out.

But OK, this could be an optional step, just in case... Not on the top priority list as of today.

**Comment by Bacchushlg** [comment]
The german version is "ein gebranntes Kind scheut das Feuer" (l'enfant brûlé a peur du feu)...

I completely agree concerning your approach to improve the basic recognition before restoring faulty things later. But sometimes the image scans are of poor quality - so the garbage is already present at start-up. And esp. the recognition of aug.dots is really something very difficult in such cases. 
Therefore I think that for a final "perfect" solution, we will need something like what we discuss here...
