### ISSUE TITLE
Ottava_alta is recognized but cannot be assigned

### ISSUE THREAD

**Issue by Bacchushlg** [Audiveris/audiveris#179]
![sur le fil_00](https://user-images.githubusercontent.com/33522630/41968267-2b1b2608-7a04-11e8-8f77-2e3a7ac82b73.jpg)

The ottava_alta in the beginning of the score is recognized (when setting a lasso around it), but it cannot be assigned.
The same applies to ottava-bassa in another score.

**Comment by hbitteur** [comment]
Oops! ottava_alta and ottava_bassa are not implemented (no Inter), although the shape is recognized.
Sounds like a bug indeed!

**Comment by hbitteur** [comment]
News from the front:
The symbols 8va and 8vb are recognized, but I don't feel comfortable with the scope. It is supposed to be a dashed line, that may extend on several systems (although at beginning of new system the symbol *should* be replicated, but this example does not respect this rule), and finish with a small vertical hook.

How can we detect the **dashed line**? (because it is dashed, the CURVES step does not detect it).
How can we detect the very **small hook** at the end of the dashed line? It's so small! Too small for a symbol.

I can still define a kind of "closing ottava symbol" (the small hook), that the user could manually insert to speficy the end of the scope.

**Comment by hbitteur** [comment]
Detecting the end of scope is mandatory, since in the exported MusicXML data, all the *embraced* notes must have their pitch shifted accordingly.
I propose to label this as an improvement and leave this for 5.2

**Comment by hbitteur** [comment]
Available since 5.3
Closing
