### ISSUE TITLE
page of score is almost completely ignored although of good quality

### ISSUE THREAD

**Issue by Bacchushlg** [Audiveris/audiveris#181]
[liebestraum_pdf.pdf](https://github.com/Audiveris/audiveris/files/2148736/liebestraum_pdf.pdf)

page 5 of this score is almost completely ignored during transcription. Cannot see a reason for this...

**Comment by Bacchushlg** [comment]
after export to TIFF and re-import to Audiveris, everything is fine.

**Comment by hbitteur** [comment]
Very funny.
See below the "combo" scale plot for page 5:

![image](https://user-images.githubusercontent.com/22053634/43993911-be31ca42-9d94-11e8-969f-6e23c0a3e819.png)

The second peak was mistaken for a "large" staff interline of 40 pixels (and the real interline of 20 pixels was consequently considered as a "small" staff interline)
And since most of processing is based on the large interline value, it went totally wrong!

Where does this spurious "40" peak come from?
See below the loooong horizontal line, between the first 2 staves:

![liebestraum 5-ext](https://user-images.githubusercontent.com/22053634/43993975-8ad101b2-9d95-11e8-9e82-bdc808ad6708.png)

Here is the culprit! Because this is a synthetic score image, all the runs (1524 of them) between this line and the staff line just below have exactly the same length (40), resulting in a sharp peak in histogram. 

There is a sanity check to discard peaks that are too far from the most frequent peak, but this one went through because it stands at the exact maximum distance from previous peak. Bad luck.

I will have to strengthen the checks...
Stay tuned.

**Comment by hbitteur** [comment]
It was even worse than that, because in the first system of this 2-system page, there was also a looooong horizontal line, distant from the staff line below of, guess how many pixels... exactly 40!

ScaleBuilder code is now more strict on combo histogram peaks.

But reality is that we could find one small stave in a page of say 14 staves (imagine a page with 3 systems of respectively 4, 3 and 3 staves, with only the first staff of the first system being a small staff).
We would get roughly 1/14 = a ratio of 0.07 of total run counts.

So, I set the (modifiable) quorum value at 0.05
Available in last commit a8506b1917e4332f47c9a5343d63484e1fa1091b

This was one more example of the problems brought by "too perfect" images. :-)
