### ISSUE TITLE
Add "Last assigned" entry

### ISSUE THREAD

**Issue by webfischi** [Audiveris/audiveris#182]
At the moment I have a really annoying sheet, it's using one of those crazy fonts and the program couldn't recognize any quarter rests, which brought me to the following idea:
Why not add a new right click menu "Last assigned" which contains the last 3 or more commonly used glyphs, searching the same glyph over and over again is really time consuming and exhausting.

**Comment by hbitteur** [comment]
In the "development" branch, you already have a display of the last 5 shapes manually assigned, so that they are immediately available for a new double-click or drag n' drop.
This list is displayed as the first line in the shape palette.

If this is not what you have in mind, could you clarify your proposal?

Or perhaps you didn't try the "development" branch? Anyway we are just about to publish a release candidate for 5.1 on the (default) "master" branch.

**Comment by webfischi** [comment]
I am in the development branch already with a batch automatically updating it everytime I run it. After I wrote this enhancement I noticed that drag and drop is working pretty well since I last used it, even repeat signs are working now. I would like to have the last 5 shapes in the right click menu as well, especially when using a trackpad, dragging and dropping can be a real pita.

**Comment by hbitteur** [comment]
OK, @webfischi , so you want the same feature (today available via double-click and/or drag n' drop) to be also available in the context menu (right-click menu).
Sounds feasible.

**Comment by hbitteur** [comment]
OK, it's done in commit 987aab6941a6692c713f5cc8d7c995348aec99d8 (on branch "release-candidate-5.1")

**Comment by webfischi** [comment]
Great, almost what I was looking for. Contextmenu and drag and drop/double-click are synced up now, but entries are still missing in the context menu.

**Comment by hbitteur** [comment]
Oops I see the point

**Comment by hbitteur** [comment]
Correction done in commit 425f335853d535ca540cead09be1ca43b4d72307
Now, the context assign menu also displays the most recent shapes.
Sorry, I had missed that point
