### ISSUE TITLE
define a different directory as working directory for "save", "export" etc.

### ISSUE THREAD

**Issue by Bacchushlg** [Audiveris/audiveris#186]
by default save, export etc. go to a directory in the "Appdata/Roaming/..." directory that is normally hidden.
I had changed this a long time ago through the options settings - but for a normal user we should define a better reachable directory.
My proposal: use a subdirectory "Audiveris" in the user's document path. MuseScore does it this way, and I think it's a good solution as standard.

**Comment by Bacchushlg** [comment]
![autumn leaves 1](https://user-images.githubusercontent.com/33522630/42363922-ac278358-80f9-11e8-848a-b6191868fd00.jpg)

same problem with this score.

**Comment by hbitteur** [comment]
Sounds OK for any output.
But what about the config folder where user choices are kept?
/Herve (with very poor connection)

**Comment by Bacchushlg** [comment]
The config folder should stay where it is now. No (normal) user need to access these files directly, so no need to change anything here...

**Comment by hbitteur** [comment]
This sounds like  a good decision 


Envoyé depuis mon smartphone Samsung Galaxy.
-------- Message d'origine --------De : Baruch <notifications@github.com> Date : 06/07/2018  14:42  (GMT+01:00) À : Audiveris/audiveris <audiveris@noreply.github.com> Cc : Hervé Bitteur <herve.bitteur@audiveris.org>, Comment <comment@noreply.github.com> Objet : Re: [Audiveris/audiveris] define a different directory as working directory for "save", "export" etc. (#186) 
The config folder should stay where it is now. No (normal) user need to access these files directly, so no need to change anything here...

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Audiveris/audiveris","title":"Audiveris/audiveris","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/Audiveris/audiveris"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Bacchushlg in #186: The config folder should stay where it is now. No (normal) user need to access these files directly, so no need to change anything here..."}],"action":{"name":"View Issue","url":"https://github.com/Audiveris/audiveris/issues/186#issuecomment-403022865"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/Audiveris/audiveris/issues/186#issuecomment-403022865",
"url": "https://github.com/Audiveris/audiveris/issues/186#issuecomment-403022865",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [Audiveris/audiveris] define a different directory as working directory for \"save\", \"export\" etc. (#186)",
"sections": [
{
"text": "",
"activityTitle": "**Baruch**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@Bacchushlg",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"Audiveris/audiveris\",\n\"issueId\": 186,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"Audiveris/audiveris\",\n\"issueId\": 186\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/Audiveris/audiveris/issues/186#issuecomment-403022865"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 353621094\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by Bacchushlg** [comment]
I found a solution to solve this problem. 
Hopefully it's in line with your ideas...
See commit 859797c7e75a045e498d03c31dd2dd3e56c1ef79

**Comment by Bacchushlg** [comment]
I would even prefer to have the Audiveris directory as direct root of the exports. As far as I see the only used directory is ./data/output, which would make no more sense, now that we have split off this from "config" and "log".
Also I propose to set "/temp" to the "log" path, and not together with the output path.

**Comment by hbitteur** [comment]
@Bacchushlg
Sorry, I can't find your reference as  "commit 859797c7e75a045e498d03c31dd2dd3e56c1ef79"

Anyway, here below is a commented view of current audiveris folder.
Feel free to propose a different target for each kind of them.

```
├── config (user-defined configuration parameters)
│   ├── logback.xml (configuration file for logging). For advanced user.
│   ├── plugins.xml (connection of sequencers to Audiveris .mxl). For standard user.
│   ├── run.properties (user options). Opaque, should be accessed via Options menu.
│   └── user-actions.xml (definition of additional entries in menus). For really advanced user.
├── data
│   ├── output (default base for any book folder, which will contain .omr file). I don't use this one.
│   │   ├── MyBook 
│   │   │   ├── MyBook.omr, etc
│   ├── temp (temporary files for any use)
│   │   ├── batuque.json
│   │   ├── batuque.png
│   │   ├── carmen.json
│   │   ├── carmen.png
│   │   ├── chula.json
│   │   ├── chula.png
│   │   ├── cucaracha.json
│   │   ├── cucaracha.png
│   └── train (files for training classifiers) For advanced user.
│       ├── basic-classifier.zip (trained model: model.xml, means.xml, stds.xml)
│       ├── images.zip (images where samples were taken from. Huge archive. Not all images)
│       └── samples.zip (all samples usable to train the classifier)
├── log
│   └── 20180706T223427.log (one file per Audiveris run)
(Below are .xml files stored and loaded by BSAF, Better Swing Application Framework, for each UI window)
├── aboutDialog.session.xml (bsaf, opaque)
├── frame0.session.xml (bsaf, opaque)
├── frame1.session.xml (bsaf, opaque)
├── mainFrame.session.xml (bsaf, opaque)
├── optionsFrame.session.xml (bsaf, opaque)
├── SampleBrowserFrame.session.xml (bsaf, opaque)
├── scoreParams.session.xml (bsaf, opaque)
├── scoreTreeFrame.session.xml (bsaf, opaque)
├── topicsFrame.session.xml (bsaf, opaque)
└── TrainerFrame.session.xml (bsaf, opaque)
```

**Comment by Bacchushlg** [comment]
concerning commit: in the GIT history it appears as "859797c"

For the rest: let us move train as subdir to config and temp to log (simple way).

Or: create a separate main path beside "data" only for the output files. This would be <documents>/Audiveris/MyBook/MyBook.omr, etc.

**Comment by Bacchushlg** [comment]
change for Windows according to "simple way" in commit bf5b0a1

**Comment by hbitteur** [comment]
@Bacchushlg, I know you must be on vacation right now...

But where can we find your Windows installer?
I would like to play with it.
Does it define a default binding for .omr file type to Audiveris?

Enjoy your vacations anyway :-)

**Comment by Bacchushlg** [comment]
I thought that had sent you the link, didn't I?
https://app.box.com/s/oobukn13g08ijsxqe3n1w8fam782amx8

Am 14. Juli 2018 19:34:42 MESZ schrieb "Hervé Bitteur" <notifications@github.com>:

**Comment by Bacchushlg** [comment]
shall we change the paths for Linux / OIS, too?
If not, I would close this issue.

**Comment by hbitteur** [comment]
We need a clear definition of all the target paths, for each OS, so that we can complete the user handbook.
Don't close the issue until then.

Since you initiated the modifications, could you make a proposal for all these paths?

**Comment by Bacchushlg** [comment]
[Data file tree.xlsx](https://github.com/Audiveris/audiveris/files/2283751/Data.file.tree.xlsx)

here is my description of where files will be found on a windows system.
Who can fill it for the 2 others?

**Comment by hbitteur** [comment]
@Bacchushlg Could you have a look at latest handbook version?

**Comment by hbitteur** [comment]
New target folders policy is now correctly implemented and documented in handbook.
Closing this issue
