### ISSUE TITLE
Install fails on Windows

### ISSUE THREAD

**Issue by CedricMi** [Audiveris/audiveris#211]
Hello,
 .\gradlew.bat clean build
fails on Windows:
> Configure project :
targetOS=windows-null

> Task :compileJava
warning: [options] bootstrap class path not set in conjunction with -source 1.7
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':startScripts'.
> Could not resolve all files for configuration ':runtimeClasspath'.
   > Could not find tesseract-windows-null.jar (org.bytedeco.javacpp-presets:tesseract:3.04.01-1.3).
     Searched in the following locations:
         https://jcenter.bintray.com/org/bytedeco/javacpp-presets/tesseract/3.04.01-1.3/tesseract-3.04.01-1.3-windows-null.jar
   > Could not find leptonica-windows-null.jar (org.bytedeco.javacpp-presets:leptonica:1.73-1.3).
     Searched in the following locations:
         https://jcenter.bintray.com/org/bytedeco/javacpp-presets/leptonica/1.73-1.3/leptonica-1.73-1.3-windows-null.jar

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 38s
7 actionable tasks: 7 executed

Java version:
java version "1.8.0_141"
Java(TM) SE Runtime Environment (build 1.8.0_141-b15)
Java HotSpot(TM) Client VM (build 25.141-b15, mixed mode, sharing)

Gradle version
------------------------------------------------------------
Gradle 4.6
------------------------------------------------------------

Build time:   2018-02-28 13:36:36 UTC
Revision:     8fa6ce7945b640e6168488e4417f9bb96e4ab46c

Groovy:       2.4.12
Ant:          Apache Ant(TM) version 1.9.9 compiled on February 2 2017
JVM:          1.8.0_112 (Oracle Corporation 25.112-b15)
OS:           Windows 10 10.0 x86

Tesseract version: 3.05.02

Any ideas?
Thanks

**Comment by CedricMi** [comment]
Hello,
It says:

> Configure project :
os.arch=x86
targetOS=windows-null

**Comment by hbitteur** [comment]
My understanding for your configuration is:
- Java: 32 bit - because you get Java HotSpot(TM) Client VM (build 25.141-b15, mixed mode, sharing). If it was a 64 bit, it would explicitly say so.
- OS: Windows 10 Pro 64 bits

Since System.getProperty('os.arch') returns "x86" in your case, I suppose it represents the architecture of the JVM not of the underlying OS. Fine.

But, if **"x86"** is a legal value for os.arch, then there is a bug in our **build.gradle** file:
Could you try to modify the lines 18-20:
```
ext.targetOSArch   = ["i386":"x86", "i486":"x86", "i586":"x86", "i686":"x86",
                      "amd64":"x86_64", "x86-64":"x86_64", "x86_64":"x86_64"]\
                     [System.getProperty('os.arch').toLowerCase()]
```
as follows (mind the **"x86":"x86",** addition):
```
ext.targetOSArch   = ["i386":"x86", "i486":"x86", "i586":"x86", "i686":"x86", "x86":"x86",
                      "amd64":"x86_64", "x86-64":"x86_64", "x86_64":"x86_64"]\
                     [System.getProperty('os.arch').toLowerCase()]
```
This is a map to align with Javacpp dependencies convention. And obviously "x86" was not part of the set of keys, resulting in a null value, which modified the names of several dependencies in an invalid manner.

Could you try it and post the results?

**Comment by CedricMi** [comment]
I had the Java 8 Runtime & Java 8 SDK installed in both 32 and 64 bits.
I uninstalled the Java Runtimes and the SDK 32 bit.
A clean build worked.

Unfortunately, I did this before reading your post.

So I reinstalled the 32 bit version of Java SDK 8 to have both on my system again.
The build failed as before

I corrected the build.gradle per your instructions
The build works
It is a 32 bit build:
> Configure project :
os.arch=x86
targetOS=windows-x86

So there was a bug in your build.gradle

I don't know how many people on Windows 64 have both JDK8 32 & 64
I wonder if it would be more correct to ask them if they want to build the 32 or the 64 bit version of the software, or to default to 64.

In any case, thanks for your help!

**Comment by hbitteur** [comment]
Thanks Cedric for your contribution.

Regarding which version gradle should build for the user, we simply use the architecture of the JVM which gradle is running upon. Because this is the JVM the user is using.
And it works, if we except the bug just discovered with your specific case.

Now, there is also the ability to build Windows installers for Audiveris (and we are going to use them to post the installers (32 & 64) with the coming release).
In this specific case, the developer can choose which architecture(s) to build for (see the "installers" task in build.gradle file which by default builds both the 32 and the 64 versions for Windows)
