### ISSUE TITLE
Slur not picked up

### ISSUE THREAD

**Issue by WilloZA** [Audiveris/audiveris#218]
Having an issue where certain slurs are not getting picked up, please see below for examples:

![image](https://user-images.githubusercontent.com/26063400/49442132-35f0d000-f7d1-11e8-95ee-212b29984169.png)

![image](https://user-images.githubusercontent.com/26063400/49442307-d0511380-f7d1-11e8-9b45-561109c38eb3.png)

![image](https://user-images.githubusercontent.com/26063400/49442320-d8a94e80-f7d1-11e8-85a3-d176fc40c111.png)

Please advise me if there are any settings I could tweak to allow for better slur detection. Thanks in advance.

**Comment by hbitteur** [comment]
We know that slurs detection is a topic that would require a strong redesign.
First and foremost is the fact that image skeletonization is used to retrieve candidates slur arcs.
Many problems are due to slur portions that are tangent to (if not merged with) staff lines and ledgers.

Then we have the need to find a target note head rather close to each slur end. Here again, having a portion of staff line or ledger at the end of a slur often impedes the search for target head (because there is a maximum acceptable gap between slur end and head/chord).

There are no special tweaks available, we will need to work on more efficient techniques.
Meanwhile, it is rather easy for the end user to manually select the portions that should compose a slur and then assign the slur shape to it, and manually link it to proper heads if so needed.

**Comment by WilloZA** [comment]
Thank you for your response.
