### ISSUE TITLE
issue 204 is still a problem

### ISSUE THREAD

**Issue by de-wolff** [Audiveris/audiveris#227]

**Comment by de-wolff** [comment]
I just downloaded and installed Audiveris_Setup-5.1.0-windows-x86_64.exe
Starting audiveris results in:
Exception in thread "main" java.lang.UnsatisfiedLinkError: no jnilept in java.library.path
        at java.lang.ClassLoader.loadLibrary(Unknown Source)
        at java.lang.Runtime.loadLibrary0(Unknown Source)
        at java.lang.System.loadLibrary(Unknown Source)
        at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:804)
        at org.bytedeco.javacpp.Loader.load(Loader.java:613)
        at org.bytedeco.javacpp.Loader.load(Loader.java:530)
        at org.bytedeco.javacpp.lept.<clinit>(lept.java:10)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Unknown Source)
        at org.bytedeco.javacpp.Loader.load(Loader.java:585)
        at org.bytedeco.javacpp.Loader.load(Loader.java:530)
        at org.bytedeco.javacpp.tesseract$TessBaseAPI.<clinit>(tesseract.java:3648)
        at org.audiveris.omr.text.tesseract.TesseractOCR.identify(TesseractOCR.java:152)
        at org.audiveris.omr.Main.showEnvironment(Main.java:348)
        at org.audiveris.omr.Main.main(Main.java:122)
        at Audiveris.main(Audiveris.java:49)
Caused by: java.lang.UnsatisfiedLinkError: no liblept in java.library.path
        at java.lang.ClassLoader.loadLibrary(Unknown Source)
        at java.lang.Runtime.loadLibrary0(Unknown Source)
        at java.lang.System.loadLibrary(Unknown Source)
        at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:804)
        at org.bytedeco.javacpp.Loader.load(Loader.java:604)
        ... 11 more
using
Java(TM) SE Runtime Environment (build 1.8.0_171-b11)

on windows 10

**Comment by maximumspatium** [comment]
@de-wolff Thanks for reporting your problem. I'll ping the original author of the installer to see if we can solve it.

1) Next time you'd like to post to the existing issue #204 (even if it was closed) instead of opening a new one.
2) Please update your JDK/JRE to the latest one (1.8.0_192)
3) Please double-check that you don't have 32bit and 64bit JDK installed at the same time.

What do you get when you executing the following command in your Windows terminal:

`java -version`

**Comment by hbitteur** [comment]
This reminds me of something.
See the installation chapter in Audiveris 5.1 handbook, available at https://bacchushlg.gitbooks.io/audiveris-5-1/content/install/binaries.html

It says:
**32-bit vs 64-bit**: Audiveris software is coded in Java but uses some external binaries (Leptonica and Tesseract today, plus certainly ND4J tomorrow). Mind the fact that, because of these binaries, the JRE and installer architectures must match. Otherwise Audiveris will fail to run, with error messages saying for example that **jnilept** library cannot be loaded.
To check your existing java environment, you can use the command: java -version from a terminal window.

**Comment by maximumspatium** [comment]
To put it in other words, you'll need to ensure that

- you're running the right JRE for your machine. If it has a 64bit CPU, you'll need the x64 JRE.
- Audiveris installation package must match your CPU/JRE architecture

The problem is that Windows allows you to run 32bit JRE in a 64bit machine using the [WoW64](https://en.wikipedia.org/wiki/WoW64) compatibility layer. While pure Java software will still work this way, Audiveris won't do because it need to access native (non-Java) libraries via [Java Native Interface](https://en.wikipedia.org/wiki/Java_Native_Interface). The rule is simple: JRE 32bit won't link to 64bit libraries and vice versa.

That's why you have to double-check that all components (JRE, Leptonica and Tesseract) have the same architecture.
The simplest way is to check the dedicated directories. In english 64bit systems, all 64bit components are resided in `C:/Program Files` while everything 32bit goes to `C:/Program Files (x86)`.
(The name of these directories may be different if you're using a localized Windows version).
 
All components must be resided in the same directory to work properly.

**Comment by hbitteur** [comment]
@maximumspatium 
All the binaries used at run time must match (JRE on one hand, tesseract/leptonica on the other hand)
This does not prevent to run 32-bit binaries on a 64-bit Windows environment, thanks to the WoW64 as you mentioned.

To be strictly correct, we can't say that: "If [your machine] has a 64bit CPU, you'll need the x64 JRE."
On my 64-bit PC, I have both 32 & 64-bit JREs and 32 & 64-bit Audiveris installers (which install the proper binaries)
And I can run both (provided that I use JRE & binaries consistently of course)

Just for the sake of completeness...

**Comment by maximumspatium** [comment]
> To be strictly correct, we can't say that: "If [your machine] has a 64bit CPU, you'll need the x64 JRE."

While you can run 32bit JRE on a 64-bit CPU, there is no advantage to do that unless you have some legacy Java/JNI application. So the above-mentioned sentence can be understood as "best practice"...

**Comment by hbitteur** [comment]
Or unless you have to test the two installers... :-) which was my case, but not the case of a standard end-user I agree

**Comment by de-wolff** [comment]
@maximumspatium : I agree there is no advantage unless.. 
However, the default JRE which you install when you visit https://www.java.com/en/download/ is the 32 bits installer. I assumed (without verifying) that the default for a 64 bits system should be 64 bits.
Thats what caused my problem in the first place.

**Comment by marinellimcl** [comment]
Audiveris did'nt work on my PC with Win10. After having read above, I saw that java is installed on ProgramFiles(x86), that is in the 32 bit programs directory. So I uninstalled Audiveris x64 and installed the 32 bit version Now at least I can work now with Audiveris!!!! Sorry for my English, I'm italian.

**Comment by maximumspatium** [comment]
@marinellimcl You can alternatively deinstall Java 32bit, install Java 64bit and then use Audiveris x64.

**Comment by marinellimcl** [comment]
Yes I know, thanks. But I was in a hurry and had more difficult installing Java in the right directory. So I tried this way to control if it work and now when I'll have more time I Will tri the right way, that is put Java in the right directory. ThanksInviato da Tablet Samsung.
-------- Messaggio originale --------Da: Maxim Poliakovski <notifications@github.com> Data: 28/06/20  18:19  (GMT+01:00) A: Audiveris/audiveris <audiveris@noreply.github.com> Cc: marinellimcl <marinelli.marcello48@gmail.com>, Mention <mention@noreply.github.com> Oggetto: Re: [Audiveris/audiveris] issue 204 is still a problem (#227) 
@marinellimcl You can alternatively deinstall Java 32bit, install Java 64bit and then use Audiveris x64.

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.nd
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/Audiveris/audiveris/issues/227#issuecomment-650788351",
"url": "https://github.com/Audiveris/audiveris/issues/227#issuecomment-650788351",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by maximumspatium** [comment]
@marinellimcl Everything you need is the right Java installation package. It should put all required files automatically into the right directory.

Try the following steps:

1. Uninstall Java 32bit first!
2. Uninstall Audiveris 32bit
3. Go to https://www.oracle.com/java/technologies/javase-jdk11-downloads.html
4. Download the jdk-11.0.7_windows-x64_bin.exe package and install it
5. Install Audiveris x64
