### ISSUE TITLE
support moving of an inter

### ISSUE THREAD

**Issue by Bacchushlg** [Audiveris/audiveris#228]
sometimes it would be fine to allow moving of a wrong placed inter. E.g. in bad scans note heads are half a line misplaced. Actually only delete and new placement is possible.
In order to support this, Alt+Left-Mouse-Click might be a good action for this.

**Comment by hbitteur** [comment]
This is definitely on 5.2 feature list:
- Shifting fixed-shape symbols
- Resizing non-fixed-shape symbols (like stems, beams, slurs)

For these actions, I'd recommend to use the same gestures and key bindings that MuseScore provides. So that users don't get lost. And so that we don't re-invent the wheel :-)

**Comment by Bacchushlg** [comment]
has been implemented some versions ago.
