### ISSUE TITLE
Allow to remove pages from a book

### ISSUE THREAD

**Issue by de-wolff** [Audiveris/audiveris#232]
Or allow partial import of a pdf.
I have a lot of pdf's which contain complete music books. 
Most of them I scanned myself.
Most of the time I am not interrested in the entire book, but just in one piece, which is several pdf pages.
It should be nice when it was possible to select certain pages, or to remove pages from the book before transcribing

**Comment by hbitteur** [comment]
You can _invalidate_ a sheet, which does not totally _remove_ it since you can later _de-invalidate_ the same sheet, but this sheet will no longer be processed, so we can say it is logically removed.
To do so, select the sheet (which will simply binarize it if not yet done, just to show the sheet content) and use the menu "Sheet | Invalidate Sheet"

This may not be very convenient if you have a lot of sheets to "remove" from the containing book, since you have to do it for each and every sheet to remove.

In that case, you could resort to an external program to pre-process your pdf file. I can think of PDFSAM (PDF Split And Merge), a free and open source utility available at https://pdfsam.org/en/

**Comment by museflip** [comment]
A very valuable Open Source (GPL V3) alternative to PDFSam is : 
PDFTKBuilder (http://www.angusj.com/pdftkb/).
PDFTKBuilder is also packaged for Portableapps (http://portableapps.com/)

**Comment by de-wolff** [comment]
My intension for this ticket was to add a feature request.
I am aware of the several ways to work around the problem, but I still think it should have value when we could transcribe partial pdf's

**Comment by hbitteur** [comment]
Issue closed because feature is now implemented in 5.3-alpha
