### ISSUE TITLE
questions

### ISSUE THREAD

**Issue by chrismeo** [Audiveris/audiveris#242]
Hi there,
how to decode .mxl files? I want to get the xml out of the compressed .mxl file.
Thanks in advance!
P.S. I know there are free tools to do that, but I am looking for the algorithm,

**Comment by museflip** [comment]
Hello,
I can't find out what is exactly your need.

* You can find a good explanation of MusicXML structure there : https://www.musicxml.com/tutorial/file-structure.
* You can simply get the .xml out of the compressed .mxl find with a software like 7zip which is free and open source.
* Musescore can decode both .mxl and .xml file.

If you are really looking only for the uncompress algorithm, this has nothing to do with MusicXML and even music : you should analyse 7zip code.

Hope it helped you.

**Comment by maximumspatium** [comment]
> I want to get the xml out of the compressed .mxl file.

You can use either Unix' `unzip` command or any compatible utility for Windows (7zip for example). But in the most cases, it's unnecessary because modern notation editors can import compressed MusicXML directly.

> I know there are free tools to do that, but I am looking for the algorithm,

The algorithm is called `Deflate`. Its description is freely available elsewhere, see for example [this Wikipedia article](https://en.wikipedia.org/wiki/DEFLATE).

Maybe you can tell us what you're trying to do, so we can help you to pick up the right tool for your task...

**Comment by chrismeo** [comment]
Thank you so much!
