### ISSUE TITLE
editing multipage score during transcription makes problems on following pages

### ISSUE THREAD

**Issue by Bacchushlg** [Audiveris/audiveris#269]
during transcription of a multipage score it is possible to edit the first page(s) while the transcription is performed on the following ones.
This works without problem on the 1st page. But on the 2nd page a problem appears with the shapes. It seems that the list of shapes is initially the one of the 1st page, and when adding a shape to the 2nd page, this shape is added to the 1st page.

Switching once between 1st and 2nd page tabs resolves the problem.

**Comment by hbitteur** [comment]
Thanks Baruch.

There was a race condition in switching between sheets, that could sometimes result in the display of the wrong boards when the loading or processing of a sheet took too long.

The other switches performed later on were done with all involved sheets ready, so the race condition did not occur.

This is now fixed in commit a158a2c069d21f7b20a3c3874fab7204448c6238 in development branch.
