### ISSUE TITLE
Build hangs at 81%, 2 failed tests

### ISSUE THREAD

**Issue by miclill** [Audiveris/audiveris#27]
org.audiveris.omr.moment.LegendreMomentsTest > testAllShapes FAILED
    java.lang.ExceptionInInitializerError at LegendreMomentsTest.java:26
        Caused by: org.audiveris.omr.WellKnowns$InstallationException at LegendreMomentsTest.java:26

org.audiveris.omr.moment.ARTExtractorTest > testAllShapes FAILED
    java.lang.NoClassDefFoundError at ARTExtractorTest.java:27
> Building 81% > :test > 102 tests completed, 2 failed

I'm running debian stretch with openjdk version "1.8.0_141"
OpenJDK Runtime Environment (build 1.8.0_141-8u141-b15-1~deb9u1-b15)
OpenJDK 64-Bit Server VM (build 25.141-b15, mixed mode)

**Comment by maximumspatium** [comment]
Unfortunately, it's not clear to me how do you invoke Audiveris. Could you post the precise command that causes this failure?
Did you tried `gradle clean run`?

**Comment by mercuriete** [comment]
Hi somehow i hit the same bug trying to create a travis configuration file to add continous integration to this project.

Maybe this problem is because @miclill and I was trying to run test without X server.

this is the output -> https://travis-ci.org/mercuriete/audiveris/builds/300727509

```
org.audiveris.omr.ui.MouseWheelTest > play FAILED
    java.awt.HeadlessException at MouseWheelTest.java:102
org.audiveris.omr.ui.ZoomTest > testZoom FAILED
    java.awt.HeadlessException at ZoomTest.java:60
```

I will try to start Xvfb to run this test.

the another solution is skip those test when detecting headless configuration.

Cheers.

**Comment by mercuriete** [comment]
Sorry for the noise,
reading this bug carefully, it seems my bug is different to this one.

**Comment by infojunkie** [comment]
Same thing happened for me until I installed Tesseract - via the `tesseract-ocr` package on Ubuntu. It would be good to explicitly mention Tesseract as a prerequisite for building and running.

**Comment by maximumspatium** [comment]
> It would be good to explicitly mention Tesseract as a prerequisite for building and running.

Our [README](https://github.com/Audiveris/audiveris/blob/master/README.md) already mention Tesseract as required component. Quote:
_Please keep in mind that Tesseract is mandatory for both building and running Audiveris. It's currently not possible to use Audiveris without Tesseract._

Audiveris should work without explicit installation of `tesseract-ocr` on Ubuntu like it does for me. That's because Javacpp automatically installs libtesseract together with its Java bindings. What do you need to do manually is the installation of language files. Without them, Tesseract won't work. The README does mention that quite clear as well.
