### ISSUE TITLE
Bad recognition

### ISSUE THREAD

**Issue by andylinpersonal** [Audiveris/audiveris#276]
Cannot recognize some time signature like 12/8 ...
And Staccatissimo in reverse side cannot be recognized either.

**Comment by maximumspatium** [comment]
Can you share the score of interest with us?

**Comment by andylinpersonal** [comment]
> Can you share the score of interest with us?

This one.
[supercell - 罪人.pdf](https://github.com/Audiveris/audiveris/files/3170325/supercell.-.pdf)

**Comment by maximumspatium** [comment]
The issue title "bad recognition" is a bit exaggerated IMHO. Yes, the time signatures must be added manually which is a bit inconvenient. Despite a couple of minor corrections, the recognition works well. I was able to fix all imperfections in about 20 minutes and, finally, to play the piece back in Musescore.

The score violates the notation spacing rules by making augmentation dots overlap with slurs in some cases. Here an example:

![Augmentation dot overlap](https://user-images.githubusercontent.com/6561800/57585972-29df0c00-74ef-11e9-907e-e97ffe5734ca.png)

So we cannot blame Audiveris for not able to recognize that automatically...

Unsupported [staccatissimo](https://en.wikipedia.org/wiki/Staccato#Staccatissimo) symbols can be easily added in every notation software so that's a non-issue for me...
