### ISSUE TITLE
Delete/insert a page from/into an .omr file

### ISSUE THREAD

**Issue by oleedd** [Audiveris/audiveris#282]
Is there support for that?

**Comment by hbitteur** [comment]
See [HandBook sheet section](https://bacchushlg.gitbooks.io/audiveris-5-1/content/menus/sheet.html). From this Sheet menu you can invalidate a sheet: It is still present in the book but no longer taken into account in music processing.

There is no way to insert a sheet into a book.

Advice: you can use an external program to split & merge PDF files, for example the free version of [PDFsam](https://pdfsam.org/), and submit the resulting PDF file to Audiveris..

**Comment by oleedd** [comment]
The problem is I caught a bug in Audiveris. 6 from 7 pages were recognized good - and I made many corrections with tuplets, clefs among staffs and some another items. But the last page was recognized bad and it is red but after single recognition the 7-th page was recognized very good. So I have 2 .omr files.
The thing is that I can't add tuplets to the red page (other items may be added). All note elements of sixlets are good, there appears 6 green and 1 red lines but it gives the "Exception in addInters java.lang.NullPointerException" error.
So I need to replace the last page with a page from another .omr or to fix this error.

**Comment by Bacchushlg** [comment]
I do this normally in my notation program (I use MuseScore). Here it is rather easy to add / remove measures / pages.
Splitting of a score happens also sometimes due to changes in the systems. Also in such a case, the notation program is the best way to solve such problems.

**Comment by maximumspatium** [comment]
I already considered adding a dialog for advanced image import à la SmartScore:

![SSImageImportDialog](https://user-images.githubusercontent.com/6561800/57470866-2f87e800-728a-11e9-8091-d8d2ab2cda04.png)

Such a dialog would help to solve the following tasks:

- gather several images into one book. This is sometimes the case when images were acquired using a scanner/camera producing one image per page
- rearrange pages in a multi-page document (would help with #220)
- split a multi-page document into several books (would help with #220)

For the time being, all the above tasks need to be performed in an external tool which is inconvenient. Fixing that would be nice. That's why this is a low-priority feature in my list...

@oleedd 
If Audiveris fails to process some document, you should file an appropriate bug and share the document that triggers the bug instead of requesting features helping to work around bugs...

**Comment by oleedd** [comment]
> If Audiveris fails to process some document, you should file an appropriate bug and share the document that triggers the bug instead of requesting features helping to work around bugs...

OK. The thing is I have noticed (from another issues) that the Audiveris team doesn't have time to inspect all errors. That is why I didn't upload the file initially and just asked. Here is the file (the problem is in the last page - tuplets can't be added):
[File.zip](https://github.com/Audiveris/audiveris/files/3163298/File.zip)

About SmartScore. You still don't hear me. I need to insert/delete a page with .omr files, not image types. I can't open an .omr file with Smartscore. I don't want to lose many corrections which were made for a ling time.

> For the time being, all the above tasks need to be performed in an external tool which is inconvenient. Fixing that would be nice.

If Audiveris can export files, it should be easy to make insert/deletion pages. For deletion - just to close a tab (no need a difficult interface). For insert - now it works but the save button stops to work. Also need swapping tabs (by dropping). Without any difficult interfaces.

**Comment by oleedd** [comment]
> If Audiveris fails to process some document, you should file an appropriate bug and share the document that triggers the bug instead of requesting features helping to work around bugs...

OK. The thing is I have noticed (from another issues) that the Audiveris team doesn't have time to inspect all errors. That is why I didn't upload the file initially and just asked. Here is the file (the problem is in the last page - tuplets can't be added):
[File.zip](https://github.com/Audiveris/audiveris/files/3163298/File.zip)

About SmartScore. You still don't hear me. I need to insert/delete a page with .omr files, not image types. I can't open an .omr file with Smartscore. I don't want to lose many corrections which were made for a long time.

> For the time being, all the above tasks need to be performed in an external tool which is inconvenient. Fixing that would be nice.

If Audiveris can export files, it should be easy to make insert/deletion pages. For deletion - just to close a tab (no need a difficult interface). For insert - now it works but the save button stops to work. Also need swapping tabs (by dropping). Without any difficult interfaces.

**Comment by oleedd** [comment]
> If Audiveris fails to process some document, you should file an appropriate bug and share the document that triggers the bug instead of requesting features helping to work around bugs...

OK. The thing is I have noticed (from another issues) that the Audiveris team doesn't have time to inspect all errors. That is why I didn't upload the file initially and just asked. Here is the file (the problem is in the last page - tuplets can't be added):
[File.zip](https://github.com/Audiveris/audiveris/files/3163298/File.zip)

About SmartScore. You still don't hear me. I need to insert/delete a page in .omr files, not image types. I can't open an .omr file with SmartScore. I don't want to lose many corrections which were made for a long time.

> For the time being, all the above tasks need to be performed in an external tool which is inconvenient. Fixing that would be nice.

If Audiveris can export files, it should be easy to make insert/deletion pages. For deletion - just to close a tab (no need a difficult interface). For insert - now it works but the save button stops to work. Also need swapping tabs (by dropping). Without any difficult interfaces.

**Comment by maximumspatium** [comment]
> Here is the file (the problem is in the last page - tuplets can't be added)

Sure they can. Here is the proof:

The PDF exported directly from Audiveris for the page 7: [etude7.pdf](https://github.com/Audiveris/audiveris/files/3163954/etude7.pdf)

The corresponding MusicXML (plays well in MuseScore): [etude7.mxl.zip](https://github.com/Audiveris/audiveris/files/3163994/etude7.mxl.zip)


The OMR file itself:  [11.omr.zip](https://github.com/Audiveris/audiveris/files/3163961/11.omr.zip)

The last passage (that long group of grace notes) need to be re-entered in your scoring software (Sibelius) because Audiveris doesn't support it yet. Not a big deal...

**Comment by oleedd** [comment]
Hm. But why I have an error after trying to add tuplets? Proof:
![image](https://user-images.githubusercontent.com/36125949/57487265-cf5c6a80-72b8-11e9-940e-0316e53c2fdd.png)
In your repair .omr file I already can add tuplets without errors in the last page. Strange.

**Comment by hbitteur** [comment]
> The thing is I have noticed (from another issues) that the Audiveris team doesn't have time to inspect all errors.

Sorry, I'm deep in re-designing the code for voices and time slots, which is not that simple if we want to address almost all cases.
We just can't "stack up interrupts". That would interrupt the current work to jump to the fix of a problem, which could itself be interrupted by another problem, etc, etc.

Today, Audiveris "team" is composed of 3 people, with 2 of them on their free time only.

**Comment by maximumspatium** [comment]
@oleedd When I open your OMR file and try to assign tuplet numbers I get that NullPointerException too. It looks like the page transcription has been broken up in the CUE_BEAMS step.

Try to re-run recognition by performing the following commands:
- `Sheet->Reset Sheet to BINARY`
- `Step->PAGE`

This works for me.

**Comment by oleedd** [comment]
Just for experiment I have re-run recognition of the pdf file. The last page is again red (even if notes are green but #/♭ are missed). And again tuplets can't be added with the same error. I see this error in the log:
`[11#7] Error in performing [LOAD, BINARY, SCALE, GRID, HEADERS, STEM_SEEDS, BEAMS, LEDGERS, HEADS, STEMS, REDUCTION, CUE_BEAMS, TEXTS, MEASURES, CHORDS, CURVES, SYMBOLS, LINKS, RHYTHMS, PAGE] java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError: Java heap space`
But very strange that recognition of the single last page works. Maybe it is worth of inspection.
Pdf: http://library.newmusicusa.org/files/1090/11.pdf

**Comment by oleedd** [comment]
Just for experiment I have rerun recognition of the pdf file. The last page is again red (even if notes are green but #/♭ are missed). And again tuplets can't be added with the same error. After scanning there is this error in the log:
`[11#7] Error in performing [LOAD, BINARY, SCALE, GRID, HEADERS, STEM_SEEDS, BEAMS, LEDGERS, HEADS, STEMS, REDUCTION, CUE_BEAMS, TEXTS, MEASURES, CHORDS, CURVES, SYMBOLS, LINKS, RHYTHMS, PAGE] java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError: Java heap space`
But very strange that recognition of the single last page works. Maybe it is worth of inspection.
Pdf: http://library.newmusicusa.org/files/1090/11.pdf

**Comment by oleedd** [comment]
I think it is need to add insert/deletion pages only for .omr files - no need for pdf/tiff because many programs/online services support it but no programs/services for .omr files.

**Comment by hbitteur** [comment]
The Split & Merge features is now on the TODO list for 5.3 release.
Thanks Maxim for the SmartScore model (I knew the PDF-SAM model for PDFs, this one is more focused on OMR)

**Comment by hbitteur** [comment]
Commit 0b414c132487db6c8a19481b18c2eca3ae76113e provides the feature in development branch.
Max will certainly notice that the provided user interface closely resembles his example...
Handbook to be updated accordingly.

**Comment by Bacchushlg** [comment]
I just tried the new feature. The dialog is perfect, it provides everything for full flexibilty.
What is unclear to me: how can I create a book from all loaded images BEFORE transcription? 
Up to now it seems I need to transcribe before merging the sheets. 
It would be fine to allow merging before transcription: beside the comfort to do transcription with a single mouse click, it is really useful because the scores timing is forwarded to the following sheets

**Comment by hbitteur** [comment]
This is the first working version.  I still need to:
- Write the related handbook section
- Allow the use of such playlist in batch

I understand and fully support your remark on handling images before they are transcribed.
But first, some clarification is obviously needed.

Audiveris engine handles the collection of books being processed, whether in batch or interactive mode.

The current version of S&M works only from UI (the playlist is volatile and used only to drive the building of the compound .omr file). The 3 upper buttons allow respectively to:
1. **Load book** (from some .omr file) into the playlist (and into the books collection if not already there)
2. **Load image** (from some image file, for example a .pdf file) _as a book_ into the playlist (and into the books collection if not already there)
3. **Include book** (from some book already loaded in the books collection) into the playlist

When I say "load an image as a book", I mean just creating an almost empty book, containing the list of sheet stubs. Only if the user wants to preview an input sheet, the LOAD step is run on it, so that its binary image can be built and displayed (and stored in the related book). Nothing more, and especially no long/difficult transcription.
So, you can indeed create a book from all loaded images before **_real_** transcription.

The reason for this approach is that the S&M final "Save As" button (which could be better named "Build compound"), results in the building of a compound .omr file, which can be processed just like any other .omr file. As you can expect, the sheets inside this compound book are copied from the selected sheets of the selected books (and image books).

The copy is made directly from disk to disk, no unmarshalling/marshalling is involved, this allows efficient processing of large .omr files. This is why all .omr parts must be saved before the building can be launched.

This is a "**deep copy**", not a copy by reference, to avoid any later problem of concurrent modification. For instance, if the compound .omr file were a simple list of references to say part1.omr and part2.omr files, then there would be a high risk for the user to later modify say part1.omr, an event which could not be notified back to the compound .omr file. Moreover, the forwarding score timing from one sheet to the other could not occur across separate part.omr files.

Only when rechecking the compound .omr file, the engine could:
- discover that some referenced part.omr files have been modified (assuming these files still exist)
- recompute the forwarding from any sheet to the next one, and rebuild the resulting scores.

I'm not saying this would be impossible, just that this is not the approach I've chosen for safety reasons.
We can review this choice, of course. But let us make sure we do consider all the aspects of the decision.

For the batch implementation, the idea is to:
1. Let the user prepare a playlist (an xml file listing the files to include and their sheets to select). This playlist file could be written manually or be an output of the S&M UI dialog.
2. Let the engine take the playlist as input and build the resulting compound .omr file

**Comment by hbitteur** [comment]
Thinking more about it, perhaps we can even avoid to run the steps known as "early steps", which are currently defined as:
- LOAD: Read (a precise sheet of) the image file and, whatever its original format (channel count, alpha channel, ...), build the single-channel GRAY image from it.
- BINARY: From the GRAY image, apply the chosen binarization filter, to obtain the BINARY image.

This has been like this since the beginning of Audiveris, even before the notion of .omr files. And the reason was that there was no point in handling a sheet, for display or for transcription, without its BINARY data. Nothing could be done or displayed with a sheet without this data.

But the notion of playlist sheds a new light on these early steps, because there is now an interest in dealing with a sheet only via its existence (and of course its ability to later retrieve its content on demand).
To be concrete, we could deal with a playlist in which some excerpts are just the path to an input image file (plus a sheets specification within this file if so needed). In fact, this is how the Excerpt class is already defined in [PlayList.java](https://github.com/Audiveris/audiveris/blob/0b414c132487db6c8a19481b18c2eca3ae76113e/src/main/org/audiveris/omr/sheet/PlayList.java#L243) today, but the current implementation of the compound building uses a BookExcerpt which is a derived class of Expert class because it handles a book.

So, still thinking out loud  (this is the main purpose of this message: discuss the pros and cons before implementation gets too concrete), we could have a plain playlist sequence of (file path + sheet numbers) as an input for batch or interactive processing:
- If input is an **image file**, the engine builds a book skeleton on-the-fly, and each of the resulting "lean" sheets (without GRAY/BINARY data) would be directly marshalled to disk at compound building time.
- If input is a **book file**, each sheet content is copied disk-to-disk to compound file, as in the current implementation.

The main drawback is that the resulting compound book file, if it still contains such lean sheets, will have to retrieve the image in order to get the GRAY/BINARY data. And the path to the image file may be unusable on another machine...
I'm afraid this is the end of "lean" sheets. The compound file MUST contain the gray or binary data for every sheet handled, otherwise it would not be transferable!

Sorry for this long message.
To conclude, a playlist with image files would be OK as input for compound building (batch or interactive), but the resulting compound book needs to contain image data for every sheet in the compound.

**Comment by Bacchushlg** [comment]
Works almost perfect now.
Just a minor query: would the file open dialog for image input allow multiple selection? If I have scanned input files name page1, page2,...,page14 this would improve handling a little bit.

And now something very special (please don't shoot me...): I sometimes have scores of minor quality, where I notice during transcription that one or two pages are of so bad quality that transcription fails (so no output is generated for this page). In many cases I achieve a better result after doing some image improvement by filtering (in most cases: gaussian blur, color curve adjust, sharpen). As in this stage I may already have done some manual editing to the first pages (I always start editing when the first page is transcribed), it would be great to have the possibility to exchange the image input of an existing omr file.
Possible?

**Comment by hbitteur** [comment]
> would the file open dialog for image input allow multiple selection? If I have scanned input files name page1, page2,...,page14 this would improve handling a little bit.

Multiple selection is already available, but just when dropping from your file explorer. And the sequence of dropped files may not be preserved. I explained this in the new handbook section, but this new handbook is still not visible. I need to work on this.
But OK, I will modify the user interface so that:
1. you can load a multiple selection
2. the order within the selection is preserved

> As in this stage I may already have done some manual editing to the first pages (I always start editing when the first page is transcribed), it would be great to have the possibility to exchange the image input of an existing omr file.
Possible?

Yes indeed, it is already possible (and explained in the not-yet-visible handbook section). I even took this precise example! :-)

The easiest and more convenient way for everyone will be to merge development to master branch, this will make the new version of handbook immediately visible. I'll do this right now.

**Comment by hbitteur** [comment]
Push done!
And the handbook is visible. You can go directly to [Split and Merge section](https://audiveris.github.io/audiveris/_pages/main/split_merge/)
Please tell me if this fulfills all your requirements.

I will address your multiple selection in the coming days. I know what I have to modify. Not very difficult.

**Comment by hbitteur** [comment]
Multi-selection is now available from the "Load files" button which replaces the previous 2 buttons named "Load book" and "Load image".
And the handbook has been updated accordingly.

I'm now closing the various related issues #129, #220, #232, #282
