### ISSUE TITLE
how to transform jpg to mxl more quickly

### ISSUE THREAD

**Issue by JavaCS** [Audiveris/audiveris#285]
hi
I tried some music score images with audiveris. The accuracy is enough for us, but it was very slow to transform from jpg to mxl. How to improve the performance? Using a more powerful computer, or with GPU or some other methods? thanks.

**Comment by maximumspatium** [comment]
> The accuracy is enough for us, but it was very slow to transform from jpg to mxl

How slow is your processing? Can you report concrete numbers?

> How to improve the performance? Using a more powerful computer, or with GPU or some other methods?

It depends on several factors like available CPU and memory, input file resolution etc. Can you share details regarding your processing environment?

Moreover, it would be helpful to look at images you're trying to process.

Without the above mentioned facts it's very difficult to give any meaningful recommendations...

**Comment by JavaCS** [comment]
It may cost 15 to 40 seconds to process one image on my MacBook Pro with CPU of Intel Core i5 2.7GHz and 8GB memory. 
And the image is like
![002](https://user-images.githubusercontent.com/778726/58400561-0048e780-808e-11e9-83c3-f21cc5cc9498.png)

**Comment by hbitteur** [comment]
@JavaCS 
Orders of magnitude of processing time for this kind of sheet are as follows:
- In old 4.x version, it was about 5 seconds,
- In current 5.x version, about 30 seconds,
- In 6.0 prototype, it's a matter or minutes (typically 1 to 3).

I'm giving you these numbers, so that you don't keep too high expectations on speed.

If your main concern is speed, rather than transcription quality, then the old 4.x version is still available [here](https://github.com/Audiveris/audiveris-eg). Beside its low recognition capabilities, an additional drawback of 4.x version is you cannot save OMR data to disk, which 1/ limits the processing to small scores and 2/ imposes to perform all processing and (limited) user correction on the fly, before exporting to MusicXML.

5.x is slower but provides a better OMR engine, a true user-oriented UI for corrections, and the ability to save/restore OMR sessions. This last point is of paramount importance, because it allows to decouple the initial OMR engine processing  from manual user corrections. In other words, you can run the OMR engine in batch (at night for example, on say hundreds of images) and then get back later to every processed sheet for manual verification and correction. Only the second part (the manual part) is done in "real time".

Depending on your constraints, your mileage may vary... :-)

**Comment by JavaCS** [comment]
@hbitteur 
Thank you for your answers, I'll try the 4.x version.
And just for a technical discussion, I found [playscore.co](http://playscore.co) and it's very fast (2-3s) for OMR. I'm wondering how it works...

**Comment by maximumspatium** [comment]
> And just for a technical discussion, I found playscore.co and it's very fast (2-3s) for OMR.

It's not a technical discussion at all because you're comparing apples to oranges. I've just gave playscore a try by installing Playscore Lite App in my Android phone (it's a Samsung smartphone from 2017).
Playscore Lite is capable of recognizing pictures taken with the internal camera only. The recognition itself takes in my device at least 20 secs, sometimes even longer. Considering the fact that that app recognizes only a small subset of the notation (staves, notes and rhythm), that isn't significantly faster than other OMR engines out here. Audiveris 5.x processes a lot more including articulation, dynamics and text. All this requires additional computation time and resources.
Regarding accuracy, Playscore Lite seems to deliver a subjective accuracy of approx. 70% (counted as number of correctly sounding bars divided by the number of total bars per page). Audiveris 5.x offers significantly higher accuracy. Moreover, Playscore Lite seems to be sensitive to camera images - I've tried to recognize the same sheet several times and each time I got different results spanning from rather poor to acceptable.
You may call the above "unfair" (or biased) comparison but we couldn't do it better when comparing a state-of-the-art OMR application (Audiveris) with a nice playtoy (Playscore Lite)...
In order to bring back some fairness by comparing apples to apples, I've processed the score you posted earlier in [Capella-scan](https://www.capella-software.com/us/index.cfm/products/capella-scan/info-capella-scan/) v7 - the fastest OMR engine I ever seen. It looks approx. 6 secs to process while Audiveris requires about 30 secs for the same score and comparable results. This is still a significant difference when looking at raw numbers but frankly spoken, 30 secs of automatic processing sounds are vanishingly small compared with 15 minutes manual typing, dosn't it?

**Comment by JavaCS** [comment]
I tied with playscore2 not playscore lite (maybe playscore2 used new version of their OMR engine), and with my iPhone 7 Plus. Most of the time for OMR is 2-3 seconds.

May I explain what we want to do:
We designed an app for teaching piano. Users can upload the photo of the music sheet they are learning. After OMR processing we can get some information about what the music sheet really are. If the music sheet can match some one in our music sheet library, we'll return the matched one. So if the OMR processing can be done in 5 seconds, the user can wait for it. If not we must design another async  way for users.

Maybe it's an unfair comparison, so i said it's only a discussion. Apologize if offending.

**Comment by maximumspatium** [comment]
> We designed an app for teaching piano. Users can upload the photo of the music sheet they are learning. After OMR processing we can get some information about what the music sheet really are. If the music sheet can match some one in our music sheet library, we'll return the matched one. So if the OMR processing can be done in 5 seconds, the user can wait for it. If not we must design another async way for users.

The above looks like a real technical discussion so we can proceed with identifying your requirements.

IIRC, you're looking for a system aiming at music identification and search. You are calling Audiveris synchronously (that is your app is blocking waiting for the OMR thread to complete). That imposes the following time/performance constraint: if the OMR thread blocks for a longer period without a sign of life, the user may think that something is going wrong with the app. Moreover, for the purpose of music identification you're interested mostly in notes and rhythm. Precise recognition of articulation and text items isn't that important so there is no need to spend additional time processing them.

Is the above true so far?

**Comment by JavaCS** [comment]
Yes, that's true. "music identification and search" is what we want

**Comment by maximumspatium** [comment]
Well, Audiveris wasn't directly designed for that purpose. Although it can be called in the batch mode (without GUI), it's still a monolithic engine with a limited control and customization possibilities.

As opposite, Playscore is built around [ReadScoreLib](http://www.dolphin-com.co.uk/readscorelib.html) - a raw OMR engine implemented as a C library [including a dedicated API](https://www.playscore.co/wp-content/uploads/2016/05/ReadScoreLib-description.pdf).

Audiveris need to be adapted to work like this. The following need to be added:
- a greater control over input, see https://github.com/Audiveris/audiveris/issues/282#issuecomment-490983916
- specification of image regions for recognition (for the moment being, Audiveris processes whole images only)
- notification system for advanced error and progress report
- more flexible control over processing (i.e. skipping certain steps like text recognition etc.)
- an API for partial retrieval of recognition results (for the moment being, a huge XML file is everything you get forcing you to parse XML to extract specific information. Smth like "tell me number of bars in sheet 1" would be great).

The building blocks for all this are already there. Some more control is possible via [command line options](https://github.com/Audiveris/audiveris/wiki/CLI-Arguments) but that doesn't reach the sophistication level of a SDK.

We are a small team and doesn't have enough resources for implementing the above mentioned stuff. But we can assist someone wishing to undertake such an extension...

**Comment by JavaCS** [comment]
Thank you very much.
I know more about Audiveris and OMR
