### ISSUE TITLE
Resetting book/sheet to binary spits out errors

### ISSUE THREAD

**Issue by maximumspatium** [Audiveris/audiveris#293]
Steps to reproduce:

1) open an image in Audiveris
2) select Sheet --> Reset Sheet to BINARY
3) click on the image somewhere

_**Error reading data from initial.png**_ is displayed in the log window.

1) open an image in Audiveris
2) select Book --> Reset Book to BINARY

**_Error reading data from BINARY.xml_** is displayed for every sheet in the log window.

3) click on the image somewhere

_**Error reading data from initial.png**_ is displayed in the log window.

**Comment by maximumspatium** [comment]
@hbitteur Hervé, can you kindly look into this issue? It's valid for Windows as well.

**Comment by hbitteur** [comment]
Fixed with commit 2320721febf1223822366b0001ae23b69a131b6f in development branch (the master branch did not show this error).

The message related to BINARY.xml was perhaps a consequence of error on initial.png, I'm not 100% sure. I could not reproduce the case, could you check on your own and report the results.

**Comment by maximumspatium** [comment]
The issue seems to be fixed. I was able reproduce it before your fix in both MacOS and Windows from within `development` branch. Let's close the issue for now.
