### ISSUE TITLE
How to build from source code release instead cloning the full repo ?

### ISSUE THREAD

**Issue by YruamaLairba** [Audiveris/audiveris#298]
Hello, 

i tried to build audiveris by downloading source code from a release snapshot instead cloning the repo. I get a "Task :git_build FAILED" when running ./gladlew . Seems build instructions from handbook only work when you have cloned the git repository. Is there a way to build from a snapshot ?

**Comment by maximumspatium** [comment]
> Seems build instructions from handbook only work when you have cloned the git repository.

Yes, that's true. Our Gradle build script runs a task that asks Git to report the recent commit hash. That task will fail when no Git repository is present (i.e. when building from snapshot or source download).
For the time being, you need to clone Audiveris Github repository or to modify `build.gradle` script to skip Git invocation, see `git_build` task: https://github.com/Audiveris/audiveris/blob/2f64d06c1ac7671c40d6c597be36512162ab00ed/build.gradle#L173-L181
In the last case, you need to hardcode a valid commit hash into `project.ext.programBuild` variable. Otherwise, `build.gradle` will fail...
