### ISSUE TITLE
Muting "too large image" warning

### ISSUE THREAD

**Issue by longyuxi** [Audiveris/audiveris#299]
First of all, the software is awesome and greatly reduces the time I spend converting sheet music! Big thumbs up!

However, as I am trying a use it on one specific sheet music, a dialog box pops up complaining that the image is too large whenever the software moves on to a new page. I want to mute all these dialog boxes and let the software ignore its size. I have looked into the manual and found no answer. Is there a way to do it?

**Comment by hbitteur** [comment]
This is a protection against too large images, generally due to a much too high resolution. Trying to process them will quickly end up in an enormous need for memory resources.

There is no direct way to switch off this protection.
However, you can cheat by setting the maxPixelCount constant (default is 20_000_000 pixels!) to something higher than your image size (width x height).

You can do so via menu Tools > Options, then typing maxPixelCount in the search field. Then modify the value.
But don't expect miracles in terms of processing... :-)

**Comment by piegamesde** [comment]
If some runs into this with the command line: The batch mode doesn't warn when the image is too large, it simply fails with an error. Adding `-option org.audiveris.omr.step.LoadStep.maxPixelCount=200000000` to the command works for me.

**Comment by Tridu33** [comment]
> First of all, the software is awesome and greatly reduces the time I spend converting sheet music! Big thumbs up!
> 
> However, as I am trying a use it on one specific sheet music, a dialog box pops up complaining that the image is too large whenever the software moves on to a new page. I want to mute all these dialog boxes and let the software ignore its size. I have looked into the manual and found no answer. Is there a way to do it?

https://zhuanlan.zhihu.com/p/569432113
