### ISSUE TITLE
Update Wiki with GUI/layman-friendly instructions

### ISSUE THREAD

**Issue by matthras** [Audiveris/audiveris#32]
I was able to figure out how to use the GUI, but I feel this can be made much more accessible to the layman with proper instructions on the Wiki.

I intend to submit changes myself, but I'm pretty absent-minded, so am leaving this here for future reference.

**Comment by maximumspatium** [comment]
Hi Matthew,

you're right - there is no actual description of the GUI in the latest audiveris' version because this GUI isn't intended for use by regular end-users.
You may still find our [older handbook](https://github.com/Audiveris/audiveris-eg/blob/master/data/www/docs/manual/handbook.html) useful. Just clone [audiveris-eg](https://github.com/Audiveris/audiveris-eg), navigate into `/data/www/docs/manual/` and open `handbook.html` from there.

Hervé is currently working on improving the new GUI. We'll update the docs when it's ready.

**Comment by hbitteur** [comment]
We are about to release a 5.1 version, with what we call a basic UI, enough to correct OMR mistakes.
Stay tuned.

**Comment by hbitteur** [comment]
The user-oriented GUI is now available and documented in [handbook](https://bacchushlg.gitbooks.io/audiveris-5-1/content/).
I'm closing the issue.
