### ISSUE TITLE
Improve support for high-DPI displays

### ISSUE THREAD

**Issue by hekkup** [Audiveris/audiveris#323]
The UI font size is very small on high-DPI displays.
It's possible to change font size for different sub-views of UI (e.g. log) making the situation a little bit better but this is not possible for the whole UI.
There's a mention about high-DPI displays in issue #51 (closed issue) so it looks like it's coming alongside JDK9 support. I added this issue because it _is_ an issue currently.

**Comment by hbitteur** [comment]
I personally have no access to such high DPI device, and can't try anything.
With a quick Googling, I just stumbled upon this interesting article [https://superuser.com/questions/988379/how-do-i-run-java-apps-upscaled-on-a-high-dpi-display](https://superuser.com/questions/988379/how-do-i-run-java-apps-upscaled-on-a-high-dpi-display)

Could you elaborate on which Java version you use.  I suppose java 8 for last release (5.1). Although  Java 11 is supported for the coming release (you can get a pre-release by pulling the "development" branch).
I'm asking this because the article indicates several workarounds, the best one seeming a Java upgrade.

Could you try on your own and keep us posted?
Thanks in advance.

**Comment by hekkup** [comment]
So far I have tested setting Java properties -Dsun.java2d.uiScale=FLOAT, -Dsun.java2d.dpiaware=BOOL with any combination of values but they don't work. I used the environment variable JAVA_OPTS. When printing the command with which the application is run (echo "$JAVACMD $@" in gradlew), it looks like they are getting actually used.

I'm on Ubuntu 19.04.

I have tried OpenJDK 8, 11, and 13 (stock Ubuntu packages) as well as Oracle Java 13 (downloaded the DEB package from Oracle). Oracle is quite intrusive towards people who try downloading older Oracle Java versions so I didn't go there.

With Java 13 I needed to modify the source in two files: Book.java and ZipFileSystem.java. These had FileSystems.newFileSystem(path, null) but need to remove the null as it'll cause ambiguity in the new API.

The only thing that has worked for UI scaling was running
  GDK_SCALE=n ./gradlew run
but that only works with integer numbers, and with scale factor 2 it will cause the UI to be now too big.

I have also tried to change the Java/Swing look and feel, to no avail. I have tried changing it from the application settings but it doesn't work. Setting it with swing.properties will crash the application -- maybe this is the reason it doesn't work from application settings either. The LAF I used was Radiance (https://github.com/kirill-grouchnikov/radiance). The two different versions I tried was Ubuntu stock package with OpenJDK 8, and the newest one from GitHub repository with newer Java versions.

The last thing I tried was to modify the code and set font for JMenus and JMenuItems in MainGui.defineMenus(). That kind of works but only partially since some menu items are added from somewhere else dynamically and they are normal size (too small). Calling UIManager.put("Menu.font", font) doesn't work (maybe should be done somewhere else).

There are some hacks using VNC locally but I'd really prefer the application itself working.

**Comment by hekkup** [comment]
Workaround for poorly working DPI support in Java on Linux would be to enable changing font size with settings.

**Comment by hbitteur** [comment]
@hekkup 
If I understand your 2 last messages correctly, the only way that works, at least for Linux, is to explicitly set a bigger font size for all menus used by Audiveris. Please correct me if I'm wrong.

This sounds possible.
There is no central code location in Audiveris where all menus would be created. The method MainGui.defineMenus() addresses only the global pull-down menus, not the popup ones which are created on-the-fly where they are needed.
So this will require some code inspection and modification to make it work for all menus, but that's all.

A side-effect of this enhancement would be to clean up the code, especially for the popup menus, and make them use injection from the resources .properties files. This is already up and running for pull-down menus, it enables language support for field names and tool tip , as well as icons and short-cut keys.
Today, popup menus don't use this injection, they use hard-coded english text, something I always wanted to fix but never found the time to do.

Now, assuming that all menus are now readable, will that be enough? I mean: are there other areas where similar "font zooming" would be necessary?

**Comment by hekkup** [comment]
Yes, the only sensible way for larger font I could make work was the programmatic way.

Similar font zooming would be useful for tool tips.

**Comment by maximumspatium** [comment]
I own a Microsoft Surface with a high DPI display. Audiveris UI with Java 8 was unusable due to too small text. After switching to Java 11 everything works just fine.
Sounds like a poor Java support on Linux.

**Comment by hbitteur** [comment]
I just pushed commit 100a4bcffe3ee8a38c08ac17bb60b260801a6356 on branch "menu-fonts".

It is the first version of a global handling of font sizes. I tried several things without great success, the commit I pushed uses an upfront setting of UIManager default main fonts and it works.

By default, no scaling is applied. But you can set the application constant "org.audiveris.omr.ui.util.UIUtil.globalFontRatio" to something different than default value (1.0)
[I will later provide something more user-friendly, but let's focus on the results first].

I have no access to any high-DPI device, so I can only extrapolate from what I can see on my standard device, when setting globalFontRatio to say 1.4
Every piece of text (menu, tooltip, log, ...) is correctly sized.

However, some boards (left column) exhibit real estate problems on my display (because text gets too big in too narrow fields)
Could you check on your own device and tell me how it looks, for Windows, for Mac and for Linux if you can.
Better yet, don't hesitate to post results.

Thanks for your help.

**Comment by hekkup** [comment]
It's much better now. I have tried the scale factor 1.4 and it's alright.
My screen is 1920 x 1080 at 14".
Here are a couple of screenshots, first with no scaling and then with scaling. I have removed the desktop toolbar from the screenshots. The log view font is already scaled larger than the default.

![audiveris-font-scale-factor-1_0-191216](https://user-images.githubusercontent.com/1606010/70870918-078c0000-1fa2-11ea-8c5c-dfd5fad66a7e.png)

![audiveris-font-scale-factor-1_4-191216](https://user-images.githubusercontent.com/1606010/70870923-107cd180-1fa2-11ea-84ea-6b3a135d5422.png)

**Comment by hekkup** [comment]
Addition: this was in Ubuntu Linux 19.04 & Oracle Java 13.
The scale slider text size at the left side poses no problem for me. I'm really happy about the font scaling in general so I don't care about a few lost pixel columns at the left side.

**Comment by hekkup** [comment]
The buttons at the right side get eaten out by the screen edge, though. It would help if there was a moving divider / resizer for the whole right side. The scrollbar at the bottom helps somewhat, but all of the buttons are not visible at the same time, which is not so nice.

Basic classifier buttons could be moved to the left side of the sub-view.

**Comment by hbitteur** [comment]
My mistake! I was referring to problems with boards on the RIGHT side (not on the left side as I wrote). So, yes I need to change the layout definition of these boards. This should not be too difficult.

Also, could you explain one thing: I'm not familiar with these high DPI screens but, for me, a 1920 x 1080 screen must be rather common today. It's the "full HD" definition. Perhaps the key point is that 14" is rather small for the number of pixels, then the resulting physical dimension of a single pixel is smaller than for say a 17" screen.
I work on a laptop with a extension monitor connected:
- laptop: 17", 1600 x 900
- monitor: 32", 2560 x 1440
Windows 10 display is extended, rather than duplicated, on these 2 displays.

**Comment by hbitteur** [comment]
Here is the fix as commit c99256f5c0bff515b55b1bd7a068c675047b3f4e still in "menu-fonts" branch.
There is now a moving split between left and right parts of the main display, the right part being the boards column.
Please check if the scrollbar at the bottom of boards column does not impede you. It should not appear, even if you deliberately try to move the split too far on right. On Windows it's OK, but perhaps on Linux some default widths are a bit different.
Just tell me.

**Comment by hekkup** [comment]
Ok, the splitter works. The scrollbar doesn't appear.

The panel apparently doesn't redo layout so the sub-views in the column are too narrow compared to the panel width.

![audiveris-side-bar-Screenshot_20191222_124313](https://user-images.githubusercontent.com/1606010/71320796-2bc37180-24b9-11ea-92c3-bbcea6db6129.png)

**Comment by hbitteur** [comment]
In most cases, the layout of each board has been designed to fit within a (constant) width. Remember the width of the boards column could not be modified until the recent modifications.

For some simple boards, like the shape board in your example, it might be interesting to dynamically redefine the layout when the column width gets modified.
For the other ones, like the inter board or the classifier board in your example, I can't see any real interest.

I can give it a try though...

**Comment by hbitteur** [comment]
Done.
You can pull it from the "development" branch (to which I merge previous menu-fonts" branch)
