### ISSUE TITLE
Shortcut keys for zooming [feature request]

### ISSUE THREAD

**Issue by hekkup** [Audiveris/audiveris#329]
Could you please enable zooming in with '+' key, and zooming out with '-' key? I think that would ease use of Audiveris. There's the drag zoom widget at the edge of view, but keys are usually faster to use.

I tested pressing the keys in geometric-ui branch build and I couldn't see any immediate effect from them so I assume they are currently unused.

**Comment by hbitteur** [comment]
In MuseScore, CTRL + wheel up/down increases/decreases zoom (same thing today for Audiveris)

In MuseScore, CTRL + '+' increases zoom, CTRL + '-' decreases zoom and CTRL + '0' resets zoom to 100%.

Also, my favorite PDF viewer (Foxit Reader) uses the same shortcuts. Same thing for Firefox browser. And these are only 2 examples I just checked.

So, for Audiveris, I would suggest to use CTRL + '+/-/0', rather than '+/-/0' directly without CTRL, to increase/decrease/reset zoom level.

**Comment by hbitteur** [comment]
Done in commit 69f92d138db1f2fa2dcaaa5a3d7baa6ca56f51eb available in development branch

**Comment by hekkup** [comment]
I have tested the key shortcuts and mouse functions for zooming in Linux and they work.
