### ISSUE TITLE
Add shortcuts to tool tips [feature request]

### ISSUE THREAD

**Issue by hekkup** [Audiveris/audiveris#332]
This is quite common in different applications.
Somewhat related to #183 (cheat sheet for key bindings).

**Comment by hbitteur** [comment]
Done in commit 69f92d138db1f2fa2dcaaa5a3d7baa6ca56f51eb available in development branch

**Comment by hekkup** [comment]
Ok, I can see the shortcuts.
The shortcuts could be added in all tool tips in Audiveris.
Maybe the two-key shortcuts could be marked with the "standard" way, like "n + b" (plus character in between). Compare to e.g. Ctrl+X.
Would it be clearer if the keys were in parentheses? E.g. "NOTEHEAD_BLACK  (n+b)".
I don't know if that's so important, just thinking aloud.

**Comment by hbitteur** [comment]
Well, let's see how the shortcuts appear in pulldown menus:

![image](https://user-images.githubusercontent.com/22053634/70387697-6ea92380-19a8-11ea-8876-657920bee6b0.png)

These menus are built automatically by the underlying Swing Application Framework based on resource .properties files. (In other words, we don't control their syntax).

Notice they don't use parentheses but a rather wide gap with the menu item text, and a smaller font size.
Also character  '+' seems reserved to separate modifier keys, while '-' is used for standard characters.
For example: **Print Book as...   Ctrl+Shift-P**

So I propose to stick to this syntax.

**Comment by hekkup** [comment]
@hbitteur ok, for consistency that format is alright.

**Comment by hbitteur** [comment]
Additional question: Should we use lowercase or uppercase characters in the shortcuts appearance within tool tip text?
For example, int the pull down menu, we have:
- Print Book...   Ctrl-P (mind uppercase 'P', rather than lowercase 'p')
- Print Book as ...   Ctrl+Shift-P (here again uppercase 'P')

Obviously P and Shift+P lead to two different menu items.

And in case you wonder, I just made the small test of modifying the related .properties file
(D:\soft\audiveris-github\development\src\main\org\audiveris\omr\sheet\ui\resources\BookActions.properties on my machine) where you can find among many other lines:

> printBook.Action.accelerator = control P

> printBookAs.Action.accelerator = control shift P

I have replaced the capital P by a plain p, and guess what, these shortcuts no longer work.

So, I suggest to use capitals in our tool tip text (such as "H-B") even if we expect the user to press 'h' then 'b'.
Please help me make the right decision for our users!

**Comment by hekkup** [comment]
I think capital letters would be better for consistency.

**Comment by hekkup** [comment]
I think using parentheses in tool tip would be alright even if they are used in the menu. The reason for this would be that the menu can use left-right alignment to make the menu item text and the shortcut to visually appear in different groups. In tool tip this grouping is not available as clearly. I checked Inkscape tool tips and there parentheses are used in tool tips but not in menu items.

**Comment by hbitteur** [comment]
OK, done with capitals and parentheses in commit e9df8e649b24cac24ad50b80ac9b836195759084 on development branch.
