### ISSUE TITLE
lyrics are sometimes ignored due to (wrongly) recognition of notation elements

### ISSUE THREAD

**Issue by Bacchushlg** [Audiveris/audiveris#343]
![Chili con Carne (2)](https://user-images.githubusercontent.com/33522630/71812382-57c52200-3077-11ea-9290-b6dd53a17e4d.jpg)

sometimes lyrics lines are completely ignored after some wrongly recognition of notation elements. In most cases these are (wrongly) dynamics texts, and in the example above the "i"-dots are recognized as staccatos - skipping all lyrics due to this...

**Comment by hbitteur** [comment]
First analysis of what is happening in this example:
- During the TEXTS step, text candidates are OCR'ed , good ones are kept and gathered as sentences. You can see full lines of lyrics in your example, almost all words are correctly recognized.
- Then at beginning of SYMBOLS step, the program gathers all remaining non-assigned glyphs in order to launch recognition (using the neural network) on each glyph.
Since small words can result from OCR mistakes and in fact be musical symbols, there is a test in the gathering of non-assigned glyphs: if the longest word in a sentence is shorter than a given value (today this value is 4 characters), then the whole sentence is considered as questionable. It is kept as a legitimate inter but all its glyphs (they correspond to short words) are also considered for symbol recognition, which may give birth to other legitimate inters competing with the original sentence "words".

In your specific case, you have long sentences, fine, but made only of very short words, typically 2 or 3 characters. Which is below the minimum threshold of 4.
Then we end up with new symbols, like (false) staccato dots which unfortunately exhibit a better grade than their competing sentences, which are then deleted!!!

In short, with current algorithm and threshold, the results are for example:
- "This is a **phrase**" is safe because the longest word in this sentence is "phrase" = 6 letters.
- "**foobar** %(" is safe because the longest word, "foobar" = 6 letters. Unfortunately the second word "%(" is certainly an OCR mistake but Audiveris cannot safely say so.
- "ba ra **chi** ki ba ra chi ki ba ra chi ki ba ra chi ki ba ra chi ki ba ra chi ki ba ra chi ki " is NOT safe because the longest word is "chi" = 3 letters (< 4).
This is your first lyrics line and, among others, the dot on the 'i' of the last word "ki" is mistaken for a staccato dot (grade 0.79) in conflict with lyric item "ki" (grade 0.67) and with lyrics line (grade 0.72). And of course, the highest grade wins, keeping the staccato dot and discarding the conflicting items...

For this specific score, you could temporarily lower the minimum threshold from 4 to say 2, by modifying the constant "minWordLength" in the Tools | Options menu. This would fix your case, but would open the door to false words of 2 or 3 letters. Anyway, it should work for this case.

Perhaps we could modify the algorithm by taking into account, not only the longest word in sentence, but also the total number of letters in the whole sentence. Here again, this would just be a heuristic, which might lead to mistakes in some other examples, as usual...

**Comment by Bacchushlg** [comment]
Ah, this explains a lot. So I try to reduce the limit to 3 as a first step.
Often there are also lines full of doo, do, do,... for the bass voice...

**Comment by hbitteur** [comment]
I just tried with minWordLength set to 2 for your example. This is OK for symbol recognition (no more false staccato dots).

But some lyrics disappear due to another problem in your last system which contains 5 lyrics lines. In lines 1, 3 and 4 there is a (false) slur (detected during the CURVES step) and here again with a grade (0.46/0.80) higher than lyrics grade (0.70).
![image](https://user-images.githubusercontent.com/22053634/72061520-5a718280-32d6-11ea-879e-08d38b25964f.png)

This is really silly to prefer a tiny slur candidate to a full line of lyrics. I'll investigate the interest of raising grade of a lyrics line based on its total number of letters.

**Comment by hbitteur** [comment]
Both problems are now fixed on "development" branch, commit 167e7618c89c6a17143000c4667149280b6e4af6

There is no more need to artificially lower constant minWordLength since total sentence length is now taken into account, thus protecting it from competitors like slurs or symbols.

**Comment by Bacchushlg** [comment]
Tested and confirmed: works as expected.
When you are just working in this region: the bottom lines of the 2nd a 3rd system are assigned mixed as lyrics and note line text... 
Can be manually repaired, but maybe...

**Comment by hbitteur** [comment]
Sorry, I overlooked these.

For the line between system 2 and system 3, almost every word has two interpretations, one as a lyric word WRT upper system and one as a text word (direction...) WRT lower system. 
This is definitively a bug!  In PAGE step, theoretically such cases should be addressed, and we should no longer see overlapping inters coming from two different systems. I need to investigate why this did not work as expected.

For the line below last system (3), the words around the center, abscissawise, of the page are inferred to be of Copyright role, while the words more distant are not and rather assigned to lyrics. This mixture could be better addressed. I need to think it over. For example, I think it would be safe to say that a copyright sentence cannot appear on the same line as a lyrics line.

OK, more work to do :-)

**Comment by hbitteur** [comment]
Done with commit 9b5cb49088196be5ef1ede41a08e33f322485d4e on development branch.

Also I discovered and fixed some awkwardness in text processing, the TEXTS step on this score is now a matter of 5 sec compared to 30 sec before.
Enjoy!

**Comment by Bacchushlg** [comment]
what a big progress! Also in analysis time!
I had often wondered, why text analysis needed so long sometimes.
