### ISSUE TITLE
Build failing with multiple compiler errors

### ISSUE THREAD

**Issue by Bastian-B** [Audiveris/audiveris#345]
Dear all,

I'm having trouble with installing Audiveris on a Mac OS Catalina system. The build wouldn't start at all due to an incompatibility of the gradle wrapper with the current Java version, but I figured out how to update the Gradle wrapper to a version that is compatible with my Java SE 12.0.1.

Unfortunately, the build is still not successful for reasons that escape my understanding of how Java and the compiling process work. I'm attaching a log files with the results of `./gradlew build`.

Please excuse my asking, I'm rather new to installing and using software from command line.
Thank you very much for your help
Sebastian

[error_log.txt](https://github.com/Audiveris/audiveris/files/4113428/error_log.txt)

**Comment by hbitteur** [comment]
According to your compilation errors, there are problems with Lombok and with javax.xml.bind package among others.

 We compile Audiveris with Java 11, not Java 12. Could you retry your build with Java 11 instead?

**Comment by Bastian-B** [comment]
Thank you for your answer. I tried with JDK 11.06, but the result is the same, except for the first to lines (the [options] warnings) that are now gone.

**Comment by hbitteur** [comment]
I'm thinking: which branch are you trying to build?
- By default, it's the "master" branch, which will require Java 8 (not 11 as I wrote too quickly)
- I use the "development" branch, which carries the latest modifications and is meant to be used by Java 11.

To select a branch different from default master, use a command like:
> git checkout development

Then:
> ./gradlew build

Apart from that, you may have specific rules for Mac environment. I cant' help you here, since I have no access to such environment. I think I remember you need to use Oracle OpenJDK. I'll ask Maxim to confirm.

**Comment by maximumspatium** [comment]
What does the terminal command `java -version` say?

**Comment by Bastian-B** [comment]
Thank you very much, @hbitteur , the development branch did the trick, Audiveris is now running on Java 11. (@maximumspatium : I had succesfully switched to 11 before.)
Thank you both for your efforts and your patience!
