### ISSUE TITLE
Current work signs

### ISSUE THREAD

**Issue by oleedd** [Audiveris/audiveris#347]
It would be fine to add a label or - better - green circle (online) to issues which are in work at the moment.

**Comment by hbitteur** [comment]
What would be the purpose of such green circle?
I'm personally working on coming 5.2 release.

This is an open-source project. Any concrete contribution is more than welcome. So, if you are especially interested by a given feature, feel free to take the action point and submit a PR.

**Comment by oleedd** [comment]
The purpose is to let users see what issues are active at the moment (to suggest or know something).
What do you mean by a PR? It is about to add some sign to an issue if you are starting to work on it.

**Comment by hbitteur** [comment]
Sorry, a PR means "Pull Request".

Any one can contribute by implementing a new piece of code or modifying existing code, or both.
Before his contribution is accepted and included in the project main stream, it must be reviewed and accepted by the project owners (we are 3 owners on Audiveris project).
A "pull request" is a kind of notification from the tentative contributor to the owners, requesting them to "pull" the contribution (so that they can build it, test it, review it and finally decide to reject or include it).

**Comment by oleedd** [comment]
I know what is a PR.
If you start to work on some issue - you add a sign (label, milestone or other) to it on github and others can see these active issues. It is not about a feature which needs coding.

**Comment by hbitteur** [comment]
Actually, most issues need to get hands on code or doc or other kind of material in the project.
My advice is to get your own hands on what you are interested in, rather than monitoring what others are doing.

**Comment by oleedd** [comment]
I don't know Java to fix something.
But sometimes devs do so - make list of current tasks and mark done tasks by a tick. It is effective. Users, which know Java, can see active issues and propose some solutions with code. Others can give ideas.

**Comment by oleedd** [comment]
What about a list of plans for near future (for example month)?
