### ISSUE TITLE
mergeSystem: Exception in mergeSystem

### ISSUE THREAD

**Issue by Bacchushlg** [Audiveris/audiveris#349]
![Caresse sur l'Ocean](https://user-images.githubusercontent.com/33522630/73552556-c021dc00-4448-11ea-98a8-3748d9482a59.jpg)

In this score the 1st system is not recognized as such (split to 2 systems). So I tried to merge the top system with the 2nd one. Unfortunately I get an error:
Exception in mergeSystem java.util.ConcurrentModificationException

And a blank screen afterwards...

Just another question: is there a possibilty to set the 6/4 rhythm so that the rhythm check works correctly?

**Comment by hbitteur** [comment]
Topic1: Sounds like a bug! I assigned it to me.

Topic2: 6/4 doesn't appear in shape board, then we will have to use a custom N/D signature. Unfortunately, this feature disappeared a couple of years ago, I don't remember why.

Easy fix: modify shape board to include 6/4.
More serious fix: implement support of custom time sig.

**Comment by Bacchushlg** [comment]
topic2: easy fix would be ok. It also helps for 12/8 (which is the same, arithmetically).

**Comment by hbitteur** [comment]
OK, 6/4 and 12/8 are now on board.
Commit 1b807c5fae5515ee26807a6f4574a5253a6515ff on development branch

**Comment by hbitteur** [comment]
Regarding the initial problem of systems cut in two portions, the root cause is the system vertical line on the left uses gray pixels.
During binarization, these pixels are discarded. SInce the rest of the image is a good black and white, we could use the basic binarization which is based on a global threshold (rather than an adaptive threshold which is now the default).

Well, I tried this and the result is even worse!
Because the left side of the image is rather blurred and the very first pixels on the left compose a kind of vertical barline (on the left of the brackets and the braces).
So, we end up with a giant single system...

OK, back to the manual merge.
It crashes.
But, when run in debug mode, it does not crash and works perfectly!
I'll try to sort this out.

**Comment by hbitteur** [comment]
Fixed in commit e58595984572ca48e78161d57f608e738f55db31 on development branch.

It happened only when processing a score directly from image input, not when processing from a saved .omr file. So in fact this was not related to debugging or not.

**Comment by Bacchushlg** [comment]
fixed with commit e585959
