### ISSUE TITLE
provide a universal time signature symbol

### ISSUE THREAD

**Issue by Bacchushlg** [Audiveris/audiveris#360]
sometimes I have scores with unusual time signatures.
Unfortunately that has 2 drawbacks:
- the rhythm check does not work (not nice mais faisable).
- the export is not correct.
The latter is sometimes really nasty, because the notation is shifted completely.

My idea is to provide something like a universal time signature: it can be drag-n-dropped to the score image and the configured to a universal signature with independent numerator and nominator (No need to display the selected values, that would only be nice-to-have...)

**Comment by MusicForStringsPercussionCeleste** [comment]
Baruch, how weird are the time signatures you speak of? Do they not have whole numbers for a numerator or denominator?

Given the complexity that might be added with a workaround, maybe a better route is to put limits on the possible time signatures that are allowed.

Surely 98% of all music can be served with time signatures of 4/4, ¾, 2/4, C and cut time, ⅜, 2/2, 12/8, 9/8, 6/8.

Best wishes,
RG

On Feb 22, 2020, at 6:49 AM, Baruch <notifications@github.com> wrote:

﻿

sometimes I have scores with unusual time signatures.
Unfortunately that has 2 drawbacks:

  *   the rhythm check does not work (not nice mais faisable).
  *   the export is not correct.
The latter is sometimes really nasty, because the notation is shifted completely.

My idea is to provide something like a universal time signature: it can be drag-n-dropped to the score image and the configured to a universal signature with independent numerator and nominator (No need to display the selected values, that would only be nice-to-have...)

**Comment by Bacchushlg** [comment]
Of course you are right for about 95% of scores.
Actually I had a score that started in 12/8 and then changed to 9/8. 
And I have a couple of scores from balkan music that use 7/8, 11/8, 13/8... 
My proposal aims to avoid the need for all these curious rhythms and simply provide a sort of configurable item that can be placed on the score. The rest should be simple mathematics... ;-))

**Comment by Bacchushlg** [comment]
Perfect solution with version 5.2.1-alpha. Any time signature can be added now, and what I tested is properly calculated through rhythm checking
