### ISSUE TITLE
idea for improving transcription of bad-quality score images

### ISSUE THREAD

**Issue by Bacchushlg** [Audiveris/audiveris#365]
I sometimes have rather bad quality score images - which I transcribe anyway but with a lot of after-work through the editor.
I have observed that the initial steps often detect many a the note heads and beams correctly, but during detection of the stems many of them are removed, and the step reduction then does the rest...
The reason in most cases are the bad stems which are no more a continuous line but just a couple of pixels along the original stem (see appended example, which is extremely bad...).

My idea would be to make the algorithm for detection of stems more tolerant against broken stem lines. Also the end-points of detected beams together with a note head below (or above) could be used as anchors for possible stems.
Maybe this behaviour could be made optional (flag in book or sheet parameters) - so the normal transcription is not disturbed, but in case of bad originals this would reduce the effort in the afterwork. 

![Viva la Vida (7)](https://user-images.githubusercontent.com/33522630/76165108-ac0e8000-6154-11ea-848f-2f2dcd13a376.jpg)

**Comment by MusicForStringsPercussionCeleste** [comment]
Baruch,
I think you might consider working with the scanner to make a better copy than expecting audiveris to guess about stems.  I fear trade-off costs, and always try not to change something that works in majority of use cases or works with good input.  It is reasonable to assume a clean PDF or scan, right?

in any event, thank you for the conversation so far.  Fantastic progress.

RG

________________________________

**Comment by Bacchushlg** [comment]
have a look at the openscore project (https://openscore.cc/project) working on the scores of the IMSLP library.
Most of these scores are of rather - lets say - weak quality. No way to get better scans - they are provided as scans - and I assume that the people doing the scan worked with maximum care.
In my case, I have a couple of scores that are bad copies of the original - and I have no way to better one's...

**Comment by MusicForStringsPercussionCeleste** [comment]
yes, the problem with these scan projects - but are the utilities we have for editing, sharpening, and improving scans better suited to cleaning up these music scores than Audiveris?

20 years ago I took a chance on myself... and won.

________________________________

**Comment by hbitteur** [comment]
I'm answering rather late to this issue which I saw when it was first posted. Today, I'm trying to clear the backlog, and I still have no definitive position on this topic.

Two important things to consider:

1.  Human brain is very powerful. Things that may look obvious for a human, may be far from obvious for the software. I know that a few pieces of AI software are now able to overcome humans, for tumor detection in medical images for example. Applied to music OMR, we had this experiment made by ZHAW university in 2018, and integrated in Audiveris [6.0 prototype](https://github.com/Audiveris/audiveris/wiki/6x-Presentation). To quickly summarize the experiment (read the details by yourself), we can say that the classic approach, based on lots of rules and code, performs better on good quality scores but fails miserably on poor quality scores, whereas the AI-based prototype perfoms worse of good quality but surprisingly rather well on poor quality. Perhaps because AI does not require a stem that really looks like a stem. On the other hand, AI is totally stupid in some cases: I remember a "4" lower part of time signature, and nothing found in the upper part.

2. There is no limit in "poor quality". In other words, when should we stop trying to recover from poor scores, poor poor scores, incredibly poor scores? Every progress we can make after weeks / months / years of trial and error to successfully process a few cases, may be totally useless on the next score, not to speak of possible collateral damages on scores that were correctly processed before. This is awfully frustrating.

There are 2 axes in Audiveris development: OMR engine and UI tools, both working on a solid data model. I'm OK with the SIG-based data model (typically the structure of the .omr project file). After an initial focus on OMR engine improvement, I'm now trying to fill the most important holes in UI tools and 5.2 release is not far away now.

This being said, I know that beams are generally well detected by the OMR engine. We could look more aggressively than today for stem and head connection in their neighborhood, especially on the beam left and right edges. Typically, should we aim at solving the case below - please think of the collateral damages, and answer yes or no :-)
![image](https://user-images.githubusercontent.com/22053634/81711227-b52d0d80-9473-11ea-80f8-bc4162c1dbaf.png)

**Comment by Bacchushlg** [comment]
ok, ok, I agree...
My proposal aimed at the direction to suppress **optionally** the removing of note heads and beams that have no stems during reduction step. This could make the manual rework easier.
In the example above I was very astonished that these elements were mostly detected properly, but then reduction came and removed all of them...

**Comment by hbitteur** [comment]
@Bacchushlg I told you already that the "real" test is the reduction step. Because this is where all informations retrieved so far with respect to beams, stems and heads are globally evaluated using contextual grades and compatibility tests.

What you could do on your own is to lower the minimum final contextual grade which is required for any symbol to survive. It is by default set to 0.5.
Open Tools | Options window and type Grades in the search field. This will take you to the Grade class where most of grade constants are managed.
Notice especially:
- minInterGrade (0.1)
- minContextualGrade (0.5)

Constant **minInterGrade**  allows an Inter candidate to be created from some glyph or other input. Below this value, the inter is not even created.

Constant **minContextualGrade** allows an Inter candidate to survive the REDUCTION step, provided it has not been excluded by another Inter candidate with a better contextual grade.
So, this is the constant you may want to play with.

But a head (except whole head) needs a stem, same thing for a beam, regardless of their grade. We could remove this constraint, but what should we do with stem-less heads or stem-less beams then?

For the heads, move until STEM step (just before REDUCTION step). All heads that need a stem and don't have one are displayed in red (abnormal status) whereas the stem-connected heads are displayed in dark green. At this point, you could manually insert the missing stem.

For the beams, the situation is similar: beams are displayed in red and turn dark green only at STEM step. And it's during the REDUCTION step that beams are checked for stems at both ends (one end only for beam hook).

So, in both cases, you have the opportunity at end of STEM step to visually check the abnormal situations and manually correct them before the REDUCTION step removes the involved inters.

**Comment by hbitteur** [comment]
I'm  thinking of a possible improvement to help you deal with your "recognized-but-killed-by-reduction" symbols. At least for those which are removed because of their too low contectual grade.

Still at the end of the STEM step, heads without connected stem are displayed in red as you know. But heads which have a stem but have a resulting contextual level below  0.5 (minContextualGrade) are displayed in dark green. We could use a different color (not red, but perhaps orange?) so that the end user can easily detect them. Then we could provide a way for the user to manually "force" the survival of some of these weak symbols that otherwise are meant to disappear at reduction step.
We need a way to designate one or several symbols and "force" them.

What do you think?

**Comment by Bacchushlg** [comment]
Oh yes, that sounds good. So the user can "verify" the weak detected symbols before reduction, hindering reduction to remove them.
I think this is a very good way to handle this problem - and also logical.
Color orange: yes might be a good choice.
For bad scan an option "accept all" might be useful, too. Bad scan need a couple of manual afterwork anyway...

What about also allowing to add e.g. stems at this point? So the reduction steps sees the stem (of a before floating head or beam) and can continue his "normal" work?

**Comment by hbitteur** [comment]
> What about also allowing to add e.g. stems at this point? So the reduction steps sees the stem (of a before floating head or beam) and can continue his "normal" work?

I think you can already do so: manually add stem between STEM step and REDUCTION step.

**Comment by Bacchushlg** [comment]
I had tried so, but with no success. And now I understand, why: die recognized elements had a score that was too low, so my added elements did not succeed.

**Comment by hbitteur** [comment]
Current Audiveris engine performs badly on poor-quality scores like the ones available on IMSLP site, 
I just spent a few days on "what if" prototyping and I think there are a few tracks available to improve the situation.

The REDUCTION step is the key step which plays with heads, stems and beams.
- **Heads** are rather well recognized especially when they are black. Void heads are more badly recognized by the current template matching technique. We may have a better technique some day but probably not in the very near future.
- **Stems** are correctly recognized when their pixels exist. That's the real problem, because in poor quality images, stems are the items that suffer the most. Probably because they are thin lines. Staff lines also are thin lines, but there is so much information redundancy for staff lines that the OMR engine can cope with severe "holes" in staff lines. But not with stems.
- **Beams** are very well recognized via their ad-hoc technique (you can study the code of BEAMS step if you wish). Reality is that, if we except the case of very short beams, almost all beams are correctly recognized (very few false negatives or false positives).

The user could select a "**poor**" mode for the OMR engine, telling explicitly that the input image is of poor quality and that the OMR should expect severe holes in stems. The risk is to come up with some false stems or with some stems longer that they should. At least the user could try both modes on the same input and choose the one that performs better on the input at hand.
This poor mode would also lower the constraints for a given inter to survive. Today its contextual grade must be at least of 0.5 (in the 0 - 1 range). At the end of the STEMS step (the one right before the daunting REDUCTION step), As already written in a previous message, we could display the weak items in a special color (orange for example) to call user attention on them. The use could dynamically lower the threshold (via a slider?) and observe the impact on these "weak" items.

Beside the poor mode, we could rely more heavily on beams.
Today, if a beam lacks a connected stem and head on one of its horizontal side, it is discarded by the REDUCTION step! We could keep it, while still displaying it in red because of its abnormal status.
Also, a (not too short) beam could be used as a kind of "**beam umbrella**" for all the note heads just above or just below, not just the ones located on beam sides. Here again, the engine may be too aggressive, but we can rely on the user to correct a few bad results if, on the other side, he can benefit from many good outputs.

Since many parts of the engine will be impacted, I will use a specific branch ("poor") to host the temporary modifications before we decide to accept or reject them.

**Comment by hbitteur** [comment]
Quick update on this score example, using latest Audiveris version (5.2.3)
I simply run until REDUCTION step, with no manual action.
And I got this, no that bad after all:
Beams are generally OK, some isolated heads with really poor stems will need manual fix.
Manually adding missing barlines is very easy (it operates on the whole system)

Even the tiny dirty snapshot is correctly handled:
| Input | Output |
| :---: | :---: |
|![](https://user-images.githubusercontent.com/22053634/81711227-b52d0d80-9473-11ea-80f8-bc4162c1dbaf.png)|![image](https://user-images.githubusercontent.com/22053634/128605913-7ac2dd9b-9b35-4df6-bf73-0805faa5dace.png)|


So, I consider that the new STEMS step algorithm is a significant progress... :-)

![image](https://user-images.githubusercontent.com/22053634/128605554-7d4c9af0-5dee-44f4-8d43-b0ffb6d17cc8.png)

Closing this issue now.

**Comment by Bacchushlg** [comment]
this is really a marvellous improvement!
