### ISSUE TITLE
missing key "none"

### ISSUE THREAD

**Issue by Bacchushlg** [Audiveris/audiveris#371]
In case that the key of a note line changes to "none", it is not possible to signify this. There is no "none" key available.
Should be added, e.g. as a simple natural symbol.

**Comment by hbitteur** [comment]
Do you mean that the user should be able to remove the key signature of a stave? If so, what is the problem: simply select the key signature and remove it.
Could you clarify?

**Comment by Bacchushlg** [comment]
No, the problem appears in such a case:

![image](https://user-images.githubusercontent.com/33522630/81164231-53ab0180-8f90-11ea-94bb-859af43fa6aa.png)

The key changes to "no" within a note line. And there is no way to assign to "no", only to a couple of # or b.

**Comment by hbitteur** [comment]
Oh yes now I see what you mean.
And indeed, natural signs are still not handled in any key signature. This had no important impact, because they are often used in the very last portion of a staff, just to notify the reader that next staff will have a different key.

But in the case at hand, the key signature is supposed to "disappear" completely. The engine should not ignore this cancellation or, at least, the end user should have the ability to manually enter this information.
This means the ability to enter a key sig filled only with naturals. Since Audiveris knows which key sig (and clef) is active right before this location, it could directly propose the right combination of naturals to the user.
This would be more convenient that asking the user to build up the key from individual natural signs.

What would you like?

**Comment by hbitteur** [comment]
How do you do this this MuseScore?

**Comment by Bacchushlg** [comment]
![image](https://user-images.githubusercontent.com/33522630/81166423-ec8f4c00-8f93-11ea-813b-c3b5d07a5239.png)

MuseScore can add a "no-key" from the palette (bottom right)

**Comment by Bacchushlg** [comment]
About how to insert: from my point of view it is not really necessary to build up the correct number of natural accidentials. You could provide a special symbol, e.g. a crossed-through b or #. That would do it and might be easier to handle (?).
In case of automatic detection the insertion of the proper number of naturals is a good solution.

**Comment by hbitteur** [comment]
In the shape palette, on keys panel, we could add a button with no sign in it, rather similar to MuseScore except that today we don't show the lines in these buttons (something we could do by the way).
And if the user selects this "void shape", he gets the right combination of natural signs at the location where he drops the shape.

The only problem left is which "shape" should be shown while being dragged? (because there is none). Perhaps this is one more reason for displaying the staff lines as shape decoration.

**Comment by hbitteur** [comment]
This is now available in development branch, commit eb4236d03cc5e050ce83253b80614761d9537d14

See in shape board the palette dedicated to key signatures. In the middle, it contains a new icon with just a natural sign:

![image](https://user-images.githubusercontent.com/22053634/81287907-e36db000-9063-11ea-9b38-872cc342348e.png)

Simply drag and drop this icon to where the "none" key signature is to be inserted. It is drawn as a sequence of natural signs, according to the current clef kind and the current key signature. This is why I named it KEY_CANCEL rather than "none".

You willl notice that staff snapping is active:  once in a staff, the icon color turns from gray to light green, and the icon precise shape is determined according to the previous key signature and clef kind  before the current location. 

The icon can move only horizontally in the current staff, but you can move to another staff.
In staff with no prior key signature, you will notice that the icon remains gray and that you cannot drop it.

**Comment by Bacchushlg** [comment]
Perfect solution! Works better than expected ;-))
