### ISSUE TITLE
Almost perfect transcription gives export with wrong system assignment

### ISSUE THREAD

**Issue by Bacchushlg** [Audiveris/audiveris#377]
This score was transcribed almost perfectly. But the export file gives a completely wrong system assignment

[Cole Porter-My heart belongs to daddy-SheetsDaily.zip](https://github.com/Audiveris/audiveris/files/4511542/Cole.Porter-My.heart.belongs.to.daddy-SheetsDaily.zip)

Version: 861999d7

**Comment by hbitteur** [comment]
I found a couple of bugs in the exporting code, easy to fix.

But the main problem is the fact that the images of two sheets (number 2 and 4) are truncated on their left side, making the detection of braces impossible, resulting in broken parts.

With current version, you can manually insert braces but this does not fix the building of parts. This is a missing feature to be addressed ASAP.

More on this later.

**Comment by hbitteur** [comment]
I noticed also that staves have a too narrow margin on their left side. Beside impeding brace recognition, this has an impact on staff line recognition as well.

**Comment by hbitteur** [comment]
OK, this is now fixed, see development commit ca3bf80f3db3600727a8f128d73ff79a83b4a2a3 which fully implements the manual addition/removal of braces with their impact in terms of Part/Staff configuration.
Please check on your side.

**Comment by Bacchushlg** [comment]
I just tried with the example score, but with no luck:
the critical page is page 2. 

there was a missing brace in the first system. When I insert it, I get an error in the logging window:

> Merging {Part#2 staves[2]} with below {Part#8 staves[3]}
> Exception in addInter java.lang.NullPointerException

And exporting this page still leads to a score with 8 note lines.

**Comment by hbitteur** [comment]
Waoh! This was a pretty difficult fix. Done in commit 71b9aaaabb5a696882b55399b3ac1ae11293ddc0.
To "repair" your example, which is broken on sheets 2 and 4, do the following:
- [pull the updated software]
- load the .omr
- on sheet 2, manually remove all braces, then drag n' drop new ones
- on sheet 4, same actions
- you can then export as musicxml
- save the modified .omr file

Et voilà !

NOTA: In case you wonder, you could as well remove a brace and then undo the removal (CTRL-Z) for each and every brace. This would work for every brace, except the last brace on sheet 4, which is incorrectly related to staff 12 instead of 11. The undo would thus throw an exception.
This is because your .omr is right now in some illegal status. On a "legal" .omr the undo or the manual re-insertion would both work and produce identical results.

**Comment by Bacchushlg** [comment]
Bingo! Works fine.
