### ISSUE TITLE
First steps using Audiveris

### ISSUE THREAD

**Issue by rodolfo-medina** [Audiveris/audiveris#379]
[test.zip](https://github.com/Audiveris/audiveris/files/4535189/test.zip)
Hi.

I'm new to Audiveris and it seems to me that I don't manage to do even the
basic things.  In the attached example, the first measure seems all right, but
I don't manage to repair the beams in the second and third measure, both in the
left hand: second beam of the second measure and first beam in the third
measure.  Can anybody please help me?

thanks in advance,

rodolfo

**Comment by hbitteur** [comment]
@rodolfo-medina 
Your score is of rather poor print quality, many lines are broken, making the work of the OMR engine rather difficult. You need to perform a few manual corrections.

These corrections are now easy in the "development" branch (the coming 5.2 release) but were still very limited in the official 5.1 release.
Which version was used in your case? I suppose it was the 5.1.

Simply pull the development branch and build it. You will gain all the new features including these UI actions that you need to correct this score.

Documentation for these new features is still to be written, this should be done in the coming weeks. But there is nothing very complex, many features are based on drag and drop from the shape board, and/or double click on an item to then pull its handles.

By the way, your example is short and requires typical adjustments. Would you mind if I use it as an illustration in the coming documentation on these UI corrections?

**Comment by rodolfo-medina** [comment]
thanks...  of course I wouldn't mind at all...  please use it as you like...  I pulled down Audiveris again and re-builded it freshly with:

  $ git clone https://github.com/Audiveris/audiveris.git

, and the version now is: 5.1.0:68a18bb6d.  Is it the development branch you mean...?  If so, I'll be trying my exercize again and will let you know if I'm successful...

thanks again,

rodolfo

**Comment by rodolfo-medina** [comment]
I pulled and builded the development branch and now I have the 5.2 version...  but just the same I don't manage to repair those beams I pointed out:: left hand, second beam of the second measure and first beam in the third measure...  does anybody manage...?

thanks,

rodolfo

**Comment by hbitteur** [comment]
The new features are available in development branch, but the documentation is still to be written. This is currently my main task together with the clearing of issues backlog.

So, let me explain how you can correct the OMR output in your two precise beam cases.

First case (measure 2, staff 2):
![image](https://user-images.githubusercontent.com/22053634/81920790-f808f580-95d9-11ea-8b48-bf291acfc27b.png)
The beam in red is something you have inserted manually, certainly by drag n' drop, but in 5.1 you could not modify the symbol one dropped. In 5.2 alpha, you could reshape it, but in this precise case, there is something better to do.
1. First, remove this manual (half) beam on the left. You do this by selecting the symbol and pressing the delete key, for example.
2. Then select the other (half) beam on the right by a double-click in order to open it for edition. Depending where you precisely double-click, you may select a (wrong) slur hidden just behind the beam, if so, simply remove it as well.
3. The right half beam, when selected for edition, display 3 handles, one in the middle, one on left and one on right. Select the ledt handle, and drag it to the left so that this half beam now becomes a full correct beam. Release it by clicking somewhere else. You now should have something like:
![image](https://user-images.githubusercontent.com/22053634/81922159-00fac680-95dc-11ea-8dde-66578096fa9a.png)
4. Now, there is one missing symbol: a stem from this beam to the note head below. If you click on the stem pixel, you can see a vertical glyph underneath, not the full stem because of missing pixels, but not too bad either. With this glyph selected, open the shape palette ofr the last family (Physicals) where there is a stem button. Use a double-click on this stem button to assign the stem shape to your selected glyph. You'll be prompted to choose between staff above or below, select below.
5. Use double-click of this new stem to open it for edition, since it is too short. Here again , you'll get 3 handles, drag the bottom handled down to the note head.
6. Deselect the stem and drag it to the beam to esatblish a connection between them.
7. Drag from the stem to the note head to establish connection with the note head.

Et voilà :
![image](https://user-images.githubusercontent.com/22053634/81922973-3a800180-95dd-11ea-8759-f83d124aab93.png)

Second case (measure 3, staff 2), I'll leave it to you as an exercise. Just tell me if you succeed... :-) You should!

**Comment by rodolfo-medina** [comment]
Thanks indeed...  I'm testing and try to learn.  I'm attaching the whole score from which I extracted the above example.  On this whole score I did on the same three measures the same operations as on the example but nevertheless the resulting xml is very poor and broken.  So I wonder if it's possible to export just a small chunk, say the first three measures, in order to concentrate one's efforts and immediately check their result....

thanks again,

cheers

rodolfo
[jensen-studio8.zip](https://github.com/Audiveris/audiveris/files/4648561/jensen-studio8.zip)

**Comment by hbitteur** [comment]
You are not obliged to export the whole book, you can work sheet by sheet and export just the sheet at hand.
My advice would be to select a sheet and in step menu, select the last step (PAGE). Then perform all needed manual corrections, paying attention to the background color of every measure: a pink background indicates a measure with abnormal rhythm, often due to symbols wrongly recognized. So, work measure by measure, until every measure is correct.
You can also, using a right click in a measure, print the voices in this measure, This helps detect rhythm problems.

But, don't expect miracles from a very poor quality score...

**Comment by rodolfo-medina** [comment]
In the example I attached, the background colours of all measures appear white to me...

**Comment by rodolfo-medina** [comment]
I'm doing further tests...  I'm attaching two PDF scores.  It's the same score, but with respectively the first 8 or 9 measures.  With 8 measures everything is perfect: Audiveris sees and exports it regularly without problems.  With 9 measures, instead (i.e. just adding one more measure), the resulting xml file is corrupted...  In both cases, everything seems to be ok: no red parts, all green.  Why does this happen?

Thanks for any help

Rodolfo
[test-8bars.pdf](https://github.com/Audiveris/audiveris/files/4655231/test-8bars.pdf)
[test-9bars.pdf](https://github.com/Audiveris/audiveris/files/4655232/test-9bars.pdf)

**Comment by hbitteur** [comment]
I took each of your 2 examples, ran through PAGE step, did no manual correction at all, and then called Musescore plugin on the MusicXML output.
Here are the two MuseScore windows:
![image](https://user-images.githubusercontent.com/22053634/82470800-15502f00-9ac6-11ea-8c09-f9dff4dc1800.png)
and
![image](https://user-images.githubusercontent.com/22053634/82470871-3153d080-9ac6-11ea-8fb0-b0906954499b.png)
There are a few mistakes, that would be easy to fix on Audiveris side, but there is no "corrupted output" to my knowledge.

**Comment by rodolfo-medina** [comment]
When importing the resulting .mxl output into MuseScore, all I get is a blank, completely blank sheet, and the message that it's "not a valid MusicXML file"...  What could it be...?  How to work it out...?

thanks,

rodolfo

**Comment by rodolfo-medina** [comment]
Indeed, within Audiveris, bottom left, I can read the following:

[test-9bars] Error in performing [SCALE, GRID, HEADERS, STEM_SEEDS, BEAMS, LEDGERS, HEADS, STEMS, REDUCTION, CUE_BEAMS, TEXTS, MEASURES, CHORDS, CURVES, SYMBOLS, LINKS, RHYTHMS, PAGE] java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.lang.NullPointerException

please help...

rodolfo

**Comment by rodolfo-medina** [comment]
The problem seems to be solved if I run Audiveris with:

 $ git checkout java11
 $ TESSDATA_PREFIX=/home/rodolfo/Downloads/tesseract/tesseract/tessdata/ ./gradlew run

I'm doing more tests...

Rodolfo

**Comment by hbitteur** [comment]
I'm afraid you are mixing several things here.
I suppose you have cloned and built the development branch of Audiveris, please tell me if I'm wrong.

"java11" branch has already been merged with "development" branch, don't use it or you will be several commits behind development branch. We should totally remove java11 branch now, to prevent this.

Could you make sure that you use:
- correct Java (11) 
- correct Tesseract (3.04) trained data pointed by TESSDATA_PREFIX

**Comment by rodolfo-medina** [comment]
I cloned Audiveris with:

 $ git clone https://github.com/Audiveris/audiveris.git

and am running it with:

 $ ./gradlew run

Now everything seems all right...  maybe because this morning I did:

 $ git pull --all

Before that last command, there were those problems I described
above: MusicXML output was corrupted; now it's ok.  Previously,
before cloning Audiveris, I had installed Tesseract with the
following commands:

 $ git clone https://github.com/tesseract-ocr/tesseract.git
 $ cd tesseract
 $ git checkout 3.04
 $ ./configure
 $ make
 # make install
 # make training

What do you think...?

thanks

rodolfo

**Comment by hbitteur** [comment]
To be precise, you do not need to "install" tesseract software, strictly speaking.
The reason is Audiveris directly calls a tesseract library (a .dll on Window, not the .exe).

But, regardless of the way tesseract software is used (via .exe or via .dll), it does need some data (the trained models, those pointed by the TESSDATA_PREFIX environment variable).
And installing tesseract as you did is one way to put some of the trained models in proper location. 

But you could have manually put them on your own, and this is what you would do to install support for additional languages.

**Comment by rodolfo-medina** [comment]
Please have a look at page 2 of this other attached example.  Why do measures 6, 7 and 8 have a red background?  What's wrong with them?  What elements need being repaired?  All stems and beams seem to be all right so I wouldn't know where to work upon with Audiveris...

thanks indeed

rodolfo

[verdi-caro_nome.zip](https://github.com/Audiveris/audiveris/files/4662819/verdi-caro_nome.zip)

**Comment by rodolfo-medina** [comment]
...it's probably the bug #326 ...
