### ISSUE TITLE
PATH/build/scripts/Audiveris generates incorrect classpaths on Linux

### ISSUE THREAD

**Issue by bobdrad** [Audiveris/audiveris#38]
I built audiveris (gradle build) in a directory ~/apps/audiveris.
If I cd into that directory and run "gradle run", it starts fine.
But if instead I run ~/apps/audiveris/build/scripts/Audiveris, I get:

Error: Could not find or load main class Audiveris

I noticed that the classpath expects a 'lib' directory under builds, which does not exist. I tried making a symlink from 'lib' to 'jar', but then I got a different error:

Exception in thread "main" java.lang.NoClassDefFoundError: org/kohsuke/args4j/CmdLineException
	at Audiveris.main(Audiveris.java:49)
Caused by: java.lang.ClassNotFoundException: org.kohsuke.args4j.CmdLineException
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 1 more

So something is wrong with the way the shell script is launching audiveris on Linux, but I am not sure what... For now, I'll create my own script that does a cd into ~/apps/audiveris, and then does "gradle run", but the script should be fixed since it's documented as an alternative way to launch the app.

Thanks!

**Comment by maximumspatium** [comment]
The start script in audiveris/build/scripts/ isn't intended to be run directly. It will be placed there by Gradle during the build process.
In order to obtain a working Audiveris distribution, please proceed as follows:
```
gradle clean build
cd build/distributions
```
You'll find two files there: `Audiveris.zip` and `Audiveris.tar`. Both are working distributions.
Below the sequence of terminal commands to launch the ZIP distribution:
```
cd build/distributions
unzip Audiveris.zip
cd ./Audiveris/bin
./Audiveris
```
The last command will launch the app. You can append CLI arguments, too.

Please tell me how it goes.
