### ISSUE TITLE
How to pull development branch?

### ISSUE THREAD

**Issue by rodolfo-medina** [Audiveris/audiveris#385]
Hi.

I pulled Audiveris, from my Debian Linux system, simply with:

 $ git clone https://github.com/Audiveris/audiveris.git

How to pull the development branch instead...?

Thanks for any help,

Rodolfo

**Comment by hbitteur** [comment]
You did!
> cd audiveris
> git status

Git should tell you that you are on master branch.
Simply do:
> git checkout development

and then

> ./gradlew clean build

To make sure you have everything up-to-date in your copy (in case you cloned some time ago), before checking out a specific branch you can always use:
> git pull --all

You should be OK now.

**Comment by rodolfo-medina** [comment]
Thanks...  but "./gradlew clean build" gives error:

$ ./gradlew clean build

> Configure project :
targetOS=linux-x86

> Task :compileJava
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

> Task :compileTestJava
Note: /home/rodolfo/Downloads/audiveris-new/audiveris/src/test/org/audiveris/omr/moment/MomentsExtractorTest.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

> Task :test FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':test'.
> failed to read class file /home/rodolfo/Downloads/audiveris-new/audiveris/build/classes/java/test/org/audiveris/omr/jaxb/table/Table.class

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 5m 35s
11 actionable tasks: 11 executed

please help...

rodolfo

**Comment by hbitteur** [comment]
I develop from Netbeans IDE, which when asked to clean and build, runs a gradle command behind the scene: 
> ./gradlew --configure-on-demand -x check clean build

"-x check" excludes the check task, which depends on test task.

I'm afraid there is an old test that is no longer relevant and which has remained undetected until you tried to run it.
More on this later.

**Comment by hbitteur** [comment]
There seems to be an issue for tests between Gradle 4 and Java 11.
I have to investigate further.
For the time being, you could run gradle with -x check, since these tests are not needed.

**Comment by rodolfo-medina** [comment]
thanks, that worked...

**Comment by vidalsantos** [comment]
Hi , 
I am also trying to build it
Seems that the page trained model is not available at the moment. Could you please repost it?

Thanks,

**Comment by leo6104** [comment]
@hbitteur When i upgrade gradlew version to 5.6.4, it fixes. 
I just change `gradle-wrapper.properties` distributionUrl to 
```
distributionUrl=https\://services.gradle.org/distributions/gradle-5.6.4-bin.zip
```

**Comment by hbitteur** [comment]
Thank you @leo6104 
I will update Audiveris accordingly.

**Comment by hbitteur** [comment]
Done in commit fcabcbdbd71c68ee7ebb7316bf65b201705f3c00
Closing the issue

**Comment by weidi** [comment]
> Hi.
> 
> I pulled Audiveris, from my Debian Linux system, simply with:
> 
> $ git clone https://github.com/Audiveris/audiveris.git
> 
> How to pull the development branch instead...?
> 
> Thanks for any help,
> 
> Rodolfo

You may also just run 
`git clone --branch development https://github.com/Audiveris/audiveris.git`

**Comment by hbitteur** [comment]
Or you can use:
``` bash
# Clone Audiveris repository on your local machine
git clone https://github.com/Audiveris/audiveris.git

# Pull everything (especially if your local clone is a bit old)
git pull --all

# Switch to "development" branch
git checkout development

# Build from scratch
./gradlew clean build
```

**Comment by rodolfo-medina** [comment]
Is it also necessary to do:

  $ git clone https://github.com/tesseract-ocr/tesseract.git

and

  $ tar xzvf leptonica-1.78.0.tar.gz

and install them?

**Comment by hbitteur** [comment]
@rodolfo-medina 
Thank you for pointing this out.
And I don't have yet a clear answer for this. Let me explain.

Audiveris does not need that Tesseract binary program (and its dependent library Leptonica) be installed. Because they are not used.
Instead, Audiveris uses a javacpp "bridge" which calls proper tesseract and leptonica binaries embedded in jar files that are automatically downloaded and packaged when building Audiveris. In fact, after building Audiveris, you can have a look at build/distributions/Audiveris.zip, which contains a top folder Audiveris and 2 sub-folders: "bin" for scripts and "lib" for all dependent jars. It's in this lib folder that you can see all the tesseract and leptonica binary jars, among many others.

So, that's for binaries.
But not for language data files.
I don't remember if Tesseract comes with pre-package English language as default or if it needs language data file even for English.
Anyway, if you plan to OCR other language than English (typically Italian, German, French), then you'll have to make sure that the corresponding data files are available on your machine. 
See the article on Tesseract OCR in [https://bacchushlg.gitbooks.io/audiveris-5-1/content/install/binaries.html](https://bacchushlg.gitbooks.io/audiveris-5-1/content/install/binaries.html)
