### ISSUE TITLE
Tremolo

### ISSUE THREAD

**Issue by rodolfo-medina** [Audiveris/audiveris#390]
Hi...

Audiveris displays correctly the tremolo notation but then it is misunderstood in the xml output when opened up in Musescore.  Is it a feature still to be implemented...?

thanks

rodolfo

**Comment by Bacchushlg** [comment]
see my last comment on #388

**Comment by hbitteur** [comment]
Tremolos are implemented since commit f2ca67f34d53a8e5620438c17ab76681add3b8e2

This concerns tremolos of "single type", that is a series of several slanted "lines" on a **single** stem.
![image](https://user-images.githubusercontent.com/22053634/210965188-ce6e6ca1-9303-4349-8495-0c58b4d14566.png)

Support for "double type", that is tremolos located **between** chords, remains to be done.

**Comment by hbitteur** [comment]
Audiveris 5.3 was just released with tremolo support.
So, I'm closing the issue.
