### ISSUE TITLE
guitar chord fingering symbols are sometime recognised as notation lines

### ISSUE THREAD

**Issue by Bacchushlg** [Audiveris/audiveris#396]
[Believe me if all those endearing young charms.zip](https://github.com/Audiveris/audiveris/files/4776001/Believe.me.if.all.those.endearing.young.charms.zip)

In some cased the guitar chord fingering symbols are recognised as notation lines, leading to some addtional notes in the score. The appended file is a good example for this.

Maybe a good idea is to "recognise" the tab symbols (just the grid) in order to hinder the transcription to find notes there.

**Comment by hbitteur** [comment]
Did you check the tablature support (in Book parameters)? 
If so, the OMR engine should simply detect the tablatures areas and avoid any recognition in these areas.

**Comment by Bacchushlg** [comment]
No, I didn't.
I did now - no change...
I understood that tablature support is meant for tablature notation lines... I this case we have chord fingering symbols for guitar.

**Comment by hbitteur** [comment]
Oops, my mistake!
I should have opened the .zip archive. Instead I had picked up the "tab" word and answered too quickly on tablature staves (a feature just recently added).

![image](https://user-images.githubusercontent.com/22053634/84627808-d86e3100-aee7-11ea-9c3e-53b98f7f232a.png)

Chord "frame" is the word used by MusicXML. See  [frame definition](http://usermanuals.musicxml.com/MusicXML/MusicXML.htm#EL-MusicXML-frame.htm%3FTocPath%3DMusicXML%2520Reference%7CScore%2520Schema%2520(XSD)%7CElements%7Cdirection%7C_____26).
Current Audiveris situation is that these chord frames, located between chord symbols (AKA chord names) and staff, are not recognized or handled at all.

And right now, I have no clue on how the engine could detect them.
Any idea?

**Comment by Bacchushlg** [comment]
Well, my idea would be to train some examples of these chord frames without dots (just the grid) - in the hope that these trained symbols are recognized with an acceptable reliability when found above the notation lines.
And then handled as clutter elements.

**Comment by hbitteur** [comment]
I think Audiveris will never be able to correctly process such chord diagrams, at least not in a foreseeable future. Because this would mean recognizing all the tiny segments for guitar strings and frets, as well as the finger locations.

What we could expect, however, is that some day the OMR engine will be able to detect such chord diagrams in the input image, and simply "erase" them logically, so that they don't get in the way of standard processing.

In the short term, we could think of a way for the end-user to manually define these diagrams areas as "blacklisted regions".
See #439 which is a kind of duplicate, so I'm closing this one
