### ISSUE TITLE
Triplets not detected

### ISSUE THREAD

**Issue by Sunny090628** [Audiveris/audiveris#402]
Triplets in this score are not detected.
[IMSLP02821-Debussy-L066.pdf](https://github.com/Audiveris/audiveris/files/4828683/IMSLP02821-Debussy-L066.pdf)
Windows 10 Audiveris 5.1 x64

**Comment by hbitteur** [comment]
Triplet recognition, as any other symbol, does not always work.
In your specific case, there is even no visible triplet symbol. Hence, you need support for **implicit** triplets.
This feature is available in the development branch only, and you have to explicitly activate the feature (in the book parameters dialog).

You can try this, and tell us what the result is on your example.

Please keep in mind that handling time slots and voices is one of the trickiest parts of OMR engine, and imposing support for potential implicit triplets does not help at all...

**Comment by rodolfo-medina** [comment]
I seem to have a similar problem.  In the attached score triplets are declared just in the first measure and remain implicit everywhere else.  I tried to add them by hand and it worked for the first page, but now on the second page transcription fails and I don't manage to add triplets by hand.  I tried to activate support for implicit triplets as hbitteur suggests but didn't manage to although I installed the development branch.

[bellini.zip](https://github.com/Audiveris/audiveris/files/4840171/bellini.zip)

**Comment by hbitteur** [comment]
@Sunny090628 Your IMSLP image is really too poor to waste time on it.
@rodolfo-medina I tried your Bellini example with rather easy success. Here is what I did:

1. Reloaded your .omr file into Audiveris
2. Used menu Book | Set Book Parameters to check for implicit tuplets option. It was not set. So, I set it for the whole book, using not the first tab (default for application) but the second tab (bellini-ah_non_credea_mirarti for current book). Pressed OK.
3. Selected sheet number 2. I discovered it was stuck on step MEASURES. I could not run the CHORDS step because of many inconsistent data: for example, first stem (2369) in staff 2 was linked to 6 different chords, all identical...!
4. So, I simply restarted sheet transcription from scratch, by selecting menu Step | REDUCTION, in order to stop at end of REDUCTION step. It's generally a good idea to stop there and have a look at remaining heads.
5. There was only one beam mistaken for a head: 
![image](https://user-images.githubusercontent.com/22053634/86819704-50172200-c088-11ea-86c7-728c4f05fe72.png)
Easy to fix: de-assigned the faulty head, selected the underlying beam glyph and, via the shape board, assigned this glyph the beam shape.
6. Then I completed sheet transcription by selecting menu Step | PAGE.
7. It's rather correct, just 3 measures (1, 6 and 9) exhibit a rhythm problem. Many measures show implicit tuplets, as expected.
8. Measure 1: 
![image](https://user-images.githubusercontent.com/22053634/86820891-f7e11f80-c089-11ea-982f-29216cff3a02.png) Two double flags were not recognized, selected underlying glyph and assigned double-flag shape. Measure turned from pink to white.
9. Measure 6:
![image](https://user-images.githubusercontent.com/22053634/86821106-42fb3280-c08a-11ea-921e-096041c51598.png) An implicit tuplet-6 had been detected at end of measure but no tuplet-3 at beginning of measure. Inserted a manual tuplet-3 just above the triplet composed on one 8th rest and two 8th notes. An implicit tuplet-3 got automatically inserted for the following triplet, measure was then OK.
10. Measure 9:
![image](https://user-images.githubusercontent.com/22053634/86821611-e8aea180-c08a-11ea-84dd-2b0c1b4e8db4.png) Here again, two double-flags were not recognized. Assigned them manually.

Et voilà !

**Comment by rodolfo-medina** [comment]
thanks, hbitteur...!  I've learned now this important trick: when PAGE step won't be completed, all I have to do is simply perform REDUCTION and then PAGE again...  et voilà, PAGE is completed...  I couldn't imagine...

As for support for implicit tuplets, I'm afraid it does not work in my Audiveris station: I activated such support as you said, but I have to add by hand *all* occurrences of triplets, none of them is automatically recognized.  And I don't understand when you say that first stem (2369) in staff 2 is linked to 6 different chords, all identical.  Apart from that, as I said, now I can work on sheet 2 the normal way and correct all the rythm problems: but I have to do so by hand.

I hope you'll also have time to have a look at issue 399 "Black note heads without stems"...

thanks

**Comment by hbitteur** [comment]
@rodolfo-medina No, there is no "trick" here. I just noticed many chords defined with the same note head and same stem, and I don't know where they came from. Some data was flagged as MANUAL (I think I remember it was the relationship between this stem and this head). So I simply decided to restart from scratch for this sheet.

And I also confirm that, with my Audiveris version which is the latest committed in development branch, almost all implicit tuplets were detected on this sheet number 2. IIRC, there was just one tuplet-3 missing in the whole sheet, so I simply inserted it manually. But just one.

I'm also studying what @Sunny090628 uploaded (an IMSLP score). I'm investigating if and how we could improve beam recognition and then beam-related notes. SInce beams are rather well recognized, we could be more aggressive on each side of a beam when looking for a black head, even with almost no stem pixels.

**Comment by rodolfo-medina** [comment]
Strange...  Why does implicit tuplets support not work in my case?  I enabled it as you suggest, and, when I do `git status', I get:

On branch development
Your branch is up to date with 'origin/development'.

nothing to commit, working tree clean

**Comment by hbitteur** [comment]
Could you post the image of book parameters dialog where support for implicit tuplets is set or not.

**Comment by rodolfo-medina** [comment]
Here it is...
![screenshot 2020-07-13 18:29:13](https://user-images.githubusercontent.com/64352612/87339959-f35bb180-c536-11ea-9fbf-dc7ab3d58e36.png)

**Comment by hbitteur** [comment]
OK, this is what I suspected: You have not activated the option!
Let me explain how this dialog works (it is documented in Audiveris handbook. See [this section](https://bacchushlg.gitbooks.io/audiveris-5-1/content/main/score_parameters.html) written for 5.1)

This dialog is meant to handle options that are _scope-dependent_. The scope can be:
1. **Default**: for all books from now on
2. **Book**: for all sheets of the current book
3. **Sheet#n**: for sheet number n in current book

Understand that certain options (and implicit tuplets option is one of them) can be set for some books (or even some sheets within some books), but not for all of them.
So you have the choice to define the option at the scope you desire: default, book or sheet.

If an option is not explicitly chosen for a given scope, it inherits the value from the scope above. For example, you can set the implicit tuplets option for a certain book of IMSLP as you did, it will apply to all sheets in this book and only for this book, except for the sheets if any where you set a specific value.

In this dialog, you choose the scope by selecting the tab on top.
Then you decide on the value, via the 2 checkboxes available for each option:
Checkbox on the left, when checked, tells the software that you are setting the value for this scope, regardless of what may have been inherited from the scopes above. And you explicitly enable or disable the option by checking or unchecking the checkbox on the right.
If the left checkbox is not checked, you discard any local value, you simply inherit the value from upper scope, and the line is displayed in gray (and you cannot modify the checkbox on the right).

According to the dialog image, you have selected the score tab (bellini ...), and thus chosen to define the option for the score. And the chosen option is "disabled" (the right box is unchecked). To set it to "enabled", simply check the checkbox on the right.

**Comment by rodolfo-medina** [comment]
thanks indeed...  it works fine now.
