### ISSUE TITLE
The location, where file is saved is not right

### ISSUE THREAD

**Issue by NelDav** [Audiveris/audiveris#405]
While saving files, if the location, where the file should be saved changes, the file is not saved to the selected directory.
It is saved to the directory above with the directoryname as filename. A little example:

I want to save to D:\scores\myscore\score.mxml, so I navigate to this directory with the save file dialog.
When I press save the file is saved in D:\scores\myscore.mxml

(Because the filename is not seperated from the file path)

**Comment by hbitteur** [comment]
@NelDav 
I agree with you. Where output files should be stored is a question that still needs clarification and improvement.
Release 5.2 is just around the corner, so it's the right time to review this feature before the new release is out.

Here is the current implementation (with all its drawbacks):
There are several relevant application constants in BookManager class (you can easily access and modify them, via the Options menu):

- **baseFolder** is the default base for output folders. It can be overridden by the "-output baseFolder" option on the command line interface.
- **useSeparateBookFolders** is a boolean (default value is true). It tells whether outputs for a given input file should be gathered in a separate folder. For example, the output files for a foo.png input should be stored into baseFolder/foo/ and the output files for a bar.jpg input should be stored baseFolder/bar/.
If this boolean is false, there is no separate folder, so all the output files for foo.png input and for bar.jpg input should be stored directly into the same folder "baseFolder/".
- **useInputBookFolder** is a (new) boolean (default value is false) which tells to store outputs as siblings of their input files. If set to true, this option bypasses the notion of baseFolder and of separate folders.

**Comment by NelDav** [comment]
Hi @hbitteur,

i am not sure, what the baseFolder is needed for. On Windows it is `C:\Users\DN\Documents\Audiveris` by default isn't it?
But I can't find any files there. I know that this directory is needed to be there, because audiveris always tells me, that it isn't able to create this directory, if the directory doesn't exists.

Am I right, that this directory is the default directory, which is displayed after loading the `saveFileDialog`?

I think the idea is nice. The only issue is, that the filename of the outputfile is overwritten by the `saveFileDialog` when changing the directory. Is it ok, if I try to fix that?

**Comment by hbitteur** [comment]
@NelDav 
I don't really understand what your problem is.
I just double-checked with my own configuration:
- baseFolder is d:/soft/cases (my specific value)
- useSeparateBookFolder is true (default value)
- useInputBookFolder is false (default value)

I read input from D:\soft\audiveris-github\issues\data\examples\chula.png and choose "Export book as" in the book menu.
It opens a filechooser dialog, with predefined values of:
- folder as d:/soft/cases/chula
- file name as chula.mxl
This is consistent with my configuration.
However, in the filechooser dialog I can change the target folder to something like d:/soft/temp-garbage and the target file name to something like myFileName.mxl.
And the result is actually exported as d:/soft/temp-garbage/myFileName.mxl

In your case, I'd suggest to set the option useSeparateBookFolder  to false, 

You said that you don't understand the role of baseFolder. Its role is to provide the base for any output when you need such base.
And you need it, unless you have set the option useInputBookFolder to true, in which case the "base" for the output is the input folder.

**Comment by hbitteur** [comment]
I would like to first make sure that you can indeed save your output as you wish.
Then, we should avoid the need for the user to directly modify the useSeparateBookFolder  and useInputBookFolder  options, because these are very low-level data.

I would appreciate any advice for a true user-level choice.

**Comment by NelDav** [comment]
I think we are talking at cross purpose. My single problem is, that the filename of the filechooser changes, when I select a directory. I always select a directory during navigation to a directory. Because of that the filename becomes overwritten when changing the directory. 

You could have a look to my PR. I hope it is easier to understand this way.

**Comment by hbitteur** [comment]
@NelDav 
After reviewing your PR, I'm now convinced there is a misunderstanding.

The purpose of the dialog (based on JFileChooser) is to prompt the user for the full path of some file.
The dialog is generally prefilled with default values based on the context (what the file is meant for) and user configuration (the various options the user can play with: baseFolder, useSeparateBookFolder and useInputBookFolder).

When I say "the full path of some file", I mean the Path (Java notion) to the physical file. A path is the sequence: device + folder(s) hierarchy + fileName.

For example in path  "/full/path/to/file.ext", we can see:
- "/full/path/to/" which is the hierarchy of folders,
- "file.ext" which is the file name.

So, Audiveris let the user provide this whole path, even though default values are initially presented in the dialog. The user is free to accept or modify the device+folders part and the fileName part.

In the JFileChooser, the user can change both:
- the target device/folder hierarchy (field at the top of the dialog, following "Save In:" label, or by typing the folder sequence directly at the beginning of the File Name field)
- the file name (via the File Name field).

Contrary to what you said, modifying the target directory does NOT overwrite the file name (and this is fortunate!).

**Comment by NelDav** [comment]
The reason why this Issue is closed is explained at #406
