### ISSUE TITLE
transcription stops with java.lang.NullPointerException after many "collision SlurInter" warnings

### ISSUE THREAD

**Issue by Bacchushlg** [Audiveris/audiveris#416]
![I Wonder Why (3)](https://user-images.githubusercontent.com/33522630/89981047-70cc2c00-dc73-11ea-9d10-55f5abeb7824.jpg)

The transcription stop in step rhythms with:
Error in performing [RHYTHMS, PAGE] java.util.concurrent.ExecutionException: java.lang.NullPointerException

It seems that the reason are the many "collision SlurInter" warnings before - which are unclear to me.

The complete score consists of 5 pages - 3 of them show the same behaviour.

Version: 5.2.1-alpha:b2de98813

**Comment by hbitteur** [comment]
Hello Baruch!

I noticed a few problems:

- Even if the braces are correctly recognized and located, each system exhibits 3 parts made on 1 staff each. We would have expected each system to be made of 2 parts, 1 staff for first part and 2 staves for the second part.
This is due to the fact that this score exhibits vertical connectors between **all** staves of the system. I mean, among staves 1,2 & 3 of each system, we would need vertical connectors between staves 2 & 3 (same part) but not between 1 & 2 (separate parts). This is the reason why the OMR engine did not accept staves 2 & 3 as a single part.
- Many stems are temporarily considered as arpeggiato candidate symbols. Fortunately they get discarded at LINKS step, but I need to investigate why these stems still get considered as candidates during the SYMBOLS step, perhaps because their grade is too weak. I need to check this.
By the way, LINKS step, as REDUCTION step, performs SIG reduction. Based on symbols intrinsic grade, contextual grades are computed thanks to supporting relations (LINKS), and then reduction is performed using contextual grade. This is the reason why some symbols candidates may be discarded during LINKS step.
- The NullPointerException occurred on TupletInter '3' when the OMR engine computed the containing measure for this triplet. See in the picture below this triplet, embracing chords located in the staff above, while the triplet symbol itself is almost stuck to the staff below.
![image](https://user-images.githubusercontent.com/22053634/89996950-bc8acf80-dc8b-11ea-943f-aa9f36c2231c.png)
If the two lower staves were contained in the same system part, the measure height would embrace the height of the two staves. But this is not the case here (see problem 1 above), so the part/measure height is limited to the middle staff. In other words, the triplet belongs to the measure of its embraced chords (staff 2) although physically it belongs to staff 3.

By selecting "View | Show attachments" (assuming you have selected DEBUG in the advanced topics), you are able to visualize the "limits" of staff area as in the following picture:
![image](https://user-images.githubusercontent.com/22053634/89998740-391ead80-dc8e-11ea-8e85-ae060a5d08e8.png)
In this picture, the upper line displayed in red and pointed by the arrow, is not a staff line but the lower limit of the above part/staff area. You can notice that the center of the triplet symbol is located outside this area. Hence the computation failed.

Now, what can we do?

This boils down to the fact that the parts were not correctly detected in first place. I think that Audiveris is right in considering that this is **not** a legal 2-staff part. See examples of piano and voice scores, you'll notice that these vertical connectors exist within the piano staves, but not between the score staff and the first piano staff. Have a look at Dichterliebe in Audiveris examples. The left-most barline is not an inter-staff  "connector", it is only a system-defining barline.

To save your life, at least for today, here is the trick, to be performed at end of GRID step:

1. Manually remove all the braces
2. Manually re-insert them by dragging brace symbols from the shape palette

Et voilà ! The parts are now well defined.

Why? Because the user is always trusted. If the user manually drags a brace into a suitable location, then there must be a 2-staff part. Period!

**Comment by Bacchushlg** [comment]
Oh, I didn't notice this.
I agree that almost all scores use separate vertical connectors. But in this book that I just started to scan - all scores (25) (release of the book: 1992) are notated in this way. Seems to be a problem of this notation program - or of the user who used it.

But I also have a couple (but only few) of SATB scores that also use common vertical lines throughout the system.

Is it really a problem to accept these lines - or do you need it to keep the parts together?

**Comment by hbitteur** [comment]
The problem is mainly with the brace symbol.
Because I noticed that scores may use braces just for the purpose of gathering staves as a group. 
Thus, the OMR engine needs some additional information to decide whether these "grouped" staves correspond to one single part or not. And vertical connectors bring this additional information.
I don't have a precise example immediately available, but I guess we could find some on IMSLP.

As usual, if you have a bunch of scores that don't comply with this "rule", we could easily add a switch in OMR engine to enforce or not this behavior on these particular scores.
The cost is just additional switch for the user to deal with.
Just tell me.

**Comment by hbitteur** [comment]
See https://www.scribd.com/document/397216550/IMSLP13118-Dvorak-Symphony-No-8-III-pdf exhibiting braces just for grouping. Notice each of these braced groups does not correspond to a single instrument. And these groups have vertical connectors above and below.

Same thing for many Mozart symphonies.
For example https://imslp.org/wiki/Symphony_No.19_in_E-flat_major,_K.132_(Mozart,_Wolfgang_Amadeus)

And here is the first page of "la plus que lente" (Debussy), with true braces. Notice the lack of vertical connectors around the braced parts:
![image](https://user-images.githubusercontent.com/22053634/90046134-54aaa800-dcd0-11ea-9044-93db8f9354e2.png)

**Comment by hbitteur** [comment]
It is important for the OMR engine to know if the part at hand contains one or several staves.
In the 2-staff case, beams, stems, slurs, etc can extend between one staff and the other, while this is not possible for the 1-staff case.

**Comment by Bacchushlg** [comment]
Ok, I understand that it is really difficult to handle these different usages of braces automatically.
I propose to keep automatic detection as it is now, and only provide a possibility to correct manually in the GUI. 
This means in the concrete case (top score) that there needs to be a command like "split staves".
And of course, your proposal of the "switch in the OMR machine" is a good idea, too.

By the way: for a long time, I have in mind to have a sort of initial pop-up dialog after starting the transcription. This could simply be the book parameters dialog.
Maybe this pop-up only as an option, for "sophisticated users" ;-))

**Comment by hbitteur** [comment]
I used the "I wonder why" score example to implement the ability for the end-user to explicitly link a rest to a beam (2 cases in this sheet).
See commit 4d406296f8f1bd093bf163c7252a0cedc8a2bcdb on development branch
