### ISSUE TITLE
Transcription stops with java.lang.NullPointerException: Error in guessRole for TextLine 

### ISSUE THREAD

**Issue by Bacchushlg** [Audiveris/audiveris#419]
![Aint't She Sweet (2)](https://user-images.githubusercontent.com/33522630/91139889-c3640a00-e6af-11ea-90fc-455efad77dcf.jpg)

transcription of this score stops during processing the chord symbols (all 3 pages of this score behave like this).

I assume that this should not stop the complete process.

version: 5.2.1 4cbe2c42c

**Comment by hbitteur** [comment]
This seems due to chord name "C+5" which is not correctly handled.
I need to work on it.

**Comment by hbitteur** [comment]
@Bacchushlg, I need your help here.  
I'l trying to come up with a new consistent version of ChordNameInter class, which is in charge of handling all chord names.

Typically, how should we interpret the following chord names, taken or derived from your own example above:

- **C7**:  C (root) + E (major third) + G (perfect fifth) + Bb (minor seventh). In other words chord type is DOMINANT. So far, so good.
- **C7/9**: What is the role of '/' character, here? A '/' is generally used to introduce a bass note, lower than the root note, as in "C/G" for example. Here, it seems to be used as a separator between "7" and "9", perhaps meaning something like "C7(9)" where the ninth degree is added to the dominant "C7". But, to my knowledge, a "C9" already contains the minor seventh, hence what is the purpose of explicitly naming "7".
- **C7/11**: Here again, do this mean: 7 + 9 + 11? In "C11", 7 and 9 are implicitly part of the chord.
- **C+5**: The character '+' is generally meant to specify an augmented fifth. Hence, what is the purpose of explicitly naming "5". To my knowledge, "C5" means C power chord, not minor or major, since there is no third. "C5" means notes C (root) plus G (perfect fifth). But what is the meaning of "C+5"?
- **C7/+5**: Problem rather similar to the one just above.

We could be tempted to just take the chord name strings as they are and not try to parse them. But we have two problem. First,  MusicXML expects a "Harmony" element for each chord name. Second, Audiveris can differentiate lines of chord names from plain text or lyrics, only by trying to parse them as valid chord names.

Here are a few links to some sources I have used:
- [MusicXML chord type values](http://usermanuals.musicxml.com/MusicXML/MusicXML.htm#ST-MusicXML-kind-value.htm)
- [https://www.musicnotes.com/now/tips/a-complete-guide-to-chord-symbols-in-music/](https://www.musicnotes.com/now/tips/a-complete-guide-to-chord-symbols-in-music/)
- [https://www.stringkick.com/blog-lessons/chord-names-symbols/](https://www.stringkick.com/blog-lessons/chord-names-symbols/)

Thanks in advance for any help you can provide

**Comment by Bacchushlg** [comment]
C7/9: What is the role of '/' character, here?
The meaning of the slash depends on the following character: in case of a letter, it's just what you described above. In case of a number, it's an additional note with intervall resp. to the base note.
You are right, that normally 9 implies the 7. But it is rather usual that the 7 (and others) are added explicitly.

C7/11: Here again, does this mean: 7 + 11? In "C11", 7 and 9 are implicitly part of the chord.
same as above

C+5: The character '+' is generally meant to specify an augmented fifth. Hence, what is the purpose of explicitly naming "5". To my knowledge, "C5" means C power chord, not minor or major, since there is no third. "C5" means notes C (root) plus G (perfect fifth). But what is the meaning of "C+5"?
You find different writings for the augmented fifth, I saw C5+ as well as C+5.
A power chord is C5, without + or -.

C7/+5: Problem rather similar to the one just above.
Same logic as above.

For me this wikipedia article is very helpful:
https://en.wikipedia.org/wiki/Chord_letters

**Comment by hbitteur** [comment]
The WikiPedia article is really interesting, thanks Baruch.
I will need to relax the rules in order to accept all these "variants"...

**Comment by Bacchushlg** [comment]
problem is solved with version f13d9e97b7
