### ISSUE TITLE
transcription tends to detect bar lines instead of stems

### ISSUE THREAD

**Issue by Bacchushlg** [Audiveris/audiveris#422]
![Easy 03](https://user-images.githubusercontent.com/33522630/94045118-4ec7dc80-fdcf-11ea-921f-fc171e37c5fb.jpg)

I have a couple of scores where the transcription tends to see bar lines instead of stems.
Additionally sometimes there stay measures limits even after deletion of the bar lines (This seems to happen, if transcription has removed a bar line during reduction - but the measure limits stay detected).
In the score above in line 3, 4th measure, there appear 2 additional measures (can be seen in output mode)

**Comment by Bacchushlg** [comment]
I get the above problem with almost every 2nd score that I transcribe.
Maybe I have done some wrong setting in my parameters?
Here are 2 more files with the same problem:
[Time to Wonder.zip](https://github.com/Audiveris/audiveris/files/5504991/Time.to.Wonder.zip)
[Wonderful World.zip](https://github.com/Audiveris/audiveris/files/5504993/Wonderful.World.zip)

**Comment by hbitteur** [comment]
There are several colliding problems here.

For one, a barline (the part within staff height) is allowed to overlap with a beam. I remember very few examples of such configurations, so I propose to forbid this overlap.

The second problem is really a bug. While barlines are declared to be compatible with beams (see above), the StaffBarlineInter class is not! That's the bug, because a StaffBarlineInter is an ensemble that represents the horizontal grouping of one or several BarlineInter (for example a double barline). Most of the time, a StaffBarlineInter ensemble is composed of just one barline. 

As proposed above, I will fix this inconsistency by declaring beams and barlines **not** overlap-compatible.
But this will concern only barline/beam collisions.

Another problem is, I think, the fact that barline detection produces too many false positives. I will try to be more strict on the lack of black pixels aggregated on left or right sides on the barline candidate, in order to detect and discard stems that have a head located within staff height. This should work well with good-quality and straight images, and much less with poor-quality and slanted images. We'll see.

**Comment by hbitteur** [comment]
Oops! Oops! Oops!
In commit 70bd856b143425ef431aaaff3ee16ff4abfbad64 made on August 10, and named "Re-engineering of StemsBuilder", I refactored many classes related to the building of stems near heads and beams. This was at the beginning of my current work on poor-quality scores (work still in progress today...)
For some reason I can't remember I had made a quick and dirty code modification, and I forgot to clean it up afterwards.

Since August 10, Stem building in development branch has been impacted by this, resulting in rather poor stems (grade: 0.5) and thus easily defeated by competing barlines. And this is what happened in your examples.

Needless to say how much I'm feeling bad.
Fix will follow quickly.

**Comment by hbitteur** [comment]
Bug fixed in commit 95092479f6a5341d35b1a0b577cf5403704d3e1a
Please pull from development branch.

However, I keep the idea on barline detection improvement. Should be addressed at some point in the future.

**Comment by Bacchushlg** [comment]
I already had the impression that this "feature" had been introduced with one the last versions.
Now, everything works again as formerly - concerning the wrongly detected bar lines.

**Comment by hbitteur** [comment]
@Bacchushlg 
I've just pushed this commit 4a6141a4c2107846ef139e02eba7c6a0b37ca9a5 which is meant to detect barlines more efficiently by discarding stems with attached heads within staff height.
Some of these false barlines may still be detected but they are now assigned a lower grade and are defeated against stem with attached heads during the REDUCTION step.
So this new version works really well with your 3 examples. 

Just 2 barlines are not detected in "Time to Wonder" example. This is due to the fact than there is an ending leg (refrain 1 and refrain 2) that is stuck to the barline below, resulting in a high barline glyph that goes too high above the staff limit.
There might be some tricks to handled these, especially the thick barline with the thin ending leg above. For the case of thin leg aligned with thin barline, I have no clue today.
If you have any idea to handled these 2 cases, I'm interested !

**Comment by Bacchushlg** [comment]
From my point of view, these double bar lines are a "nice-to-have". Esp. those double thin.
The other one is part of the repeat sign, which is not detected. Ok, detection would be fine - but also not critical. For me the behaviour is almost perfect now.
Time to provide a new version with installer etc. :-))

**Comment by hbitteur** [comment]
FYI, I need to complete the important task I started to improve stems building and their linking to heads and beams, especially with poor-quality images. To do this, I use the good beams as kinds of "umbrellas" to aggressively support stems and heads located above and/or below. Initial results are very promising.

Regarding user documentation, Audiveris handbook is also to be updated for 5.2.

And then, finally, release 5.2 will get out... ... ... ...

**Comment by hbitteur** [comment]
>>> From my point of view, these double bar lines are a "nice-to-have". Esp. those double thin.
>>>The other one is part of the repeat sign, which is not detected. Ok, detection would be fine - but also not critical.

In fact, repeat signs are generally detected, provided that the vertical pair of repeat dots is close to a horizontal pair of barlines (thick + thin + dots) for a left repeat and (dots + thin + thick) for a right repeat.

In the case at hand, the thick barline was not detected (because merged with an ending leg above), and therefore the repeat sign was not recognized. But if before the SYMBOLS step you manually insert the thick barline in proper location, the repeat dots should be recognized as such in the SYMBOLS/LINKS steps.
