### ISSUE TITLE
rhythm check fails for 1/8-1/4-1/8 beam combination

### ISSUE THREAD

**Issue by Bacchushlg** [Audiveris/audiveris#424]
[kleine Konditorei.zip](https://github.com/Audiveris/audiveris/files/5372672/kleine.Konditorei.zip)

In this score almost all appearances of beams containing a 1/8-1/4-1/8 combination are not properly recognised.
Astonishing that some are recognised...

**Comment by hbitteur** [comment]
For some reason (that I'll need to find out), first chord on the upper staff and first chord on the lower staff are not put into the same time slot, despite their vertical alignment...
To fix this, simply pick up one note of the upper chord, and one note of the lower chord. Then use a right-click for the popup menu which should provide a "Chords" submenu offering to select "Same time slot". And the measure turns white.
Meanwhile, I'll investigate the root cause.

**Comment by Bacchushlg** [comment]
Thanks a lot for this advice. I was successful to export the complete score now.
