### ISSUE TITLE
Manually declaring what a selection is

### ISSUE THREAD

**Issue by git-along-little-dogies** [Audiveris/audiveris#427]
In multiple cases in my score audiveris doesn't recognize an eighth-note rest.  Unfortunately, not only does it not show what I need as an option (which is understandable), but it provides no way for me to make a manual correction.  Both the Shape and Basic Classifier offerings are utterly unrelated to what I need, and cannot be expanded to show other possibilities.  (Presumably this issue applies to many other needed corrections and not just eighth-note rests; it just happens that in my document this is the most frustrating issue I can't fix.)  I imagine two ways of resolving the situation: 
1) Allow the user to drop down menus and/or type in the correct term at the top; 
2) Allow the user to drill down through various types of possibilites.  In this example, the sequence would be Rhythm -> Rests -> Eighth  (There might be additional options relative to shape or position, etc.)

FTR I'm running version 5.1.1:78dfce31f on Bodhi Linux 5.1.0 with the Moksha desktop 0.3.1.

**Comment by hbitteur** [comment]
Please correct me if I'm wrong, but when I read:
> "it provides no way for me to make a manual correction"

I understand you are not yet familiar with Audiveris tool.

Because the major feature provided by 5.1 version was precisely the ability for the end user to correct most of OMR engine mistakes. Additional possibilities are provided in the coming 5.2 version, but even with just 5.1 you have several ways to fix any misrecognition of an eighth rest.

As an introduction, you can have a look at the [tutorial video](https://www.youtube.com/watch?v=718iy10sKV4&feature=youtu.be) recorded by Baruch.

For a more comprehensive description, please refer to [5.1 handbook](https://bacchushlg.gitbooks.io/audiveris-5-1/content/), and especially its chapter dedicated to [manual edition](https://bacchushlg.gitbooks.io/audiveris-5-1/content/edition/).
