### ISSUE TITLE
Transcription failure on excellent PDF score

### ISSUE THREAD

**Issue by rodolfo-medina** [Audiveris/audiveris#433]
Audiveris won't transcribe page 5 of the following score:

[schumann-kreisleriana_op16.pdf](https://github.com/Audiveris/audiveris/files/5515780/schumann-kreisleriana_op16.pdf)

Please help understand why this happens...  thanks

**Comment by hbitteur** [comment]
There was a NullPointerException  on page 5, now fixed by commit 5aae9e48b78b2eb53e461cf14a9aba6011b42808

Also, I noticed several cases still in page 5 where measure rhythm could not be correctly computed. You have noticed some messages like:
>Time inconsistency in {1/8=[HeadChordInter{#4795(0.862/0.862) stf:4 slot#2 off:1/8 dur:1/16}], 3/16=[HeadChordInter{#4769(0.918/0.918) stf:3 slot#2 off:3/16 dur:1/16}]}
>Time inconsistency in {3/16=[HeadChordInter{#4796(0.841/0.841) stf:4 slot#3 off:3/16 dur:1/8}], 1/4=[HeadChordInter{#4770(0.905/0.905) stf:3 slot#3 off:1/4 dur:1/8}]}
> S2 MeasureStack#7 no correct rhythm

You can get these messages when computing measure rhythm, for example when running RHYTHM step or when modifying some items that lead to partial rhythm recomputation, or when explicitly asking for rhythm recomputation at page or measure levels (via the contextual popup menu).

Such an incorrect measure is usually displayed with a pink background. Please use latest commit d651028a3433d5b953ca455fc108f4377f5f699d which provides better detection.
This measure 7 is now displayed as:

![image](https://user-images.githubusercontent.com/22053634/98828158-05dbee00-2438-11eb-8494-731c4ae3921f.png)

You can also ask to dump the voice strips, via the popup menu of a given measure. For the same measure 7, this gives:
<pre>MeasureStack#7
    |0       |1/8     |3/16    |1/4     |3/8     |1/2     |9/16    |5/8     |3/4
--- P1
V 1 |Ch#4768 =========|Ch#4769 |Ch#4770 |Ch#4771 |Ch#7681 |Ch#4773 |Ch#4774 |3/4
V 2 |Ch#4766 ===========================|Ch#4772 |........|........|........|1/2
V 5 |Ch#4794 ===========================|Ch#4798 |Ch#7679 =========|Ch#7682 |3/4
V 6 |Ch#4792 |Ch#4795 |Ch#4796 =========|........|........|........|........|5/16
V 7 |........|........|........|........|Ch#4797 |Ch#7680 =========|Ch#7683 |3/4
</pre>

Looking more carefully at the very first time slot in this measure, you will notice that the chords of upper staff have both an augmentation dot:
![image](https://user-images.githubusercontent.com/22053634/98829452-83542e00-2439-11eb-9e54-82882d5d1d5b.png)
However in the chords of lower staff, only the chord with up stem is linked to an augmentation dot.
![image](https://user-images.githubusercontent.com/22053634/98829572-a088fc80-2439-11eb-8de0-8581fced4d29.png)
This is more obvious when using colored voices, because the augmentation dot is colored according to the color of the voice of the linked chord.
By selecting the augmentation dot, you can also vizualize which heads it is linked to.

To fix this, you have to explicitly link the augmentation to the head in the lower left corner, by pointing to the dot and dragging to the target head and releasing the mouse button. The measure turns white because its new rhythm is now correct. 
A closer look to the dot shows the modification (the dot now exhibits two halves colored according to their related head):
![image](https://user-images.githubusercontent.com/22053634/98830353-9b787d00-243a-11eb-9f3c-216aca6dcdd2.png)

The voices are now like:
<pre>
MeasureStack#7
    |0       |3/16    |1/4     |3/8     |1/2     |9/16    |5/8     |3/4
--- P1
V 1 |Ch#4768 |Ch#4769 |Ch#4770 |Ch#4771 |Ch#7681 |Ch#4773 |Ch#4774 |3/4
V 2 |Ch#4766 ==================|Ch#4772 |........|........|........|1/2
V 5 |Ch#4794 ==================|Ch#4798 |Ch#7679 =========|Ch#7682 |3/4
V 6 |Ch#4792 |Ch#4795 |Ch#4796 |Ch#4797 |Ch#7680 =========|Ch#7683 |3/4
</pre>

**Comment by hbitteur** [comment]
Why all this? Because chords in opposite configuration, one stem up and one stem down) share a common head.

If this common head lies on a staff line or ledger, the augmentation dot cannot be on the line. Thus there are generally two dots, one for the "upper" chord and one for the "lower" chord. This is the case for the upper staff in your example.

Bur when the head lies between two lines or ledgers, there can be at most one physical dot.  This is the case in the lower staff of your example.
The question is then: should we link this dot to the two chords or only one? 
Current algorithm is to pickup the chord with longest duration if their durations are different, and to pickup both if their durations are equal.
This is the current heuristic, perhaps we could let the user choose a different behavior, for example always linking the dot to both chords. This choice could be added to the processing switches (at sheet, book or global level).

Any idea?

**Comment by rodolfo-medina** [comment]
thanks for the recent commits: now page 5 is processed by Audiveris...  great!  As for the choice about dot behaviour, maybe it could remains as it is now if always linking the dot to both chords can lead as well to rythm problems in case the dot belongs to only one of them...  I don't know...

**Comment by hbitteur** [comment]
I have implemented a new processing switch, to let the user decide on the assignment policy of dots to shared heads.
It's available from commit 07bdca247e562a77945ed40285d1af80ca1fb859 in development branch.

In your example, you just have to use the menu "Book | Set book parameters" and set the switch "Link augmentation dot to both shared heads" to true at book or sheet level (it is set to false by default).

**Comment by rodolfo-medina** [comment]
great...  thank you
