### ISSUE TITLE
impossible to build on java 11.0.9 ?

### ISSUE THREAD

**Issue by olof29** [Audiveris/audiveris#435]
on master and on development branches, when i want to build with
`./gradlew build`
i have this : 

`FAILURE: Build failed with an exception.

* What went wrong:
Could not determine java version from '11.0.9'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org
`
i'm on linux debian buster (librazik 3) with openjdk-11-jdk 11.0.9

could i do something ?

**Comment by maximumspatium** [comment]
Please open a new terminal window and execute the following commands:
```
cd [your Audiveris directory]
git branch
./gradlew --version
```
What do the last two commands show?

**Comment by trebmuh** [comment]
_(probably related : #414)_

**Comment by maximumspatium** [comment]
@trebmuh The right solution for both issues has been already told:

If you want to run Audiveris under JDK 11, you has to build it from `development` branch.

The code in the `master` branch uses oldish Gradle Wrapper 4.6 that isn't compatible with JDK 11.
Updating it will be of no avail because the engine code won't compile with JDK 11.

For now, the following rule holds:

- `master` branch requires JDK 8
- `development` branch supports JDK 11

**Comment by trebmuh** [comment]
@maximumspatium I saw that, that is why I made a comment here with link to #414 here one can find the solution.

**Comment by olof29** [comment]
git branch gives me : 
`* development
  master
`
and ./gradlew --version gives : 
`
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine java version from '11.0.9'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org
`

**Comment by trebmuh** [comment]
Then try `git checkout development` before doing `./gradlew`.

**Comment by olof29** [comment]
i am already on development branch

**Comment by trebmuh** [comment]
Give us all the precise steps you're doing.

**Comment by maximumspatium** [comment]
Try to clear Gradle cache:

`rm -rf $HOME/.gradle`

**Comment by olof29** [comment]
i tried to clear gradle cahe, but it dont build : 
`Downloading https://services.gradle.org/distributions/gradle-4.6-bin.zip
......................................................................
Unzipping /home/olivier/.gradle/wrapper/dists/gradle-4.6-bin/4jp4stjndanmxuerzfseyb6wo/gradle-4.6-bin.zip to /home/olivier/.gradle/wrapper/dists/gradle-4.6-bin/4jp4stjndanmxuerzfseyb6wo
Set executable permissions for: /home/olivier/.gradle/wrapper/dists/gradle-4.6-bin/4jp4stjndanmxuerzfseyb6wo/gradle-4.6/bin/gradle

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine java version from '11.0.9'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org
`

But don't worry, i don't understand why it did'nt work on my computer, but olinux tried and it worked, then he realised a release for librazik 3 (debian buster) working well. Then, i don't need to try anymore to buil it.

thanks for your job and your help

**Comment by maximumspatium** [comment]
The code in the `development` branch should download Gradle 5.6.4, not 4.6!
If it tries to download Gradle 4.6 you must be on the wrong branch.

I'd try the following steps:

- ensure you've cloned the Git repository using `git clone`. Don't download Source ZIP! It won't work because the zip doesn't contain required Git files.
- ensure the right branch is checked out:
`git checkout development`
- ensure the latest code is pulled:
`git pull`
- ensure Gradle cache doesn't contain incompatible dependencies:
`rm -rf $HOME/.gradle`

If the above steps succeed, you'll should be able to compile and run Audiveris. A better approach would be to clone Audiveris to another directory and try from there.

**Comment by olof29** [comment]
ok, i tried it, and it works this time.
thank you

**Comment by maximumspatium** [comment]
Fine!
