### ISSUE TITLE
Error in performing [CHORDS, CURVES, SYMBOLS, LINKS, RHYTHMS, PAGE]  java.lang.NullPointerException

### ISSUE THREAD

**Issue by Bacchushlg** [Audiveris/audiveris#437]
The score of issue #344 makes a new problem on page #1, which results in a nullpointerexception.

I already removed the wrongly recognized 3/4 in S2, but the error message stays alive.

**Comment by hbitteur** [comment]
I could not reproduce the NullPointerException on this page.

No big deal on this page, I simply unchecked the book/sheet switch on "Use of system indentation" since the 2 first systems are indented and we can think there is no movement break between first and second systems of page 1.

I had to manually remove the 3/4 time signatures and re-insert the left repeat signs. 
Plus a couple of 1/8 rests to be manually inserted since Audiveris does not share rests between voices.
And a triplet.
That's all.

Now, I was a bit surprised by the fact that repeat barlines at start of system 2 had been replaced by (false) 3/4 time sigs.
It turns out that these barlines (thick and thin) had a grade of 0.779 and 0.794 while the 3/4 sig exhibited a grade of 0.798, hence the result.

OK, with the recent work on barlines, their intrinsic grades may now be a little bit lower. But I checked the underlying glyph of the false 3/4 item: it's the compound of thick + thin + the upper repeat dot, for which the neural network of the glyph classifier gives 3/4 with 0.9969 (and 0.9969 * 0.8 = 0.798). Such classifier mistake is just unbelievable!
Can you observe such behavior on your side? I'm afraid so.

I just checked in the samples used to train the network, I found nothing abnormal regarding time sigs.
Perhaps I could add a few samples of (thick + thin) barline couples and tell the network to classify them as clutter. Other than that I have no clue.

**Comment by Bacchushlg** [comment]
curious. I retried and I get the error again.
I looked around to my settings - but I have only 1 individual setting that maybe could apply (mincontextualGrade). I reset to default, but with no improvement.
I upload the omr-file. Maybe you find something suspicious inside...

[Blues and Trouble.zip](https://github.com/Audiveris/audiveris/files/5541128/Blues.and.Trouble.zip)

**Comment by hbitteur** [comment]
I have a problem with your .omr file: there is no BINARY.png for sheet 1. There is one for sheet 2, but the problem we are trying to fix is on sheet 1...

You can check by yourself, simply change the .omr extension for a .zip extension and open the archive.

**Comment by Bacchushlg** [comment]
I just retried... and get the same output, when I save the OMR file.
But the source is the same as the original one - maybe you can merge it into the file ?

**Comment by hbitteur** [comment]
OK, I made a kind of cut & paste, to come up with a .omr with the needed binary images in it.
And now, I'm able to reproduce your error, it's an IndexOutOfBoundsException raised when loading the .omr file.

I checked the sheet#1.xml file, and it is indeed corrupted OMR-wise.
The sheet contains 2 pages (if you uncheck the switch useSystemIndentation, you should have exactly 1 page in this sheet. Please double-check that the switch is off for this book). This is not the error, but you'd better restart from scratch (the .tif file) with the switch unchecked.

The sheet#1.xml file contains an error. System 2, made of staves 3, 4 and 5, declares to horizontally contain 3 stacks.
This number is correct at staff 3, staff 4 but not staff 5, for which the files gives just 2 measures instead of 3 as expected. Hence the exception at reload time.

I don't know where this inconsistency comes from. Perhaps this occurred when you re-inserted the barlines incorrectly discarded by false 3/4 time sigs.

Anyway, I have fed the classifier with repeat barlines as clutter, and it now works correctly in commit 7972d8d784653ad6cb409a207d628b0922d1a0ea
Please pull again

**Comment by Bacchushlg** [comment]
solved with version 145bc93
