### ISSUE TITLE
disable warning "unsufficient beam scaling data

### ISSUE THREAD

**Issue by Bacchushlg** [Audiveris/audiveris#438]
I rather often get the warning:

> Raw results of SCALE step give: beam(12 extra)
> There is no sufficient data to define beam thickness. Value of 12 pixels is just an extrapolated guess.
> 
I always confirm to continue, and in almost I get a good result.
Can I set the warning limit somewhere?
Also it would be fine to have the possibility to ignore for the complete score (all the following pages)

**Comment by hbitteur** [comment]
I agree, there is room for improvement here.
The root cause is that there is not enough data regarding beams in this sheet (in SCALE step), thus the estimate on beam height is not reliable.
And the problem is that accuracy for this height is key. Beam retrieval works rather well but needs a precise height parameter: too low or too high and the engine may miss many beams.

The current algorithm is as follows:
- During the SCALE step, the histogram of vertical black runs is searched for 2 peaks: the first one gives the most frequent staff line thickness, the second one gives the most frequent beam thickness. Each of these peaks needs to be validated against specific numbers of runs (quorum). While a true score always exhibits many runs of staff lines, this is not always the case for beams. For example just a couple of beams in the page will not be sufficient to reach the quorum for beam runs.
- If quorum is not reached for "beam runs", then a not-too-stupid beam height is estimated, based on staff line thickness and staff interline. But this "extrapolated" value may be a wrong guess, too far from real value, hence the idea to prompt the user for validation.

The current solution is not very convenient because it forces the user to stop the engine, to measure the typical beam height by himself, to enter this value into the sheet scaling data, and to re-launch the engine for the following steps.

Very often, I personally use the scale histogram (visible via menu "Sheet | Display scale plots) to read the histogram peak and copy it to the sheet scaling data. In other words, I bypass the quorum mechanism and simply take the non-validated value. Therefore, an easy improvement would be to provide the user with both the extrapolated value and the peak value (non-validated). So the user could simply click on one of these 2 values and keep going.

The question of keeping the same beam height parameter for all the subsequent sheets is more problematic. If all sheets in the book exhibit the same beam height, fine! We can even cope with the case where all sheets have not been consistently scanned with the same resolution.
But if the beams are really different from one sheet to the other, then some sheets will need a specific value. To deal with this, we could provide a new parameter within the Book/Sheet parameters (dialog is available in "Book | Set book parameters") which would allow the specific / inherited value mechanism. An additional bonus of this approach would be to preserve this beam height parameter, even when book or sheet processing is restarted from scratch.

I'm putting this on the todo list.

**Comment by hbitteur** [comment]
Here it is, commit c8982c01bbabccc575dd9ca5dd68272fb82ff87d on development branch.
Two major modifications:

1. Constraints for measurement out of histogram of vertical runs have been relaxed: quorum value is lower, and histogram peak can be accepted even if lower than quorum provided that measured value is close enough to guessed value.

2. The user interactive dialog has been removed. In the case where the measurement cannot be accepted, the guessed value is used instead but there is a warning message in the log window.

**Comment by Bacchushlg** [comment]
works fine now (version c8982c0) - and I see no disadvantage during processing.
