### ISSUE TITLE
program shutdown in tesseract step due to language files

### ISSUE THREAD

**Issue by Bacchushlg** [Audiveris/audiveris#45]
The tesseract step outputs errors:

Failed loading language 'fra'
Failed loading language 'eng'
read_params_file: parameter not found:

After this Audiveris shuts down with no additional errors.

I have tried several combinations: put the language file to a certain directory and set TESSDATA_PREFIX to this directory or create a directory "C:\Program Files (x86)\tesseract-ocr\tessdata" and put the language files there. I get the error in both cases.
The language files date from 15.01.2018.

**Comment by maximumspatium** [comment]
@Bacchushlg 
Some more info would be helpful. Which Tesseract version is shown at Audiveris' startup?
Which Java/OS are you running?

**Comment by Bacchushlg** [comment]
- Audiveris:    5.0.0:743f229a9
- OS:           Windows 10 10.0
- Architecture: amd64
- Java VM:      Java HotSpot(TM) 64-Bit Server VM (build 25.152-b16, mixed mode)
- OCR Engine:   Tesseract OCR, version 3.04.01

Just one more question: I have just the 4 language files in the tessdata directory: deu, eng, fra and ita.traineddata
Should there be more?

**Comment by maximumspatium** [comment]
@Bacchushlg Thanks!

Please provide me with a detailed description on how did you install Tesseract language files (where are they located, where they came from etc.)

> I have just the 4 language files in the tessdata directory: deu, eng, fra and ita.traineddata
Should there be more?

It depends on your targets. In the minimal configuration, only eng.traineddata + config files are required. For every further language in your scores, you'll need to add an appropriate OCR language.

**Comment by Bacchushlg** [comment]
I found the reason for my problem: I had downloaded the actual .traineddata-files, which only work with tesseract version 4, while audiveris uses version 3.
I downloaded the correct ones now and it works fine.
Just one more question: is there some documentation about the GUI of audiveris? I don't understand some features, esp. I don't understand how to train elements (e.g. make audiveris understand, that a certain "3" belongs to a triole).

**Comment by maximumspatium** [comment]
> I downloaded the correct ones now and it works fine.

I'm glad you solved your problem!

> is there some documentation about the GUI of audiveris?

Currently no, but we'll add one very soon because v5.1 is about to be released.

> I don't understand how to train elements (e.g. make audiveris understand, that a certain "3" belongs to a triple).

Left click on your "3" in the score, go to "Shape" palette in the panel to the the right, click on the pedal mark (𝆮) followed by a click on the TUPLET_THREE symbol. With a bunch of luck, your symbol will be converted to the desired tuple...

**Comment by maximumspatium** [comment]
I'll close this issue because the original problem has been solved.

**Comment by hbitteur** [comment]
@Bacchushlg 
Writing doc on the UI provided by coming 5.1 release stands high on our todo list, right after fixing some hot issues like popup menu on MacOS, or lyric lines, etc. (8 issues as of today).
I'm closing yours since Tesseract is not OK for you. So, that's 7 issues left.

Doc should be available very shortly. Keep in mind however, that the training of classifiers is a bit more complex than plain end-user actions, but we'll address it as well.
