### ISSUE TITLE
Same voice but different colours?

### ISSUE THREAD

**Issue by rodolfo-medina** [Audiveris/audiveris#451]
In the screenshot you see notes belonging to the same voice but coloured with the different colours violet and red.  Why?

PDF score attached.  Thanks.

![screenshot 2020-12-23 08:33:56](https://user-images.githubusercontent.com/64352612/102976617-bd652500-44f9-11eb-8106-731d43d50d1a.png)

[clementi-gradus17.pdf](https://github.com/Audiveris/audiveris/files/5734116/clementi-gradus17.pdf)

**Comment by Bacchushlg** [comment]
I assume that the reason is that the first 2 chords are not recognised as separate voices and therefore the internal tick counting gives a wrong result - which seems to need setting the last notes to a new voice.
Astonishingly the export is almost ok - just the mentioned chords need to be set to voice #1.

**Comment by hbitteur** [comment]
@rodolfo-medina 
Having a careful look at your image, color is not red.

Red color is reserved for objects in some **abnormal** status.

Here, we are on first staff in part, and checking with the color legend (displayed as a 1234 / 5678 image at top center of main Audiveris window), we can see that this is the color of voice 3.

And indeed, the underlying chord exhibits a stem down while the chord just above exhibits a stem up. These two chords must obviously be in separate voices, and not belong to the same voice as you expected.
