### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by chrisspen** [Audiveris/audiveris#459]
Running:

    ./gradlew build

Fails with the error:

    Could not determine java version from '11.0.9.1'.

I read that you don't support Java 10 or 11, but these should still be backwards compatible with the versions you do support. So I'm not sure why the build would fail at this step.

**Comment by chrisspen** [comment]
Neverrmind. Fixed by building with the development branch as explained in issue #435.

You might want to note this somewhere in the docs, as it seems to be a pitfall several people have fallen into.

**Comment by hbitteur** [comment]
@chrisspen 
You are right, this is something we have to explain better.
Improving the building (and installing) processes is on the todo list for coming 5.2 release.

In terms of backwards compatibility, Audiveris application is rather OK: 5.2 is able to deal with .omr files created with 5.1 or 5.0. (And before 5.0, 4.x releases provided nothing like a .omr project file).

The problem is more on Java side: Java 9 (and 10 and 11) is not transparently compatible with Java 8, for the simple reason that Java libraries have been reorganized. Some features like JAXB that were included by default in Java 8 must be now explicitly imported with Java 9. In other words, switching environment from Java 8 to 9 requires modification on Audiveris side (typically the Audiveris build.gradle file).

For the time being:
- **master** branch (current 5.1 release) requires Java **8**
- **development** branch (future 5.2 release) requires Java **11**
