### ISSUE TITLE
problems with recognition of triplets

### ISSUE THREAD

**Issue by Bacchushlg** [Audiveris/audiveris#46]
![coharm - ein freund-stimmen-02](https://user-images.githubusercontent.com/33522630/35232064-c20de102-ff9a-11e7-9023-8acd7d851e6a.jpg)

the appended file contains a lot of triplets. Unfortunately most of them are not recognized. Maybe the problem is simply in some wrong defined default values for the symbols recognition(?).

**Comment by Bacchushlg** [comment]
Hmmm...
It's really a pity that this "minor" detail sometimes leeds to a lot of after-work. What I don't really understand is the big difference of the classifier values, especially: why sometimes the highest score is set for "DIGIT_3" rather than for "TUPLET_THREE". This is the most often appearing mis-recognition in this score.
The other case is the recognition of a "word" like "1---3---1", that is then marked as "clutter".

If these 2 cases could be managed, the recognition would be almost perfect!

Just to say it once more: I am very pleased about the over-all quality of the scans!!! This is, why I think it's a really pity that this "minor" problem exists.

**Comment by Bacchushlg** [comment]
[Riverdance.pdf](https://github.com/Audiveris/audiveris/files/1656489/Riverdance.pdf)

Another trial concerning triplets: this time I have exported a pdf directly from MuseScore und imported into Audiveris.
1.: direct import is almost not usable: it seems that the import uses a too low resolution.
2.: convert to TIFF and then import: gives a much better result, but: in the 2nd line many triplets are evaluated as "text" although the classifiers give the highest value for TUPLET_THREE.?!?

Curious...

**Comment by maximumspatium** [comment]
> in the 2nd line many triplets are evaluated as "text" although the classifiers give the highest value for TUPLET_THREE.?!?

As already explained, this is an OCR-related problem we're currently trying to fix. You can follow the related discussion [here](#44) and [here](https://groups.google.com/d/msg/tesseract-ocr/GSS6ldaxpyA/OUfa96KYBQAJ) if you like.

**Comment by hbitteur** [comment]
@Bacchushlg 
I have just tried your first example, there are several problems.

+--3--+ is picked up by the OCR and more or less transcribed to a valuable piece of text. This prevents the following SYMBOLS step to evaluate them (and potentially recognize them as triplets). IIRC, only "3" and "6" OCR'ed good words are forced to be presented to SYMBOLS classifier, In this case the OCR value is not "3", but something like "1-3-1" word,
This conflict between TEXTS and SYMBOLS steps won't be solved within the 5.1 time frame, but the 6.0 featuring a patch classifier, likely to better tackle such case.

But beware, many triplets are physically missing in the original image. This is the case for the very first triplet in this example. A human being rather easily understands that the "3" that appears above the top staff, applies to the chords at the top of the staff, plus the chords right below in the same staff, plus the chords in the next staf below as well. For Audiveris, there is yet no support for such behavior.

**Comment by maximumspatium** [comment]
> In this case the OCR value is not the word "3", but something like word "1-3-1"

Yes, the problem is the misleading brackets in the tuple symbols - OCR layout systems tend to classify long, thin and straight objects as text.

> This conflict between TEXTS and SYMBOLS steps won't be solved within the 5.1 time frame, but the 6.0 featuring a patch classifier, likely to better tackle such case.

Another proposal is to split up OCR layout analysis and actual text recognition into separate steps, with the chance for the user to verify/correct text labeling.

**Comment by Bacchushlg** [comment]
I like very much this last proposual: maybe this is a rather simple to realize approach, and gives the user the chance to improve the scan result with not so much interaction.
I had a similar idea: allow the user to predefine regions for the lyrics before starting the recognition. The result should be the same...

**Comment by hbitteur** [comment]
Yes, giving the user the ability to inject knowledge beforehand, rather than correcting the mistakes _a posteriori_, is likely to improve the workflow and the final result.

Here below is the buffer that Audiveris presented to Tesseract OCR during the TEXTS step on the first example provided for this issue. As you can see, many areas had already been automatically cleared out. This could serve as a basis for user interaction before OCR is actually launched: ability to erase the tuplet regions, ability to flag the lyrics regions as such, etc.

The current TEXTS we have today would be replaced by two steps: LAYOUT and OCR for example. And the user always has the ability to re-perform up to any given step.
A good item for 5.2 release.


![textbuffer](https://user-images.githubusercontent.com/22053634/35332912-1c4c487a-010d-11e8-94b3-ff075f6e14d6.png)

**Comment by miclill** [comment]
@maximumspatium 
You wrote:
> Although I was able to fix most of them manually using the new UI

I don't understand how to do this. Could you please explain or share some link to the documentation?

**Comment by maximumspatium** [comment]
> Could you please explain

Click on the digit "3" above the tuplet, deassign whatever interpretation has been assigned there, then assign it the TUPLET_THREE interpretation using the symbol panel to the right.

And yes, you need to run audiveris from the `development` branch for this to work...

**Comment by Bacchushlg** [comment]
the general recognition of triplets works fine now. There are some cases, where they are still interpreted as normal text - but it's rather seldom and easy enough to fix manually.
