### ISSUE TITLE
Audiveris gets stuck when processing scores via command line on Ubuntu

### ISSUE THREAD

**Issue by luisfvc** [Audiveris/audiveris#469]
Hi,
I had been successfully batch-processing piano sheet music images for almost a year but recently Audiveris has been getting stuck in the middle of the process quite often. I'm processing them via terminal command line on Ubuntu 18.04.5 LTS only until the step GRID.

I try rebuilding audiveris and/or cloning different commit versions (always in development branch), and sometimes it works, sometimes it doesn't (yes it's quite random). For example it wasn't working for the most recent commit (1c17a38), then I changed to a different directory where commit e73f23e had been built, it worked for around 20 pages and then it got stuck for the following page, and now it doesn't work anymore.

Does anyone have a clue? Bellow is the exact moment when it just stops processing and gets stuck forever.

```
WARN  []              TesseractOCR 312  | Tesseract data could not be found. Try setting the TESSDATA_PREFIX environment variable to the parent folder of "tessdata".
INFO  []                      Main 399  | Environment:
- Audiveris:    5.2.1-alpha:e73f23e9e
- OS:           Linux 4.15.0-135-generic
- Architecture: amd64
- Java VM:      OpenJDK 64-Bit Server VM (build 11.0.10+9-Ubuntu-0ubuntu1.18.04, mixed mode, sharing)
- OCR Engine:   No OCR is available!
INFO  []                       CLI 237  | CLI args: [-batch, -step, GRID, -output, /home/luis/dev/umc_allpieces_web/500_test/sheet, --, /home/luis/dev/umc_allpieces_web/500_test/sheet/40_rsz.png]
INFO  []             AliasPatterns 128  | Alias patterns: [(IMSLP[0-9]*)-.*]
INFO  []                      Main 156  | Running in batch mode
INFO  []                  Versions 341  | Versions. Poll frequency: Weekly, next poll on: 15-Feb-2021

```
Also when I try to run the GUI application. none of the buttons in the top menu are clickable, and this is the log when run the GUI via command line:

```
> Configure project :
targetOS=linux-x86_64

> Task :run
WARN  []              TesseractOCR 312  | Tesseract data could not be found. Try setting the TESSDATA_PREFIX environment variable to the parent folder of "tessdata".
INFO  []                      Main 399  | Environment:
- Audiveris:    5.2.1-alpha:e73f23e9e
- OS:           Linux 4.15.0-135-generic
- Architecture: amd64
- Java VM:      OpenJDK 64-Bit Server VM (build 11.0.10+9-Ubuntu-0ubuntu1.18.04, mixed mode, sharing)
- OCR Engine:   No OCR is available!
INFO  []                       CLI 237  | CLI args: []
INFO  []             AliasPatterns 128  | Alias patterns: [(IMSLP[0-9]*)-.*]
INFO  []                   MainGui 425  | Audiveris version 5.2.1-alpha
INFO  []                   MainGui 426  | 
LogUtil. Property logback.configurationFile not defined, skipped.
LogUtil. No /home/luis/.config/AudiverisLtd/audiveris/logback.xml, skipped.
LogUtil. Configuration found file:///home/luis/dev/audiveris_dev/audiveris/res/logback.xml
LogUtil. Logging to /home/luis/.cache/AudiverisLtd/audiveris/log/20210215T172639.log

WARN  []                   MainGui 429  | No OCR is available! Check log file for more details.
INFO  []            PluginsManager 237  | No /home/luis/.config/AudiverisLtd/audiveris/plugins.xml file found
INFO  []           BasicClassifier 362  | Classifier loaded XML norms.
INFO  []        AbstractClassifier 348  | Classifier data loaded from default uri file:///home/luis/dev/audiveris_dev/audiveris/res/basic-classifier.zip
Gtk-Message: 17:26:41.115: Failed to load module "canberra-gtk-module"
INFO  []                  Versions 341  | Versions. Poll frequency: Weekly, next poll on: 15-Feb-2021
```

**Comment by hbitteur** [comment]
@luisfvc 
When you say "it gets stuck forever", can you observe a high CPU consumption (meaning: there must be an endless loop somewhere) or almost no CPU consumption (meaning: it's waiting for some event that never comes).

I noticed two messages in your log:
- The application cannot find **Tesseract data**. I don't think this could block the application (since it is able to detect and warn you about it by printing: "No OCR is available"). I would however recommend to really install needed Tesseract data, just to discard a possible cause of failure.
- Failed to load module "**canberra-gtk-module**". I have no idea what this module is. Reading "gtk" in its name, we can infer this has something to do with user interface. This "might" explain the fact that your buttons appear to be non clickable. Googling about this module name, I read that you should try the command "sudo apt-get install libcanberra-gtk-module".

When running in interactive mode, you said you cannot use any button. Does this concern the tool-bar **and** the menu-bar. In other words, can you still use the pull-down menus?

**Comment by hbitteur** [comment]
No news, good news.
Closing
