### ISSUE TITLE
Transcription stops with Nullpointer exception (No relation for CLinker from VLinker)

### ISSUE THREAD

**Issue by Bacchushlg** [Audiveris/audiveris#471]
[Wenn ich ein Vöglein wär Kommt ein Vogel geflogen - Line Groth Chorarrangement 1_002.pdf](https://github.com/Audiveris/audiveris/files/6121411/Wenn.ich.ein.Voglein.war.Kommt.ein.Vogel.geflogen.-.Line.Groth.Chorarrangement.1_002.pdf)

This score stops transcription with the above error. It is of rather bad quality, but the first steps seem to give a good analysis. No visible reason for the observed stopping.

I also tried export to jpg and re-try with the image. The analysis seems to be very different, then.

used commit: a2826c2

**Comment by Bacchushlg** [comment]
![Wenn ich ein Vöglein wär 2](https://user-images.githubusercontent.com/33522630/110757633-e8832900-824b-11eb-8706-94579388a3ba.jpg)

I tried to improve the image (gaussien blur, remove light grey, sharpen 3 times (unsharp mask).
But again the transcription stops with nullpointer exception.

**Comment by Bacchushlg** [comment]
![Wenn ich ein Vöglein wär 3](https://user-images.githubusercontent.com/33522630/110760552-1e75dc80-824f-11eb-8f0b-f330616bd051.jpg)

Similar for the next page of the score. Another error, but finally stop transcription with nullpointer exception

**Comment by hbitteur** [comment]
I worked on the second version of the first page (less poor quality than the PDF version). 
After SCALE step, I manually forced beam thickness to 11 (was wrongly detected at 6 pixels because of too few beams in sheet).
Then I hit 2 exceptions, that I fixed in the code. One was triggered by the fact that first staff of second system had its last measure not correctly handled, because of missing staff lines.
I also manually entered 3/4 time signature.
And it's OK now.

Please pull last commit (32231784bbfb6bde6e635dc577121517e971f4e3) on "poor" branch which fixes the exceptions.

**Comment by hbitteur** [comment]
We should think of a way to force/fix horizontal limits of systems to cope with such input images.

**Comment by Bacchushlg** [comment]
![Wenn ich ein Vöglein wär 4_](https://user-images.githubusercontent.com/33522630/110949320-c3251680-8342-11eb-9c73-c14ef1e1f645.jpg)

Still trying to get the score translated. This time, it stops at step "curves", with a cryptic error message:

[Wenn ich ein Vöglein wär 4_] Error in performing [SYMBOLS, LINKS, RHYTHMS, PAGE] java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.lang.ClassCastException: class org.audiveris.omr.sig.inter.RestChordInter cannot be cast to class org.audiveris.omr.sig.inter.HeadChordInter (org.audiveris.omr.sig.inter.RestChordInter and org.audiveris.omr.sig.inter.HeadChordInter are in unnamed module of loader 'app')

**Comment by hbitteur** [comment]
I don't get the same exception. Mine occurs in SYMBOLS step, it's a null pointer exception due to processing of a wrong time signature found "outside" of staff width:
![image](https://user-images.githubusercontent.com/22053634/111024908-6af12180-83e1-11eb-8d69-d6be2a1667a8.png)
This is a curtesy measure at the very end of the staff, which in fact contains just a 1-flat key signature.
But since the end abscissa of the staff was not correctly detected, this (wrong) symbol was found outside the staff width and triggered an NPE.
I'll will strengthen code to cope with such anomaly.

**Comment by hbitteur** [comment]
Bugfix available since commit acf65f1ce28618dda5cff4e03c885aede2ce9f94
Beware: this is now in "development" branch (since "poor" branch has just been merged back to "development" branch)

Could you pull and re-check against this score because I'd like to make sure we get the same behavior on your side and on mine.

**Comment by Bacchushlg** [comment]
I assume that I found the reason for the difference of your's and mine observation: I had set "minContextualGrade" to 0.2.
This seems to leed to problems in step Rhythms.
My test score (11 pages) stopped for 5 pages in step Rhythms, now - after reset to default - this just happens for one page. Again with null pointer ex.

But: I observe a big memory leak: after transcription of the 11 page tif, I get a red memory warning with more than 800 MB used..

Do you want to have a look of last critical page? 

By the way: I like very much the idea with the non-modal dialog that is present directly after loading. Very usuful!!

**Comment by hbitteur** [comment]
Could you send me your 11-page file, so that I can test it thoroughly ?

**Comment by hbitteur** [comment]
> "_I observe a big memory leak: after transcription of the 11 page tif, I get a red memory warning with more than 800 MB used._"
Please send me your 11-page example (by private mail if you wish) to find out where memory leaks are hidden.

**Comment by Bacchushlg** [comment]
I had sent it to you yesterday, at 15:39...

-----Original Message-----
