### ISSUE TITLE
Manual for audiveris?

### ISSUE THREAD

**Issue by 7mp** [Audiveris/audiveris#48]
Is there a manual available somewhere? Even a short tutorial to main functions of the software would be super-helpful. :)

I tried to find one by:
- Googling (found an 6 years old post about a currently non-existent manual): https://musescore.org/en/node/16998
- Stack Overflow (not much going on there)

However a full manual isn't necessary for my current needs. They would be satisfied if I knew how to begin (besides random tinkering). For example it would be nice to

- train the classifier for certain symbols with samples
- familiarize myself with the effects of the various options:

Example 1 (on treble clef):

<img width="205" alt="screen shot 2018-01-31 at 3 09 57" src="https://user-images.githubusercontent.com/1826869/35600104-cfcab824-0634-11e8-9087-5e280c06ad70.png">

Challenge: the beam is not recognized. The notehead for the G is correctly classified but at some point it is discarded. I tried to half-blindly adjust various beaming options but with no luck.

Example 2 (on bass clef):

<img width="86" alt="screen shot 2018-01-31 at 3 21 33" src="https://user-images.githubusercontent.com/1826869/35600308-f12295d6-0635-11e8-8cd0-fd7deed64e1a.png">

The eight rest is not recognized on this multivoice system. It seems that this would need some tweaking of SYMBOL recognition but I have no idea what to do.

Any suggestions would be much appreciated. :)

**Comment by hbitteur** [comment]
@7mp I agree that we need a decent documentation.

A few pieces are available in Audiveris [wiki](https://github.com/Audiveris/audiveris/wiki)
Regarding manual score edition, have a look at the "User Interface" section that was put there a few days ago. This is not enough, but you should get an idea of which features are available and how you can use them.

I would suggest that you first use manual score edition. Tuning recognition parameters or retraining the classifier with additional samples is something more complex and a bit touchy. Plus, doc is not yet written.

For your concrete example, rebuilding note head, stem, eighth rest is supported.
Rebuilding a beam is not yet available, give me a few days.
And I forgot: since 5.1 is not released yet, all these features require that you pull the "development" branch, rather than the default ("master") one.

BTW, there is not obvious reason for the OMR engine to not recognize this beam in first place, image quality seems ok. Would you mind posting the input image on fhis forum so that I can check Audiveris behavior on it? If you prefer private mail, use herve dot bitteur at audiveris dot org.

**Comment by 7mp** [comment]
Thank you for your reply, they were most helpful. :) Also, you've got mail.

**Comment by hbitteur** [comment]
This issue is no longer relevant, thanks to the handbook provided with version 5.1, and available online [here](https://bacchushlg.gitbooks.io/audiveris-5-1/content/).
So, I'm closing the issue.
