### ISSUE TITLE
[02_] Error in performing [SCALE,.... PAGE] java.util.concurrent.ExecutionException: java.lang.NullPointerException

### ISSUE THREAD

**Issue by tjwde** [Audiveris/audiveris#488]
Transcribe book fails due to a NullPointerException.

See attachments:
[audiveris.log](https://github.com/Audiveris/audiveris/files/6499326/audiveris.log)
[20210518T094703.log](https://github.com/Audiveris/audiveris/files/6499358/20210518T094703.log)
![02__](https://user-images.githubusercontent.com/16623792/118612990-9962f280-b7be-11eb-9cbe-9f5b703c6b89.png)

Comment: I got around this issue by introducing a try catch for the body of the if statement starting at line 437 in org.audiveris.omr.sheet.grid.PeakGraph.

**Comment by hbitteur** [comment]
I'm trying to understand what happened and which modification you made.

First, could you confirm that you are using the development branch of Audiveris?
The statement "Error in GridBuilder: ..." cannot occur on line 144 as printed in your log file, but on line 171. This makes me think that we are not using the same code.

Also, what did you do in your try/catch? return a null value? 
And what was the initial cause?

Could you send me the input file you were using, so that I can reproduce the problem?
Thanks in advance.

**Comment by hbitteur** [comment]
Any news?

**Comment by hbitteur** [comment]
No news, good news!
Closing the issue
