### ISSUE TITLE
might need to add leptonica-1.73-1.3-linux and tesseract-3.04.01-1.3-linux

### ISSUE THREAD

**Issue by RamKromberg** [Audiveris/audiveris#492]
First off, congrats on the new release! I only run a quick test and I never was more than a casual drive-by user to begin with since I barely do transcription at all let alone OCR ones, but scanning leftovers from past attempts shows better results and the UI feels a bit more responsive somehow though I can't quite point to how.

Anyhow, just wanted to give you a heads up, my system and execution environment is fairly unusual* so I can't be sure, but if other people get "java.lang.UnsatisfiedLinkError: no lept in java.library.path" or "java.lang.UnsatisfiedLinkError: no jnitesseract" on *nixs, they might need to get [leptonica-1.73-1.3-linux-x86_64.jar](https://repo1.maven.org/maven2/org/bytedeco/javacpp-presets/leptonica/1.73-1.3/leptonica-1.73-1.3-linux-x86_64.jar) and [tesseract-3.04.01-1.3-linux-x86_64.jar](https://repo1.maven.org/maven2/org/bytedeco/javacpp-presets/tesseract/3.04.01-1.3/tesseract-3.04.01-1.3-linux-x86_64.jar) in the classpath. 

Anyhow, congrats again and thanks :) Feel free to close the issue once you've looked through it. No reason to keep it open if it's not an issue for anyone else.

\* running nixos, I extract the windows binary, throw together all the jars, and use a hacked together shell script to execute... So, probably just a problem on my end but I figured it won't hurt mentioning ;)

**Comment by hbitteur** [comment]
I don't understand.
These .jar libraries should be automatically pulled as they are declared as dependencies in the "build.gradle" script file.
Could you double check this is not a consequence of your "throwing out all the jars" as you said?

**Comment by hbitteur** [comment]
Also, why do you have to "extract the windows binary" if you are on some unix environment? Please clarify what you did.

**Comment by RamKromberg** [comment]
>These .jar libraries should be automatically pulled as they are declared as dependencies in the "build.gradle" script file.

Good to know but that's for people who have the good sense to build from the source. Personally I'm too lazy* so when it comes to java applications I'll often just download the windows binaries, extract the jars and execute them. With Audiveris this used to work since all I needed to do was reference the conveniently provided shell script for the classpath and I had it working. This time, however, it also required those extra jars.

It's a minor complication in a really esoteric configuration but I figured I should mention it just in case someone runs into a similar problem so they'll have this pop up on their search results instead of trying to figure out the dependencies for themselves.

No need to take any action beyond letting it go on the "closed issues" log. In fact, I'll go ahead and close it myself :D

/* gradle on nixos is such a pain in the ass...

**Comment by hbitteur** [comment]
Sorry. For some reason, it didn't cross my mind that you were working from Windows files to generate your Unix-based target. A bit unusual approach as you said...

This may work or not, depending on what is stored in these .jar which are just containers after all:
- A pure Java program will store its bytecode in .class files, and this bytecode is indeed OS-independent thanks to the JVM layer.
- A hybrid program combines Java bytecode .class with some OS-dependent binary libraries.
 
Audiveris is such hybrid program because it calls Tesseract (and then Leptonica) libraries to process textual elements.
Tesseract / Leptonica are CPP software pieces. Hence the need of .jar files that contain these binary files.

For example, Audiveris Windows installer produces this folder (I'm using cygwin here):
```
$ pwd
/cygdrive/c/Program Files/Audiveris

$ ls -l lib/tes*
-rwxr-x---+ 1 Administrateurs herve   70341 Jun  4 17:21 lib/tesseract-3.04.01-1.3.jar
-rwxr-x---+ 1 Administrateurs herve 1428224 Jun  4 17:21 lib/tesseract-3.04.01-1.3-windows-x86_64.jar

$ jar --list -f lib/tesseract-3.04.01-1.3-windows-x86_64.jar
META-INF/MANIFEST.MF
META-INF/
org/
org/bytedeco/
org/bytedeco/javacpp/
org/bytedeco/javacpp/windows-x86_64/
META-INF/maven/
META-INF/maven/org.bytedeco.javacpp-presets/
META-INF/maven/org.bytedeco.javacpp-presets/tesseract/
org/bytedeco/javacpp/windows-x86_64/jnitesseract.dll
org/bytedeco/javacpp/windows-x86_64/libtesseract-3.dll
META-INF/maven/org.bytedeco.javacpp-presets/tesseract/pom.xml
META-INF/maven/org.bytedeco.javacpp-presets/tesseract/pom.properties
```
lib/**tesseract-3.04.01-1.3.jar** contains just interfacing bytecode. It's the same .jar regardless of the target OS.
But lib/**tesseract-3.04.01-1.3-windows-x86_64.jar** contains the .dll libraries needed under Windows.

In your case, you will need **tesseract-3.04.01-1.3-linux-x86_64.jar** instead of tesseract-3.04.01-1.3-windows-x86_64.jar, and a similar file for leptonica.
Surely, you won't find them among the Windows binaries! :-) You'll have to grab them from the Internet on your own and them refer them in Java classpath, as you did.

Last question: how did you get the Windows binaries? Did you install Audiveris on a Windows machine first (like I did) or were you able to somehow "extract" them from the installer itself (Audiveris_Setup-5.2.1-windows-x86_64.exe)? I'm curious.

**Comment by RamKromberg** [comment]
>it didn't cross my mind that you were working from Windows files to generate your Unix-based target
I'm not. Though funny enough, one time I used that windows 10 Ubuntu-on-Windows thing to build an openwrt image... Worked fine btw in case you're wondering.

>A bit unusual approach as you said...
Yeah but it often enough works that I always try it first since it's less time consuming.

>This may work or not
When it doesn't work I [put together a java development environment](https://gist.github.com/r-k-b/71232a4e0ceacaa15eccd4355781804e) and get the jar built but if I'm unlucky I might end up chasing dependencies of dependencies of dependencies...

>how did you get the Windows binaries?

[Gnome's Archive Manager](https://wiki.gnome.org/Apps/FileRoller) extracted Audiveris_Setup-5.2.1-windows-x86_64.exe fine on my system. But if it didn't, I'd just use wine to install it in some junk profile and get the jars from there.

If you want to see something really scary, check this beast from back when I knew what I was doing: https://github.com/NixOS/nixpkgs/blob/master/pkgs/misc/cups/drivers/mfcj6510dwlpr/default.nix

Makes this quick hack look rather tame :D

**Comment by hbitteur** [comment]
I see.
I have VirtualBox installed on my Windows PC, but haven't used it for 2 years or so.
I let Maxim deal with Linux topics, that's safer for everybody.
Bye
