### ISSUE TITLE
Can't install on Linux: Process 'command 'git'' finished with non-zero exit value 128

### ISSUE THREAD

**Issue by Gobbel2000** [Audiveris/audiveris#5]
I tried installing Audiveris on Kubuntu 16.10. I have installed all needed packages, but after running _gradle build_ or _gradle run_ I get the error message _Process 'command 'git'' finished with non-zero exit value_

This is what _gradle build --stacktrace_ and _gradle build --debug_ returns:

[debug.txt](https://github.com/Audiveris/audiveris-v5/files/819400/debug.txt)
[stacktrace.txt](https://github.com/Audiveris/audiveris-v5/files/819401/stacktrace.txt)

Hope you can fix that !

**Comment by maximumspatium** [comment]
What Git version are you using? Could you run `git --version` in your terminal and post the result here?

**Comment by maximumspatium** [comment]
Did you clone the source with `git clone` or have you downloaded it as ZIP archive?

The latter won't work because our build script queries informations from the Git commit history but this history isn't supplied within the ZIP archive. You need to obtain the sources using `git clone`.

You can test it by changing into the audiveris directory and issuing `git log` in your terminal. In the case of the valid Git repository, you'll get a quite long log. Otherwise, an error...

**Comment by Gobbel2000** [comment]
Git version is 2.9.3.

I did use the ZIP archive and `git log` returned an error :). After cloning the build worked quite far, but at `:test` it crashed again giving the following message:
> Could not open cache directory workerMain (/home/gabriel/.gradle/caches/2.13/workerMain).
       com/tonicsystems/jarjar/asm/commons/SignatureRemapper

However at that point `gradle run` started the programm just fine, so this does'nt really matter much.

Thanks for the quick help and keep up the good work!

**Comment by maximumspatium** [comment]
Hi Gabriel,

you may want to upgrade your (ancient) gradle 2.13 to the latest 3.3 as I recently did for my Ubuntu. After updating, please run `update-alternatives --config gradle` to set the latest version to be the default one.

This could help to get rid of that strange error.

**Comment by Gobbel2000** [comment]
Yup, that worked. Everything seems fine now. 
Thanks again for the advice.
