### ISSUE TITLE
Learning the Editing

### ISSUE THREAD

**Issue by Acapella-1** [Audiveris/audiveris#503]
Actually I'm a smart guy (once tested in top 4%), but there's a good bit of the handbook that I just don't understand. Thus, I have some questions about the program:
  After transcribing, I proceeded to fix some things.  I did observe previously that the absence of a Time Signature causes problems, so I entered one.  My first questions refer to my next action (changing a clef), and the pink measures:
  1. When 'replacing' the Treble clef with the 'Octavo-8' I can't delete the old one - it still shows
  2.  As shown in the attached, many measures are not rhythmically correct, but they're not pink!  Why is that?
  3.  What's the best way to fix those erroneous half notes?
    Thanks for your help.

![Audishot 2021-0715](https://user-images.githubusercontent.com/74429689/125827145-a7050fc4-885b-403c-bcce-0c50616e0fbb.png)

**Comment by hbitteur** [comment]
@Acapella-1 
What do you mean precisely by 'replacing' clef A by clef B? That may be the problem.
From OMR engine point of view, if (**and only if**) the underlying glyph of clef B is the same one as the underlying glyph of clef A, then the engine will delete clef A.
In any other case, there is no reason for the engine to remove clef A, and you'll have to remove it on your own.

Regarding pink measures, this is an output of the rhythm algorithm. A measure is painted in pink when either:
- The start time of a chord could not be determined, or
- A voice in measure ends later than the expected measure end time (which depends on the active time sig).

But a non-pink measure does not imply that measure rhythm is correct...

I'm surprised by the high number of incorrect heads.
Could you make sure that you used the latest release (5.2.2 rather than 5.2.1) because I fixed a head-stem policy in it.

Also, I'm not sure, do you have cue heads in this image? This requires a special processing switch and does not work very well.
Please provide the input image file, so that I can reproduce the transcription process on it?

**Comment by Acapella-1** [comment]
By 'replace' I meant that I deleted the "normal" clef and added the '8' clef.  What's happening now is that the old one is apparently deleted, but there are two '8' clefs, depending on the cursor position, it's either Green or Blue.  
  ( ver 5.2.2:ec28cbfa0 )   
![ThereWil](https://user-images.githubusercontent.com/74429689/125998916-f8d7efc7-73aa-4fae-bf57-2b8e963baa81.jpeg)
  Thanks so much.

**Comment by Acapella-1** [comment]
( Why does it say I closed this?? )

**Comment by Acapella-1** [comment]
Here's a .png  in case it works better
![ThereWil](https://user-images.githubusercontent.com/74429689/126001744-999e4294-19a3-4fba-82e0-3c92261dd3e6.png)

**Comment by hbitteur** [comment]
First staff begins by a treble clef. So why do you try  'replacing' the Treble clef with the 'Octavo-8' ?
On second staff, the F-clef has  not been recognized, so you'll have to insert it manually.
A time signature is needed, so you manually inserted 4/4, which is correct.

But you'll spend much time correcting all the badly recognized heads. This is because the image quality is really poor. You'd better look for a better input image.
Sorry.

**Comment by Acapella-1** [comment]
1.  Okay, I'll consider this a 'lost cause' as you suggest.
2.  The reason for the Octavo Clef is that this song is for male voices, and the 'O'Clef will cause the notes to be played at the pitch they're actually sung.
  As always, thanks for replying.

**Comment by hbitteur** [comment]
On a second thought, problem is not only input quality. I think that note head shapes in this particular image may be rather different from what Audiveris current template matching would expect: they look closer to circle than to ellipsis.

This is a limitation of the template matching approach. Perhaps a different approach, such as the one envisioned for 6.0, would be more tolerant regarding actual head shapes.

But that's not for tomorrow unfortunately
