### ISSUE TITLE
Note sequence generation

### ISSUE THREAD

**Issue by vlajnaya-mol** [Audiveris/audiveris#504]
Hi
I need to get a sequence of notes from an image. I am interested in note name, duration, octave etc. I have already figured out how to work with sheet#N.xml and I am able to determine notes by their location and pitch, but duration has more complex logic and requires to work with multiple relation at a time.
I was wandering if there is a simpler way to do it. Does Audiveris have any more high level way of dealing with a note sequence (using CLI, not GUI)?
Thank you

**Comment by hbitteur** [comment]
@vlajnaya-mol 
Sorry for this late answer, I'm away from home.

All material needed to retrieve note name, duration, octave, etc is available in sheet#N.xml, and this fortunate otherwise there would be no way for Audiveris to reload a .omr project file! :-)
Note duration as you noticed, does not depend only on the note head (or even the head-chord) at hand. It depends on surrounding items such as flags, beams, tuplets. These items can be reached via specific relations.

If I understand your question correctly, you are looking for a way to retrieve all note-related information "directly" from one item found in the .omr file.
There is no such item in the XML file, you will have to play with different related items.
As an example, you could have a look at Audiveris Java code itself, typically class PartwiseBuilder (which generates the MusicXML export file) and especially its processNote() method.
Good browsing!

**Comment by vlajnaya-mol** [comment]
Thank you for your answer, @hbitteur !
