### ISSUE TITLE
rather simple notation scan stops at step "Curves" with NullPointerException

### ISSUE THREAD

**Issue by Bacchushlg** [Audiveris/audiveris#512]
![The Bold Tenant Farmer_2](https://user-images.githubusercontent.com/33522630/134048301-a72fd03b-5330-4d57-8952-64639425913b.jpg)

The transcription of this score stops at step "Curves" with NullPointerException. No idea, why

**Comment by hbitteur** [comment]
NPE occurred because measure 7 has an ending sign but no barline on left side of the measure.
I fixed the exception via commit d861615280e36b86e4a84f03edf721fdf8c234a9 on development branch (please pull).

NullPointerException is now avoided but the ending sign doesn't get exported to the MusicXML data.
I checked MusicXML reference: the ending sign is declared as an element of its barline parent element. In other words: no barline, no ending!!?

So, right now I don't know what to do in Audiveris. I need to search further within MusicXML documentation.

A workaround for you would be to manually insert the ending sign via a music editor like MuseScore. Not very smart, I agree...

**Comment by Bacchushlg** [comment]
Works perfectly now.

**Comment by hbitteur** [comment]
Commit 87ee2d772f8e159870d2952f517d3bbb156a2363 on development branch now allows the user to manually insert a barline on a system side.
