### ISSUE TITLE
Analyze/export only pitch and rhythm XML? 

### ISSUE THREAD

**Issue by ultraGentle** [Audiveris/audiveris#514]
I'm working on the re-synthesis of classical music from score.  

For my purposes, I need only pitches and rhythms/durations, because I'm headed toward audio, not notation.  

(1) Is there a way within Audiveris to omit the steps text, articulation, curves, etc.?

(2) Assuming "no", I'm open to modifying the source for my own purposes, but I could use a pointer where to start and whether this is as straightforward as cutting out some steps here: 

https://github.com/Audiveris/audiveris/blob/6b32341ea870dce9df2a8ef75a732f44a74f0ccc/src/main/org/audiveris/omr/step/Step.java

(3) My rationale for cutting out steps is that (a) I'm imagining this would speed up recognition, and (b) I often get crashes (nullPointerException) on steps that I don't need, so I'm imagining I'd have better success at batch processing.  If my assumptions (a) and (b) are false, please let me know!

If I'm successful, I'd be glad to submit a PR for a "pitch/rhythm only output", but in any case, it would be useful to me.  

Thanks!

**Comment by hbitteur** [comment]
I think some steps could be removed with a bit of work.
You could remove some values in the Step enum type, paying attention to pieces of code where the to-be-removed values are used.
A safer approach would be to keep Stem enum as it is, but rather modify the 'neededSteps' set used by 'reachStep' method in SheetStub class according to your wishes.

But I doubt the result would fit your needs.
- The only lengthy step you could remove is the TEXTS step delegated to TesseractOCR. IIRC this is something to can do without touching the code. The downside would be that real text will be considered for potential musical symbols...
- "Speed up recognition". Yes, but marginally. I say "marginally" because this is just CPU time, not human time. What I mean is that the best way to use Audiveris is to work in 2 phases, first make it transcribe a bunch of files in batch and then interactively check and correct transcribed sheets if needed. Only the interactive (human) time is relevant.
- "NullPointerException". These are bugs that we should chase and fix. Don't be selfish, please fill an issue with related input image, so that we can improve the software.

**Comment by ultraGentle** [comment]
Thanks for the pointer; I was indeed able to skip steps in `batch` mode.  

Separately, it turns out that the Exceptions were being caused by incorrect Tesseract setup, not related to the main point of this issue.  

I would still suggest as a FR to consider a streamline pitch/rhythm mode for use-cases that don't need the other aspects of musical notation.  

But the question is answered for my purposes, so I will close the issue!
