### ISSUE TITLE
How to deal with the sheet of drum-set

### ISSUE THREAD

**Issue by yallien** [Audiveris/audiveris#518]
Thank  u for sharing such a great job.
The results are really good when the input is a sheet of piano.But there are some problems when it comes to the sheet of drum-set.
First,it failed to detected the note head Cross which appear frequently in the drum-set sheet,while I found that you have already defined the noteheadXBlack in OmrShape.(https://github.com/Audiveris/audiveris/blob/master/src/main/org/audiveris/omrdataset/api/OmrShape.java)
also the Issue(https://github.com/Audiveris/audiveris/issues/384) said most of the cross note heads were properly detected.But it did fail to detected them.

What's more,if I want to recognize the sheet of drum-set,I need to train the classfier on the drum-set dataset.Here are my questions.
1.Can I create the dataset (png+xml) and train the classifier just according the https://github.com/Audiveris/omr-dataset-tools?
2.Did it work in the step of Heads and Symbols of the pipeline?(https://audiveris.github.io/audiveris/_pages/main/pipeline/)
3.Is this classifier the so called glyph classifier?
4.After training  how could I use it?

It will be greatly appreciated if you can solved the trouble comfusing me quite a while!

**Comment by hbitteur** [comment]
By default, cross heads are not detected by the OMR engine.
So, make sure to select the "crossHeads" processing switch.
You can do that via the menu `Book | set book parameters`.

FYI, the `OmrShape` is here only to prepare migration to a future 6.0 version with new classifiers: it allows to record samples from processed scores in order to train these new classifiers. It is part of the omr-dataset-tools project which is separate  from audiveris project.
 
Current OMR engine uses the `Shape` type where you can find the `Shape.NOTEHEAD_CROSS` item.
So `Shape` type must be used to populate samples and to train the current glyph classifier.
This is an incremental process, I mean you could start from the current material and augment it with specific samples of yours, and then retrain the classifier.
This process is documented in specific sections of Audiveris handbook:
- [Samples](https://audiveris.github.io/audiveris/_pages/advanced/samples/)
- [Training](https://audiveris.github.io/audiveris/_pages/advanced/training/)

**Comment by hbitteur** [comment]
Have you been able to progress on this topic?

**Comment by yallien** [comment]
thanks for your detailed reply! The detection of cross notehead is successful under your under your guidance.And we now plan to add more data like the "REPEAT" symbol into the dataset to train the glyph classfier.Thanks again for your reply.
