### ISSUE TITLE
Memory leak while transcribing a multi page score

### ISSUE THREAD

**Issue by Bacchushlg** [Audiveris/audiveris#520]
When transcribing a score with many pages (10 in my case) transcription stops from a certain page. The top right memory info field stays at a value above 1000.
Saving the score and restart continues transcription...

version 5.3-alpha (...1288)

**Comment by hbitteur** [comment]
I don't think that reaching 1GB of memory after processing 10 sheets in a row sounds abnormal.
Do you have counter-examples (I mean, compared with a previous Audiveris version)?

Anyway, you can:
- Increase the available memory:
    - Via the maxHeapSize constant (located in build.gradle file, line 49)
    - Via the jvmLineArgs parameter on CLI (I don't precisely remember how, sorry)

- Decrease the memory needs:
    - Work by slices of sheets (remember, you can now select the sheets to process via `Book | Select sheets`) and use menu `Book | Swap book sheets` to interactively swap all sheets except the current one to disk
    - Or save and reload as you did.

**Comment by Bacchushlg** [comment]
I don't talk about the memory needs for transcription, but about a sort of memory leak. Normally, after transcription completed, the needed memory should be rather small. But now, after 10 pages of transcription, the memory info field again is red, even after transcription. 
Therefore I assume a memory leak somewhere...

**Comment by hbitteur** [comment]
Did you press the button located to top right corner ("Run Garbage Collector"), next to the memory meter?
If so, did you observe a memory decrease?

**Comment by Bacchushlg** [comment]
Ahhh..., no I didn't. And yes, this helps (a bit).
Actually I'm working on a 20 page score (but 87 measure over all, so very wide measures).
After garbage collection the memory needed stays at 700 MB. Do you think this is normal?

**Comment by hbitteur** [comment]
Mouais...
What about `Book | Swap book Sheets` ? Please try, it costs you nearly nothing!

**Comment by Bacchushlg** [comment]
Ok, this is the final solution. Would it make sense to automate this when transcription fails due to memory needs?

**Comment by hbitteur** [comment]
Pfff... Never satisfied! :-)

I need to think it over.
This must be doable, though perhaps a bit tricky. 

Flagging this request as enhancement

**Comment by hbitteur** [comment]
Letting the "out of memory" error occur and making the engine automatically react at this moment would be tricky, because at this point in time we don't really know what the current data status and validity are precisely.

FYI, there is already a `-save` option on command line interface. See [this doc section](https://audiveris.github.io/audiveris/_pages/advanced/cli/#-save).
It is effective only in batch mode and saves OMR data at the end of _every successful sheet step_.
You can later re-launch processing on the .omr file and it will continue from the point where it last successfully saved data.
But this option is not meant to save memory, since the preceding sheets are kept is memory. It is meant to save status before any crash in processing (and then let the user/developer later re-launch just the faulty step).

Now, we could use a rather similar approach, this time focusing on saving memory.
For example, a CLI `-swap` option could ask the OMR engine to always swap out the last processed sheet every time it moves to the next sheet to process.

This `-swap` option would be easy to handle in batch mode, certainly less in interactive mode, because of potential conflicts between the OMR engine and the user actions.
Granted, we could "lock" a book while a swap-mode processing is going on, thus preventing the user to work on the same book at the same time. But preventing the user to interactively access a book would appear very similar to a batch mode!

What do you think, my dear end-user? You are in the driver's seat...

**Comment by hbitteur** [comment]
Oops! In fact this "swap for batch" is already implicitly up and running.

If you simply transcribe a long book of sheets **in batch**, then any "just processed" sheet is automatically swapped out.
This is what I discovered by browsing the log file of an 8-sheet score (Maurice Ravel's Pavane). 
And sheet after sheet, the amount of memory used remains stable (about  77MB in my batch example)
I had forgotten this... :-)

The important words here are: **in batch**
Like I said, implementing this for interactive mode would be another story. But I'll investigate.

**Comment by hbitteur** [comment]
I made a few more tests.

The Pavane example is composed as follows:
- Sheets 1 & 2: No music (first sheet is an illustration, second is a blank sheet)
- Sheets 3 through 7: Music
- Sheet 8: No music (just a catalog)

Automatic detection of lack of music results in a StepException, which in batch prevented the actual swap of the sheet.
After a minor code correction, the batch processing remains now stable around 30MB (instead of 77MB as above).

I also modified the code to systematically swap the "just processed" sheet **even in interactive mode**. Just a try!
This time, memory remained stable around 180MB (yes UI needs room compared with batch).
I didn't try to actually **modify** sheets while the transcription was going on, I just browsed among the book sheets from time to time.

Then, back to first sheet, I manually used `Book | Swap book sheets`, this gave 58MB:
![image](https://user-images.githubusercontent.com/22053634/142780500-f2f61471-108f-4ea1-91c2-d4a091fc283f.png)

Then, I moved to all the other sheet tabs (pressing the left arrow key) to reload all sheets from disk, a matter of about 1 second per sheet,  this raised total memory to 222MB:
![image](https://user-images.githubusercontent.com/22053634/142780590-7cf5009a-5fa5-472c-8edb-fa2a0e1cf2da.png)

At this point in time, we could begin the interactive validation and correction of the transcribed sheets.

**Comment by Bacchushlg** [comment]
Sorry for my initial demand - I did not expect to provoke such an effort.
In fact, I assumed that there might be a "real" memory leak that leads to the memory consumption.
I tried your proposal to run book/swap book sheets directly after completion of the transcription (where the last pages were not transcribed...). Unfortunately this did not work, because the pages were not saved to disk before ( ZipFileSystem.open: path is null). 
But as you said: saving and re-open will do the work. And it does not really bother me....

**Comment by hbitteur** [comment]
Just a small trick:
When you have just loaded the image(s) file for the first time, save the book right away before launching any processing.

This will store the book (containing just the sheet stubs, one per image) to disk. You know that.
As a side effect, this will also make the book entity (in memory) remember **where it should be saved from now on**.
And this will avoid your exception ( ZipFileSystem.open: path is null).
Et voilà!

I should more or less transparently automate this trick.

**Comment by Bacchushlg** [comment]
Normally I always do it this way. Because I already start editing the transcription during Audiveris continues with the next pages. And of course I save the book from time to time to save my editing.
But this time I did not want to "disturbe" the transcription with my editing...
Anyway: I don't have a problem with the behaviour, it was just meant as a hint.

**Comment by hbitteur** [comment]
In commit bd507fcb73db912333595b42a27220c04843269e on development branch, you now have the ability to automatically swap out every sheet once it has been processed by the OMR engine.

This feature is:
- Always ON in batch mode.
- OFF by default in UI mode. It can be set via:
    - the new `-swap`  option available on CLI interface, to  be effective only for the current session
    - the new constant `BookActions.swapProcessedSheets` available in `Options` menu to be effective for any session from now on, until constant is reset.

**Comment by Bacchushlg** [comment]
works perfect also for my 20 page try-out score now.

**Comment by hbitteur** [comment]
For the sake of completeness, if you need to increase your maximum memory, you can for example use this on the command line:
>  ./gradlew -PjvmLineArgs="-Xmx2g" run

This will set the limit to 2GB instead of the default 1GB.
