### ISSUE TITLE
Issues with a symphony score [Kospoth Sym. C, 2nd Mvmt]

### ISSUE THREAD

**Issue by hmmueller** [Audiveris/audiveris#524]
### Discussed in https://github.com/Audiveris/audiveris/discussions/523

<sup>Originally posted by **hmmueller** November 27, 2021</sup>
I omr'ed 4 scans (of modern scores) of movements of a symphony by O.C.E.v.Kospoth. I saw a few things that might be of interest here (measure numbers are from the input PDF - because of non-omred pages, the mxl has fewer measures):

a) There are two types of log messages with ArrayIndexOutOfBoundsException:

[Scannen0017#2] Could not compute impacts for beam {item median:(147.0,3.9)-(1257.0,4.7) height:8.6} ex: java.lang.ArrayIndexOutOfBoundsException: Index -2402 out of bounds for length 8952088

and a little later (but seems to be an inherited error):
 
[Scannen0017#2] Error in performing [LOAD, BINARY, SCALE, GRID, HEADERS, STEM_SEEDS, BEAMS, LEDGERS, HEADS, STEMS, REDUCTION, CUE_BEAMS, TEXTS, MEASURES, CHORDS, CURVES, SYMBOLS, LINKS, RHYTHMS, PAGE] java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.lang.ArrayIndexOutOfBoundsException: Index -2402 out of bounds for length 8952088
 
b) On some pages, Audiveris "gives up" - here, e.g. page 2.
 
c) Recognition of triplet "3s" is somewhat "spurious" (see e.g. m.9). Can this be improved by changing some options?
 
d) Also, some bar lines are overlooked (e.g. between m.26 & 27).
 
e) Unfortunately, the score contains dotted slurs (added by an editor) - parts of these are "recognized" as staccato dots.

Here is a ZIP with PDF, OMR, MXL and log:
[Scannen0017.zip](https://github.com/Audiveris/audiveris/files/7611791/Scannen0017.zip) 

(I know this is a "list of issues". But I'm not sure which of these are "as designed" - e.g. the "dotted slurs not recognized"? -, so I wanted to start with this list; separating out single issues for detailed discussion is of course ok with me!).

H.M.</div>

**Comment by hbitteur** [comment]
You are right, a "list of issues" is not the most convenient way to handle and share the cases.
Separate problems should be addressed by separate issues.
One at a time, please :-)

Getting back to your very first problem (some beams not recognized), I can confirm that the root cause is that the same "beam glyph" led to 2 separate mutually exclusive interpretations one as "(full) beam" and one as "beam hook".
For some reason, the full beam could not get connected on both horizontal sides, was thus flagged as abnormal and then discarded.

If you are in a hurry, a quick workaround is to go to `Tools | Options` menu and there search for BeamsBuilder unit and its "maxHookWidth" constant which is set to 2.0. Simply change this value for 1.7 and you are gone (relaunch processing from the beginning). With this new value, your short beams won't be mistaken for beam hooks.

Please keep in mind this is just a workaround, that works for your example score.
A true fix should follow ASAP...

**Comment by hmmueller** [comment]
Original beam issues answered - thanks. And I close this and create separate issues.

H.M.
