### ISSUE TITLE
ArrayIndexOutOfBoundsExceptions abort sheet OMR (issues with score of Kospoth's Sym. C, 2nd Mvmt)

### ISSUE THREAD

**Issue by hmmueller** [Audiveris/audiveris#525]
There are two types of log messages with ArrayIndexOutOfBoundsException:

[Scannen0017#2] Could not compute impacts for beam {item median:(147.0,3.9)-(1257.0,4.7) height:8.6} ex: java.lang.ArrayIndexOutOfBoundsException: Index -2402 out of bounds for length 8952088

and a little later (but seems to be an inherited error):

[Scannen0017#2] Error in performing [LOAD, BINARY, SCALE, GRID, HEADERS, STEM_SEEDS, BEAMS, LEDGERS, HEADS, STEMS, REDUCTION, CUE_BEAMS, TEXTS, MEASURES, CHORDS, CURVES, SYMBOLS, LINKS, RHYTHMS, PAGE] java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.lang.ArrayIndexOutOfBoundsException: Index -2402 out of bounds for length 8952088

The exceptions abort the recognition process so that these pages are completely missing from the score. However, when the score is exported as MXL, there is no indication that these pages are missing, which is somewhat confusing (but ok: Exporting a score with red sheets is probably "on your own risk").

Files (pdf, omr, log, mxl): [Scannen0017.zip](https://github.com/Audiveris/audiveris/files/7612007/Scannen0017.zip)

H.M.

**Comment by hbitteur** [comment]
The exception occurred in BEAMS step on sheet 2, for a beam candidate stuck to the upper border of the image.
In fact you can notice a long and thick black line at the very top of the image.
This is where the engine tries to recognize a beam, we cannot blame it for this! :-)

In fact, the computed bounds for this beam (id: 1247, if you want to check by yourself) are as follows:
- x: 147
- **y: -1**   <--- PB here
- width: 1110
- height: 11

The problem comes from the y negative value. When retrieving the pixels in order to build the underlying glyph, the OMR engine tries to retrieve pixels at ordinate '-1' in the image array of pixels (which starts at ordinate 0).
Hence the exception.

I need to fix the code to stay safely away from this limit.
Stay tuned.

**Comment by hbitteur** [comment]
Bug fixed in commit d71e9d75e0265ea764793affe7afd2c3f188c638 on development branch

**Comment by hmmueller** [comment]
Actually, I did not look "up there", but now that you tell us ... That's what happens with real scans :-) Thanks!

(I currently dont have the build environment in place for building the development branch - I want to concentrate on music things right now, being a software engineer I have enough software engineering during the week ... I'll set up something "in the near future" to try out the development branch, but I trust you that it works).

H.M.

**Comment by hmmueller** [comment]
... and thus, I close it.
