### ISSUE TITLE
Error in performing [SCALE, GRID, ... RHYTHMS, PAGE] java.util.concurrent.ExecutionException: java.lang.NullPointerException

### ISSUE THREAD

**Issue by npostavs** [Audiveris/audiveris#579]
Audiveris seems to hit some internal error when processing certain pages of this [Schubert string trio score from IMSLP](https://imslp.org/wiki/String_Trio_in_B-flat_major,_D.581_(Schubert,_Franz)#IMSLP552832).

Page 3 is the first failing page: [D_581-page3.pdf](https://github.com/Audiveris/audiveris/files/8875664/D_581-page3.pdf), page 7 also fails.

A common property of those pages is beamed eighth groups over the bar line. I tried seeing if I could trigger the error with a simple Lilypond score using that funny beaming style. And I managed to get a similar error with this:
```
\version "2.22"

\new GrandStaff <<
\new Staff { \relative c'' {
  c1 c1 c1 % Need two parts, so that Audiveris can recognize the barlines
}}
\new Staff { \relative c'' {
  d2. r8 d[ | e c] r e[ g e] r e[ |
  d8 b] r4 r2 \bar "|."
}}
>>
```

Corresponding .omr for the Lilypond fragment: [beam-over-bar.omr.zip](https://github.com/Audiveris/audiveris/files/8875706/beam-over-bar.omr.zip)

The error looks like this:
```
[beam-over-bar] Error in performing [SCALE, GRID, HEADERS, STEM_SEEDS, BEAMS, LEDGERS, HEADS, STEMS, REDUCTION, CUE_BEAMS, TEXTS, MEASURES, CHORDS, CURVES, SYMBOLS, LINKS, RHYTHMS, PAGE] java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.lang.IndexOutOfBoundsException: Index 2 out of bounds for length 2
```

**Comment by hbitteur** [comment]
@npostavs 
You did not mention which Audiveris version you are using.
I just tried your 2 examples with the latest development version at hand. It does not raise exceptions on these examples, but has problems in the locations where a beam crosses a barline within staff height.

Either the barline is not recognized (in your small example) or the beam is not recognized as a valid beam when it crosses barline (as between measures 47 & 48 of the large example) or, even worse, when a beam crosses system boundaries as between measures 50 & 51.

For Audiveris, a barline item is the _vertical line portion limited by staff height_. Barlines from different staves can be connected by so-called _connectors_.

From current Audiveris point of view:
- A beam can extend beyond a measure to the next one in the same system, **provided it does not cross the barline** (remember, barline is limited to staff height, hence you can pull the beam above or below the staff).
- A beam cannot, like a slur, be **cut into 2 portions**, one in a system and the other one in the next system.
- A barline (in Audiveris sense) **cannot be overlapped** with other items, otherwise the barline is not recognized as such.

Except the IndexOutOfBoundsException (that I couldn't reproduce), I don't consider these cases as Audiveris "errors" but rather abnormal constructions in the score itself.
I guess you cannot rewrite the score which you downloaded from IMSLP, but you can use Audiveris editor to manually modify the beams involved. After all, it's just a matter of a few minutes.

**Comment by npostavs** [comment]
> You did not mention which Audiveris version you are using.

Oh sorry, it's 5.2.5, the latest release.

> Except the IndexOutOfBoundsException (that I couldn't reproduce), I don't consider these cases as Audiveris "errors" but rather abnormal constructions in the score itself.

Yes, agree, if Audiveris has a bit of trouble transcribing those bars it's not a big deal, but I failed to get anything at all for those whole pages with the release version. I will try with the latest development version.

**Comment by npostavs** [comment]
Okay, I can confirm the development branch doesn't bail out with that error.
