### ISSUE TITLE
Confusing glyph naming of mordents

### ISSUE THREAD

**Issue by RensBloom** [Audiveris/audiveris#598]
![image](https://user-images.githubusercontent.com/5883286/203275359-8b2bdaf2-61b3-4c8a-bd1d-5a27c7acbb27.png)
While doing some sampling, I was surprised to find the namings 'Mordent' and 'mordent inverted' swapped.
I must reckon that the English naming is a bit confusing. The upper mordent is called now 'mordent', but used to be called 'praltriller'. The lower mordent is called now 'inverted mordent' but used to be called 'mordent'.  See [Wikipedia](https://en.wikipedia.org/wiki/Mordent).
I see that the musicXML export goes well if I select the correct symbol (with incorrect naming).

I'll propose a pull request if you agree to this naming change in the code.

**Comment by RensBloom** [comment]
I see that [MusicXML](https://www.w3.org/2021/06/musicxml40/musicxml-reference/elements/inverted-mordent/) has the namings swapped. Can I propose to use MORDENT_UPPER and MORDENT_LOWER for Audiveris?

**Comment by hbitteur** [comment]
I don't know who is right.

Yesterday night I pushed  commit 09112de37850944b54cf11ed2787ba39add169b7 on "multifont" branch.
It implements the multi-font Audiveris version I told you about. It may still have bugs but you can pull and use it on your own right now.
To change default/book/sheet musical font, use the `Book | Set book parameters` pull-down menu which now provides a font-selection spinner.

While working on this version, I noticed that font codes for MORDENT and MORDENT_INVERTED had been swapped. I think this was my mistake. They are now OK for the 3 font families available (Bravura, FinaleJazz and MusicalSymbols).
Please check on your own with this new version: the names and shapes that appear in dialogs like the glyph classifier should be correct.

Back to your initial question, I prefer to stick with MusicXML and SMuFL names if at all possible.
So, rather than MORDENT_UPPER and MORDENT_LOWER, let's keep MORDENT and MORDENT_INVERTED.

The problem is to know which is which:
- On [SMuFL site](https://www.smufl.org/version/latest/range/commonOrnaments/), the [mordent](https://www.smufl.org/version/latest/glyph/ornamentMordent/) glyph has no vertical bar, while [mordentInverted](https://www.smufl.org/version/latest/glyph/ornamentMordentInverted/) exhibits the vertical bar.
- On [MusicXML site](https://www.w3.org/2021/06/musicxml40/musicxml-reference/elements/), it's the **opposite**: [mordent](https://www.w3.org/2021/06/musicxml40/musicxml-reference/elements/mordent/) has a vertical bar and [inverted-mordent](https://www.w3.org/2021/06/musicxml40/musicxml-reference/elements/inverted-mordent/) has none.

I'm ready to swap again, if needed. But who is right? I need your help.

**Comment by hbitteur** [comment]
According to Wikipedia, SMuFL is right, MusicXML is wrong

**Comment by RensBloom** [comment]
I now have succesfully managed to build Audiveris myself from the development branch. It is correct now.

**Comment by RensBloom** [comment]
I didn't check the musicXML output, which was incorect. I have sent a pull request.
