### ISSUE TITLE
faulty detection of PED items

### ISSUE THREAD

**Issue by Bacchushlg** [Audiveris/audiveris#606]
[Hasta El Dia Del Regreso.pdf](https://github.com/Audiveris/audiveris/files/10365820/Hasta.El.Dia.Del.Regreso.pdf)

A couple of transcriptions that I did with the latest version detected multiple "Ped." items within the score. 
I don't see a systematic within these detections. Mostly it happens at chord texts, but not only

**Comment by hbitteur** [comment]
I confirm that at end of LINKS step on your example, there are still 4 PED symbols. The problem is that all of them have a contextual grade lower than 0.5, and so they should be discarded by the reduction performed at end of LINKS step.
I need to further investigate.

**Comment by hbitteur** [comment]
Strange. The reduction performed at end of LINKS step does resolve conflicts but does not remove weak inters ( as opposed to the REDUCTION step performed earlier).
And this has been so for ever! As far as I can go back in source history for this class, (August 2014) the weak inters were not removed.

I can change this, and ask the links reduction to purge the weak inters. This will remove all these PED false positives, but at the expense of killing all remaining inters with similar weak grade.

**Comment by hbitteur** [comment]
So, I just fixed this "bug", that has been around for some 8 years. I still don't understand: it's more a design flaw than a bug. What would be the purpose of keeping weak inters alive?

Also, I noticed a few problems when running latest Audiveris development on this particular score:
- Some easily recognized symbols, like a quarter rest, were not detected
- A couple of black heads were mistaken for void heads. It's true that template matching was modified recently.
- Many slurs have been badly detected. There is indeed a problem with slurs.

So, stay tuned. I need to work on this.

**Comment by hbitteur** [comment]
I just pushed a bunch of commits, please pull "development" and rebuild.
- Reduction in LINKS step now discards weak inters
- Slightly improved training of glyph classifier (but some "Ped" false positives still remain in the score at hand)
- Bug fix resulting in no-detection of head-stem connection (some black heads got discarded in favor of void heads)
- Bug fix for precise display of flat-based symbols (resulting in display of flat-based keys shifted downwards)
- Bug fix resulting in abnormal symbol sizes. Small cause, big effect. This resulted in no-detection of many slurs because the vicinity of every head was 4 times bigger than it should have been, thus "erasing" the slur pixels found "too near" a note head.
- First improvements on filtering OCR outputs. A work in progress.

Thanks for pointing out defects encountered with latest development version. This new one should be better.

**Comment by Bacchushlg** [comment]
Perfect improvement!
Slurs are almost all detected now - even in mid-quality images, and within the notation lines.
The few faulty Peds are no problem - and better than loosing other symbols (it always easier to remove a faulty item than add one missing)
