### ISSUE TITLE
wrong notation scaling for bad quality score

### ISSUE THREAD

**Issue by Bacchushlg** [Audiveris/audiveris#609]
![Let me Live](https://user-images.githubusercontent.com/33522630/212110616-f7f9554e-091a-4f4e-a698-6117a9d64ce8.jpg)

For some curious reason the note heads of this score are detected as too small - leading to a problem with proper positioning of the heads in many case. Also heads below the score are detected as head with aug. dot.

**Comment by hbitteur** [comment]
In the image at hand, interline value is 14 pixels.
Accordingly, a black head template will be scaled so that its height is 14 pixels.
The problem is that, in this image, black heads exhibit a height of 19 pixels. This is way too big.

Such a difference willl have 2 consequences:
- Head detection, based on regularly scaled templates, will not work correctly
- Detected heads will appear as rather small (with a ratio of 14/19 of their original size in image)

**Comment by hbitteur** [comment]
Please pull from development branch.
I just pushed commit 4e5381ad726357eb8d23d9539922dda18ade5e19 which will allow you to effectively use a non-standard head size.

To use a non-standard head size, go to menu `Tools | Options` and modify the constant `MusicFont / headRatio` from 1.0 (standard value) to 1.35 (your 19/14 ratio).

You will however notice a side effect: many void heads on stems, that survive the REDUCTION step.
To better filter them out, go to menu `Tools | Options` and modify the constant `HeadStemRelation / headSupportCoeff` from 4.0 to 1.5

This is just a trick. So, when you are done with this non-standard image, you should reset the modified constants to their original value...

**Comment by Bacchushlg** [comment]
Lets forget about this... It seems that the score has been created with a curious notation system that is not conform to normal notation rules.
