### ISSUE TITLE
Put OMR on server to access with an API

### ISSUE THREAD

**Issue by nrigoni22** [Audiveris/audiveris#612]
It's possible to put the OMR on a server and send the PDF to get back the XML file?

**Comment by hbitteur** [comment]
Certainly.
IIRC, someone already started this kind of service. You should get more information by searching this forum.

The main drawback is that transcription will run unattended, therefore, you will get raw OMR output. Unless the input image is of very high quality, chances are you will have to manually inspect and correct this OMR output.

At the end of the day, you are only delegating the running of OMR  engine on a remote server, rather than on your own computer. You could as well run the transcription of a bunch of input images on your own computer, late at night for example, and get the raw OMR material some time later, for example the day after.

OMR engine processing time is just CPU time. What really counts is the human time, that is the time you spend verifying and correcting the OMR material to finalize the transcription

**Comment by hbitteur** [comment]
Closing this topic.
