### ISSUE TITLE
Quarter rests not detected properly

### ISSUE THREAD

**Issue by Sbte** [Audiveris/audiveris#619]
I'm trying to convert some tuba parts from bass to treble clef, and audiveris seems to do a great job, detecting everything correctly, except for quarter rests.

This is one bar of the music I'm trying to convert

![wenn3](https://user-images.githubusercontent.com/454803/218251690-d651d4ae-04b8-4451-b705-ede6573e04ef.png)

And this is the result in audiveris. It looks pretty good, except that it doesn't recognise some of the quarter rests. The one highlighted in red has a glyph classifier score of 0.8725, so I'm not sure why it's not recognised.

![wenn4](https://user-images.githubusercontent.com/454803/218251698-9a6b56be-1666-4c44-9552-ce0e3d4d3855.png)

Now it I import it in Musescore, it looks horrible. It seems to think that the quarter rests are for a different voice? Maybe because the rests are positioned slightly higher than usual?

![wenn5](https://user-images.githubusercontent.com/454803/218251703-6eb8c93f-6fef-4b44-80bd-de59422609cb.png)

If anyone has any suggestions on what I can tune to work around this (like letting it know there is only one voice, or letting it know there are 4 quarters per measure, or letting it know the quarter rests are positioned slightly higher), or what I can do to fix the bug if there is one, that would be appreciated.

**Comment by hbitteur** [comment]
@Sbte 
The root cause is the fact that chords in this score are too close abscissawise.
The OMR engine cannot reliably dispatch chords in separate time slots with the default settings.

Let's take the example of measure 5 (assuming the last quarter rest in this measure has been manually set). 
We have 4 chords in this measure:
1. a quarter note
2. a quarter rest
3. a quarter note with a higher pitch position
4. a quarter rest

Chords number 3 and 4  are so close abscissawise that they are considered as being part of the same time slot (the logic is a bit more complex than this, but you get the idea).
So, from chord 2, which chord from the next slot will better match chord 2 (chord 3 or chord 4)? The answer is chord 4.
And thus chord 3 will be left over and start a new voice.

The solution to circumvent this is to be more strict on abscissa separation into time slots.
This is governed by the contant SlotsRetriever / maxSlotDxHigh which is by default 1.1 interlines (i.e. 21 pixels in this image).
So, using menu `Tools | Options`, you can change the constant `SlotsRetriever / maxSlotDxHigh` from 1.1 to 0.7 (i.e. 13 pixels in this image).
With this narrower definition, your image gets correctly processed.

![image](https://user-images.githubusercontent.com/22053634/221251044-3cc14f71-e054-4e4a-9f88-0f41a2a623de.png)
CAVEAT: Don't forget to undo this trick when you are done and move to more "civilized" images.

**Comment by Sbte** [comment]
@hbitteur That works much better, thanks! Marking the remaining rests manually is not that much work, so this will greatly speed up my workflow.

Feel free to close this issue if you do not want to keep it open for improving the detection of the remaining rests.
