### ISSUE TITLE
unable to add barlines correctly for merging systems

### ISSUE THREAD

**Issue by Bacchushlg** [Audiveris/audiveris#629]
![Canada in Springtime 8](https://user-images.githubusercontent.com/33522630/223489093-66c6dc74-7352-41e9-a3dc-f759a3f6c0ac.jpg)

In this (rather bad) image the bar lines are not correctly detected (no wonder...)
When trying to add the necessary bar line in the piano system the rhythm detection gets completely disordered:

![Clipboard 1](https://user-images.githubusercontent.com/33522630/223489972-eef134b2-5d10-4060-ad54-9891e1c442d2.jpg)

**Comment by Bacchushlg** [comment]
[Canada in Springtime.zip](https://github.com/Audiveris/audiveris/files/10950242/Canada.in.Springtime.zip)

I append my complete score for analysis. I tried to export the score page by page to save at least the good detected parts. Unfortunately I get an index out of bounds exception each time... :-(

**Comment by hbitteur** [comment]
I tried the first image (WithTheMorning...), just until the GRID step.
[This is the best step to correct missing barlines because **we don't have yet measures** to get in our way.]
And we got a lot of them.

Here is what I did:

1/ Merge all the systems that needed to be merged. For example, the first 4 staves were grouped in one system with 2 staves followed by 2 separate staves, resulting wrongly in 3 systems. So, I merged system 2 (staff 3) with system 3(staff4) and then system 1 (staves 1+2) with the new system 2 (staves 3+4).
I performed similar merges for the other systems in the page, to come up finallly with 3 systems of 4 staves each.

2/ I adjusted the left side of staff 3 and staff 4, using popup menu in each of these staves and selecting Staff | Edit staff. I dragged the left-most handled until the staff left abscissa got properly aligned. Same thing for other misaligned staves further below.

3/ I addressed the missing barlines by first **removing the existing** barlines and then manually inserting a barline (simple or double) at proper location. While doing this, you get prompted about **performing this barline insertion for the whole system height**, this is the key point.

4/ I finally inserted brackets and braces where needed.

Et voilà!
Here is the resulting .omr file: 
[WithTheMorning.zip](https://github.com/Audiveris/audiveris/files/10951668/WithTheMorning.zip)

**Comment by hbitteur** [comment]
"Canada in Springtime" has nothing to do with "WithTheMorning", or am I missing something?

Loading Canada..., I get an error message: 
Error in class org.audiveris.omr.sheet.rhythm.Measure afterReload() java.lang.IllegalStateException: Part Barline with no proper StaffBarline
Perhaps, this is related to some barline deletion or insertion you have made? Could you confirm?

**Comment by Bacchushlg** [comment]
I just tried to open the appended omr File. Unfortunately I get:

Error in LoadBookTask java.lang.NumberFormatException: For input string: "3-beta"

Maybe a problem due to the dammed problem that in Germany decimal numbers use "," instead of "."?

**Comment by Bacchushlg** [comment]
concerning your last question: with the morning is page 6 of canada...

And yes: I get the same error message when re-loading the omr file

**Comment by hbitteur** [comment]
The very first element in this book.xml is:
```xml
<book software-version="5.3-beta" ...
```
Is this the problem you encountered? If so, you would get the same problem with CanadaInSpringtime.
Could you make sure, with a `git pull --all`, that you do have the latest development version

**Comment by hbitteur** [comment]
> Maybe a problem due to the dammed problem that in Germany decimal numbers use "," instead of "."?

What is the locale you use in Audiveris? IIRC, it is by default set to US, unless the end-user modifies this explicitly (by modifying an application constant)

**Comment by hbitteur** [comment]
Could we sort out the problem of NumberFormatException first.

Then, we'll address the questions of barline insertion.

**Comment by Bacchushlg** [comment]
concerning NumberFormat... ok, no problem.

I have just checked: I already used the latest version.

**Comment by hbitteur** [comment]
> Loading Canada..., I get an error message:
> Error in class org.audiveris.omr.sheet.rhythm.Measure afterReload() java.lang.IllegalStateException: Part Barline with no proper StaffBarline

This corresponds to the first sheet, last system, staff 11, very first measure.
This measure has no starting barline, whereas the corresponding measures in the other parts of the same system have such a left barline.

In other words, the last part of this system has 2 staves (linked by a brace). The first staff has no starting barline while the second staff has a starting barline.
And a "PartBarline" is supposed to have a corresponding StaffBarline in each of the part staves.

**Comment by hbitteur** [comment]
> concerning NumberFormat... ok, no problem.

So, where does this message about NumberFormat come from? Could you have a look at the stack dump in the program output.

**Comment by Bacchushlg** [comment]
does this help?

INFO  []                      Book 2844 | Loading book E:\Users\Baruch\Documents\Audiveris\canada in springtime\Canada in Springtime.omr
WARN  [Canada in Springtime#1]                   Measure 482  | Error in class org.audiveris.omr.sheet.rhythm.Measure afterReload() java.lang.IllegalStateException: Part Barline with no proper StaffBarline
java.lang.IllegalStateException: Part Barline with no proper StaffBarline
        at org.audiveris.omr.sheet.PartBarline.getRightX(PartBarline.java:209)
        at org.audiveris.omr.sheet.rhythm.Measure.getAbscissa(Measure.java:658)
        at org.audiveris.omr.sheet.rhythm.Measure.getLeft(Measure.java:996)
        at org.audiveris.omr.sheet.rhythm.Measure.filter(Measure.java:550)
        at org.audiveris.omr.sheet.rhythm.Measure.afterReload(Measure.java:457)
        at org.audiveris.omr.sheet.Part.afterReload(Part.java:307)
        at org.audiveris.omr.sheet.SystemInfo.afterReload(SystemInfo.java:358)
        at org.audiveris.omr.sheet.Sheet.afterReload(Sheet.java:393)
        at org.audiveris.omr.sheet.SheetStub.getSheet(SheetStub.java:973)
        at org.audiveris.omr.sheet.ui.StubsController.checkStubStatus(StubsController.java:274)
        at org.audiveris.omr.sheet.ui.StubsController.lambda$display$1(StubsController.java:354)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
INFO  [Canada in Springtime#1]                 SheetStub 982  | Loaded /sheet#1/sheet#1.xml
<==========---> 83% EXECUTING [1m]

**Comment by hbitteur** [comment]
No, is does not help!!! :-)
This stack dump corresponds to the case I reported (PartBarline without all the needed StaffBarline's).

We need the dump corresponding to:
> Error in LoadBookTask java.lang.NumberFormatException: For input string: "3-beta"

**Comment by Bacchushlg** [comment]
ok sorry...

Curious, I get a different message this time... Loading works fine, but I cannot transcribe, it stays in step GRID

INFO  []                      Book 2844 | Loading book E:\Users\Baruch\Downloads\WithTheMorning\WithTheMorning.omr
WARN  [WithTheMorning]                SystemInfo 378  | Error in class org.audiveris.omr.sheet.SystemInfo afterReload() java.lang.IndexOutOfBoundsException: Index 4 out of bounds for length 3
java.lang.IndexOutOfBoundsException: Index 4 out of bounds for length 3
        at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
        at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
        at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
        at java.base/java.util.Objects.checkIndex(Objects.java:359)
        at java.base/java.util.ArrayList.get(ArrayList.java:427)
        at org.audiveris.omr.score.Page.getRef(Page.java:506)
        at org.audiveris.omr.sheet.SystemInfo.getRef(SystemInfo.java:1000)
        at org.audiveris.omr.sheet.SystemInfo.afterReload(SystemInfo.java:322)
        at org.audiveris.omr.sheet.Sheet.afterReload(Sheet.java:393)
        at org.audiveris.omr.sheet.SheetStub.getSheet(SheetStub.java:973)
        at org.audiveris.omr.sheet.ui.StubsController.checkStubStatus(StubsController.java:274)
        at org.audiveris.omr.sheet.ui.StubsController.lambda$display$1(StubsController.java:354)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
WARN  [WithTheMorning]                     Sheet 432  | Error in class org.audiveris.omr.sheet.Sheet afterReload() java.lang.IndexOutOfBoundsException: Index 4 out of bounds for length 3
java.lang.IndexOutOfBoundsException: Index 4 out of bounds for length 3
        at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
        at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
        at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
        at java.base/java.util.Objects.checkIndex(Objects.java:359)
        at java.base/java.util.ArrayList.get(ArrayList.java:427)
        at org.audiveris.omr.sheet.Part.getRef(Part.java:935)
        at org.audiveris.omr.sheet.Sheet.checkPartIds(Sheet.java:501)
        at org.audiveris.omr.sheet.Sheet.afterReload(Sheet.java:403)
        at org.audiveris.omr.sheet.SheetStub.getSheet(SheetStub.java:973)
        at org.audiveris.omr.sheet.ui.StubsController.checkStubStatus(StubsController.java:274)
        at org.audiveris.omr.sheet.ui.StubsController.lambda$display$1(StubsController.java:354)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
INFO  [WithTheMorning]                 SheetStub 982  | Loaded /sheet#1/sheet#1.xml
<==========---> 83% EXECUTING [12m 51s]

**Comment by hbitteur** [comment]
I have to leave you now, Sorry.
Back to this problem tomorrow.

**Comment by Bacchushlg** [comment]
I just tried to play with the Scaling Data Parameters, as I detect the major problem during transcription in the rather bad detection of the bar lines. (To be honest I don't understand, why it is so bad, because the bar lines are rather good visible - my initial idea was to improve the bar lines in the image sources...)

Which parameter might help to improve the detection?

**Comment by hbitteur** [comment]
There were bugs related to the systems merge that originated in the new handling of logical/physical parts. Just fixed.
There are other bugs related to the manual insertion of barlines, I'm trying to sort them out.
Then, I'll address this question of poor barline detection.
Stay tuned...

**Comment by hbitteur** [comment]
I just pushed commit a6bbc10ee41d5fa2c812e8350974797a918267f4 to fix problems with system merge and with manual insertion of barlines.
As an example, I'm appending result on WithTheMorning image, There are still some manual corrections to perform because the input is really poor.
[WithTheMorning.zip](https://github.com/Audiveris/audiveris/files/10983462/WithTheMorning.zip)

I will now try to improve engine barline detection, but I don't have high expectations regarding the image at hand...

**Comment by hbitteur** [comment]
Good news!
You will have to modify 2 constants (via `Tools | Options` menu), in StaffProjector class:
- chunkThreshold set to 2.5 instead of 0.45
- minDerivativeRatio set to 0.2 instead of 0.4

Restart the program and run the GRID step.
All your barlines, systems, braces, ... are correctly recognized!
A miracle!

**Comment by hbitteur** [comment]
The rather good results -- at least on barlines -- for this poor-quality input deserve some explanations.

NOTA: Keep in mind that these results were achieved thanks to the "twisting" of some key parameters. Those parameter values should be limited to this kind of input, they might lead to collateral damages on other inputs.

Let's have a look at this particular input (image is shown at the top of this issue).

Barlines are detected in GRID step using peaks in vertical projection of pixels read within staff height.
A (barline candidate) peak must:
1. Be sufficiently high (the number of cumulated pixels must be close to the staff height)
2. Have a steep left side and a steep right side. This requires a high absolute value for the "derivative" of cumul values on left and right sides of the peak.
3. Have no significant chunks in the close neighborhood (typically in a width of 2 pixels on left and right sides of the peak).
4. Plus other safety checks not developed here.

See the problem at beginning of staff 3:
![image](https://user-images.githubusercontent.com/22053634/225580914-ce575a97-6c75-4972-a61b-86613c755371.png)
The treble clef is totally stuck to the barline.
Criteria 1 is OK, but 2 and 3 are not.
Hence the need to strongly modify their thresholds so that the checks get OK.

If you are curious, you can have a look at this staff projection. Use a right-click within staff 3 and in the popup menu select `Staff projection`. (You have to activate the PLOTS options in the `Tools | Advanced topics` for this feature to be visible).

With the original values, the staff projection for staff 3 looks like this:
![image](https://user-images.githubusercontent.com/22053634/225588440-f5660063-6b51-4f31-b73f-79c141d3928e.png)
Note:
- The longer arrow points to the horizontal yellow line which represents the maximum acceptable chunk on peak side. Cumul values (in red) are far above this threshold.
- The shorter arrow points to the minimum value (in absolute) for peak side derivative, displayed in green. Derivative on right side of the peak is not sufficiently negative.

![image](https://user-images.githubusercontent.com/22053634/225592580-80323079-4b46-4ed5-8a3b-708c23088e4a.png)

Many barlines are not detected, some brackets are mistaken for barlines.
This results in artificial staff indentations and thus false page breaks.

![image](https://user-images.githubusercontent.com/22053634/225593461-a29008a2-582e-420f-a1ef-9b247de6b7d1.png)


With the twisted values, projection for the same staff 3 are now like:
![image](https://user-images.githubusercontent.com/22053634/225589804-34c809e9-d81e-430f-9256-45a404921234.png)
Cumul values and derivatives are the same as before (of course) but the thresholds for chunk (in yellow) and for derivative (in green) have been sufficiently translated.

Here is the sheet at end of GRID step:

![image](https://user-images.githubusercontent.com/22053634/225591669-bfaadb7c-7196-4c72-ac13-38077b94bb49.png)

All systems are OK in one page:

![image](https://user-images.githubusercontent.com/22053634/225594457-a7f5f606-8cdf-411f-aeee-20a223c179f1.png)

Some staff lines are warped at beginning of staves 3 and 4.
We can manually correct this via `Popup | Staff | Edit lines`, but this is another story. :-)

**Comment by Bacchushlg** [comment]
Wow, I did not think that the algorithm is that sophisticated...
...and I am happy about this much better recognition of the measures now.

Unfortunately I stick to the next problem: I have removed the 4th page from the score (it was really unreadable) using the split-and-merge function and wanted the continue with the following pages.
But now, I get:
"Error in mouseReleased java.lang.NullPointerException: Cannot invoke "org.audiveris.omr.score.Score.getLogicalParts()" because the return value of "org.audiveris.omr.score.Page.getScore()" is null"
each time I press the right mouse button.

[Canada.zip](https://github.com/Audiveris/audiveris/files/11010476/Canada.zip)

**Comment by hbitteur** [comment]
I just checked. When I remove sheet 4 in your Canada example, indeed  the `score` element no longer exists in the resulting .omr file. No doubt, it's a bug! :-(
Stay tuned...

**Comment by hbitteur** [comment]
@Bacchushlg 
To be able to manage logical and physical parts, the program needs to keep track of sheet/page/system/part hierarchy at book level, even for sheets no longer in memory.
The same information is also available in sheets and the problem is to keep these informations in sync between book level and sheet level. And we have bugs there.

For instance, I noticed you set sheet 7 as invalid. But this sheet still has a page, systems and parts at sheet level. At book level however we have just the information that sheet is invalid., no more page/system/part information.
It's a mess. 
The engine generally detects an invalid sheet during the SCALE step.
Perhaps, when a sheet is manually declared as invalid by the end-user, the program should get rid of any information computed by SCALE step and following steps. That's about everything except the binary image. This way, sheet and book levels would be kept in sync.

**Comment by Bacchushlg** [comment]
Ok, I understand.
I had invalidated it because I was unable to get the page transcribed (and intended to add the missing part "manually" in MuseScore.
About your last comment: I would prefer that the page information is simply skipped, as if it was a blank page, so the following page continues with the information of the last valid page. It will fit for the most cases...

**Comment by hbitteur** [comment]
@Bacchushlg 
Please pull from development branch to get:
- Bug fix on invalid status
- Bug fix on split & merge
- New "Rebuild Scores" experimental action available in Book pulldown menu

Here is my personal experience on your "Canada In SpringTime" input, a very poor-quality input to say the least:

1. Using `Tools | Options` menu, I twisted a few key parameters in StaffProjector class:
    - `barThreshold` set to 3.2 (Minimum cumul value to detect bar peak)
    - `chunkThreshold `set to 2.5 (Maximum cumul value to detect chunks (on top of staff lines))
    - `maxDerivativeRatio `set to 0.18 (Minimum absolute derivative as ratio of elite derivative)
2. I removed sheet 4, using SplitAndMerge, because I found no way to process this sheet with such big stamp in the middle. So, I extracted sheets 1-3 and 5-10 from Canada In SpringTime into a new CanadaSans4 .omr. From now on, I'll speak of sheets 1-9 within CanadaSans4. I tried to reach GRID step on each sheet with good results.
3. Because of indented staves in the middle of first sheet, I disabled the switch "Use of system indentation" for the whole book, using menu `Book | Set Book Parameters`
4. On sheet 6 (former 7), I stopped after SCALE step to modify line thickness from 5 to 6, because of many thick lines in the image. Then I ran GRID step as on the other sheets.
5. On sheet 8 (former 9) I had one barline missing and one brace missing. I added them manually.
6. On sheet 9 (former 10) , I stopped at SCALE step to raise line thickness from 5 to 7. Grid STEP was then ok. Just one barline missing added manually. i manually straightened a few staff lines.

That's it, all the sheets reached the GRID step with correct recognition of all staff starting barlines, which is key for future processing.
A missing barline **within** staff width is not a serious problem: we can easily add it manually for the whole system height.
Same remark for a missing brace, adding it manually allows the related 2-staff piano part to be recognized as such rather than two separate 1-staff parts.

Still at the end of GRID step, I collated and edited the logical parts names as follows, and all parts get correctly mapped:

![image](https://user-images.githubusercontent.com/22053634/226890077-e16530ab-4d74-464b-905e-ce79e97b7b35.png)

Also, some staff lines can get wavy due to high line thickness. Today, I corrected them manually using the popup menu `Staff | Edit lines`. Perhaps this cleansing could be performed automagically by the OMR engine, I'll investigate this when I have some time available.

**Comment by Bacchushlg** [comment]
Finally I achieved to get the score transcribed.
Although a hard work, it was worse it, also looking at the improvements of Audiveris due to the difficulties...

**Comment by hbitteur** [comment]
> it was worse it

I suppose you meant "it was worth it", right? :-)
