### ISSUE TITLE
Grace beams

### ISSUE THREAD

**Issue by rodolfo-medina** [Audiveris/audiveris#669]
Hi, Hervé: does Audiveris still not have an implementation for grace beams?  To be clear, an example of what I mean on p.6 measure 3 of the attached score.

Thanks,

Rodolfo

[Schubert_D946_3-Pieces.pdf](https://github.com/Audiveris/audiveris/files/12641146/Schubert_D946_3-Pieces.pdf)

**Comment by hbitteur** [comment]
Audiveris now supports grace heads, as well as grace beams between grace heads.

Make sure you select the proper processing switches, via the menu `Book | Set Book Parameters`:

![image](https://github.com/Audiveris/audiveris/assets/22053634/9cf06286-dbf5-4858-a1b4-25e9be313ff5)

You need to select at least the "`small heads`" switch, because the CUE_BEAMS step will look for small short beams within any detected group of small heads.

You need to select the "`small beams`" switch only for rather long beams. And you may need to adjust the precise height for such beams, via the menu `Sheet | Set Scaling Data`.

But, I just tried to process your example, here in sheet 6, measure 3 of the second movement:

![image](https://github.com/Audiveris/audiveris/assets/22053634/b7822644-76a0-45f0-87ad-9b6ce76ce68d)

The result at the end of the REDUCTION step is rather poor regarding the cue heads and beams in this measure.  
Let's have a look at the binary input image:

![image](https://github.com/Audiveris/audiveris/assets/22053634/a8f6445e-d36b-4800-a7d0-3c181712555c)

The input image is of poor quality (stems, heads, beams). Especially the stack of "cue" beam(s) look like one big beam!  
Even as a human reader we cannot decide if we have 2, 3 or 4 small beams stacked one upon the other.
Also, what is the height in pixels of each of he underlying "small" beams? We can't tell.

So don't expect any miracle from the OMR engine. :-)

**Comment by rodolfo-medina** [comment]
Then I could use Audiveris to re-write the small beam from scratch?  With in this case three pieces one upon the other.

**Comment by hbitteur** [comment]
From Audiveris UI, you can indeed manually insert the missing items (small heads, small beams) if this is what you mean by "re-write".

Pay attention to drag 'n drop from **small** head and  **small** beam buttons:
![image](https://github.com/Audiveris/audiveris/assets/22053634/79b0fb59-55ac-4e5f-90af-777293164c8d)
![image](https://github.com/Audiveris/audiveris/assets/22053634/f360fcce-3340-4ea7-8cee-12cb1cfaf402)

**Comment by rodolfo-medina** [comment]
It seems that such grace beams are not exported in the musicxml file...  Or at least they do not appear in Musescore.
