### ISSUE TITLE
Fresh install fails to execute

### ISSUE THREAD

**Issue by KB3HNS** [Audiveris/audiveris#671]
Fresh install of the program using the provided installer.  After installation, I try to run the program.  A window pops up and immediately closes.  Searching for and running the batch file manually yields the following output:

````
Unrecognized option: --add-exports=java.desktop/sun.awt.image=ALL-UNNAMED
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```

Windows 10 x64
Java -version:

```
java version "1.8.0_381"
Java(TM) SE Runtime Environment (build 1.8.0_381-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.381-b09, mixed mode)
```

**Comment by hbitteur** [comment]
Your Java version (8) is much too old.
You need Java 17, as specified in Audiveris doc...

**Comment by KB3HNS** [comment]
Interesting.  All the documentation that I was reading calls out JAVA 8 in multiple locations.  Unfortunately days later I can't find the links that I was using.  Frustrating.  I think that this may have been the link that was [coming up for me](https://bacchushlg.gitbooks.io/audiveris-5-1/content/install/binaries.html) which I realize now is quite outdated.
I have fed it some test images (not doing well), unfortunately I need a MIDI file as an output.  I guess that's not supported.  Sadly I can't seem to find one anywhere other than Musescore which redirects to their website and wants a log-in which is a bit **NOPE** for me.

**Comment by KB3HNS** [comment]
Maybe a follow-up question:  Image rotation.  For some reason I'm importing jpeg files (paper scores captured with a phone camera).  Sometimes it will rotate the incoming image.  It seems to force wide images even when taken vertically.  Also it will frequently invert the image.  Is there a way to rotate the image at the load / raw image stage before attempting to have it transcribe?

**Comment by hbitteur** [comment]
There is currently no rotation feature in Audiveris.

For a while, we had a "_de-warping_" feature, which was able to somehow straighten wavy staff lines. But this feature was removed because it relied on the `JAI` software which is not fully open-source.

Anyway, if I understand correctly, you are looking for something like a rotation of 90, 180 or 270 degrees.
These quadrant rotations would not be difficult to implement, I agree. But are they really needed _within_ Audiveris?

Right now, I personally use XnView, but there are many other free softwares out there that you could use for this kind of operation.

**Comment by KB3HNS** [comment]
Thanks for the reply.  Actually, I have ensured that I rotated the image correctly (applied rotation using MS Paint **and** picture editor).  For some reason, on import, it does some sort of rotation.  I can send you the image directly, but can't post it here due to copyright restrictions as it is a picture of a copyright work (what I am doing is considered fair use by the terms of my license with the publisher).

**Comment by hbitteur** [comment]
You can send me the image via private mail using: herve dot bitteur at audiveris dot org

**Comment by KB3HNS** [comment]
Sorry it took so long, but I have sent you an example image.

**Comment by hbitteur** [comment]
Strange.

The staves appear to go from bottom to top in:
- Audiveris
- Greenshot
- Libre Office Draw
- Snip & Sketch
- Windows Live Photo Gallery

They go from left to right in:
- Atom
- IrfanView
- Paint
- (Windows?) Photos
- Picasa
- Thunderbird
- Windows file explorer (thumb nails)
- Windows Photo Viewer

Don't ask me the reason for these behaviors.

Anyway, I rotated the image clockwise for 90 degrees (I think I used Snip & Sketch), and then Audiveris displayed the staves from left to right.

But this is not all, because the staves are very **wavy**.
The GRID step failed to correctly process the first and the last staves, the first one exhibits a **downward** slope of 3-4 degrees and the last one an **upward** slope of 3 degrees, approximately.
The other staves are correctly processed.

My advice: make a better scan before calling OMR. :-)
