### ISSUE TITLE
Index out of bounds when transcribing

### ISSUE THREAD

**Issue by olin256** [Audiveris/audiveris#677]
[Input PNG file](https://github.com/Audiveris/audiveris/assets/84866288/26068f61-01fd-4ab3-8590-1e0436a10641)

I'm getting the following:
`Error in performing [SCALE, GRID, HEADERS, STEM_SEEDS, BEAMS, LEDGERS, HEADS, STEMS, REDUCTION, CUE_BEAMS, TEXTS, MEASURES, CHORDS, CURVES, SYMBOLS, LINKS, RHYTHMS, PAGE] java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.lang.ArrayIndexOutOfBoundsException: Index -4784 out of bounds for length 3794908`

[console_output.txt](https://github.com/Audiveris/audiveris/files/12837110/console_output.txt)

**Comment by hbitteur** [comment]
I get a different error on your input, a null pointer exception.
The root cause of (my) error is the fact that your image is much too cropped on the right side, resulting in NO barline at all in systems 1, 3, 8, 9, 10 and 13.
Could you try with a different scan presenting some horizontal margin, especially on the right side?

**Comment by hbitteur** [comment]
Update:
I've been able to reproduce your error.
In the HEADERS step, when looking for key signature, the engine tries to check pixels up to 2 interlines above the first line of each system.
In your case, this goes out of the image bounds, hence the exception.

I'll try to better protect the engine against this configuration.
Meanwhile, you should try to scan your score with larger margins (here the problem is with the top margin)

**Comment by olin256** [comment]
Thanks! I've added sufficient margins:
[new image](https://github.com/Audiveris/audiveris/assets/84866288/39d01c8e-1106-483e-af07-4f9be88cd588)
Now the transcription gets further (I get note heads and stems, but not flags), but ends with an error nonetheless:
[log file](https://github.com/Audiveris/audiveris/files/12838474/20231007T201145.log)

Is this the thing caused by having no barline at some of the systems? Just to clarify, this is not a result of cropping too much, the score indeed has only a couple of barlines (it's sort of a plainchant). Is it necessary to have barlines? And it's not scanned, it's pretty much a direct output of LilyPond intended for web presentation (hence the lack of margins).

**Comment by hbitteur** [comment]
I can confirm that "no barline" is a problem.
Give me some time to fix this.

**Comment by hbitteur** [comment]
@olin256 
I just pushed two commits related to your issue:
- Commit 94937124b441de4daf0919cc051de1126759379e to protect against access beyond sheet boundaries for images with narrow margins.
- Commit 92ed0de2f4c6fcf4fb193591b18ce35ae21c3e1a to recognize a measure even without barline in the containing staff.

They are available in the "development" branch
