### ISSUE TITLE
Cannot start software on Windows 11

### ISSUE THREAD

**Issue by edwinzap** [Audiveris/audiveris#678]
I cannot start the software after installation. I tried to open it with admin rights, same result.
Here is the error if I open it from a terminal: 
```
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.Unrecognized option: --add-exports=java.desktop/sun.awt.image=ALL-UNNAMED"
```
I installed Java from here: https://www.java.com/en/download/manual.jsp

What should I do?

Thanks!

**Comment by edwinzap** [comment]
It's working with this: https://www.oracle.com/fr/java/technologies/downloads/#jdk21-windows
Good to know

**Comment by hbitteur** [comment]
> I installed Java from here: https://www.java.com/en/download/manual.jsp  

But this site is about Java 8! Pretty old now...

As indicated on the Audiveris web page, the current release (5.3) requires **Java 17** or later.

FYI, we try to stick to Java LTS versions (LTS = **L**ong **T**erm **S**upport).
Since the latest LTS numbers today are 17 and 21, we'll soon jump to Java 21 , beginning by the development branch.
