### ISSUE TITLE
Poor beam recognition performance

### ISSUE THREAD

**Issue by olin256** [Audiveris/audiveris#680]
[Transcribed image](https://github.com/Audiveris/audiveris/assets/84866288/bd70a6ef-9564-4c59-9135-107482ee0d67)

I'd expect that it shouldn't be hard to get the beams correctly in this score; however, with the default settings, none of them is recognized. The issue seems to be the following:
```
INFO  [Z882-1]              ScaleBuilder 234  | Beam  guessed height: 10 -- 0.50 of 19 interline
INFO  [Z882-1]              ScaleBuilder 257  | Beam measured height: 18 -- 0.93 of [5..19] range at 121% of needed quorum
```
The first guessed height 10 px is perfect, 18 px is definitely not. If I set `defaultBeamSpecification` to 10, then the result is correct with all the beams recognized.

(By the way, can I set this parameter via console? I have tried `-option defaultBeamSpecification=10`, but with no effect…)

**Comment by hbitteur** [comment]
You can have a look at Scale plots (combo and black plots) via the pull-down menu `Sheet | Display Scale plots`.
The black histogram gives line staff line thickness and potentially the beam thickness.

Here is a part of this plot:

![image](https://github.com/Audiveris/audiveris/assets/22053634/4db3d536-f958-45bc-8833-4c0e540f14b3)

You can see that there are two potential beam peaks, one at 10 and one at 18. Both counts are above the minimum beam quorum (331), 18 is chosen because its count is a bit higher than the count for 10.

In fact the beam quorum appears to be too low. A higher quorum would invalidate these two beam candidate peaks, letting the engine ignore these peaks and choose the guessed height value of 10.

The beam quorum is governed by the Constant `beamMinCountRatio` whose current value is `0.007`, perhaps `0.01` would be a better value.
The quorum is computed as ratio * function area (the integral between x-axis and function).
You can augment this Constant value on your own, either interactively via `Tools | Options` or via the command line using 
> -option org.audiveris.omr.sheet.ScaleBuilder.beamMinCountRatio=0.01

Note that setting a constant on the command line always requires a **fully-qualified** name (package.class.constant).
This is the reason why your setting:
> -option defaultBeamSpecification=10

was incorrect. You should use:

> -option org.audiveris.omr.sheet.Scale.defaultBeamSpecification=10

**Comment by olin256** [comment]
Thanks! This has made it clear.

By the way,

> Note that setting a constant on the command line always requires a **fully-qualified** name (package.class.constant).

perhaps this information could make its way to the [handbook page](https://audiveris.github.io/audiveris/_pages/advanced/cli/); now I see that it is present on the wiki page…

**Comment by hbitteur** [comment]
The handbook page about CLI says:

> -option KEY=VALUE
Specifies the value of one application option, KEY being the qualified name of the option, VALUE being the value to assign.
------------------------------------------------------------------^^^^^^^^^^

OK, I will replace "qualified name" by a more explicit "fully-qualified name (package.class.constant)" as in my previous post.
Thanks for the advice

**Comment by olin256** [comment]
Ah I see. I'm not very familiar with Java, so "qualified name" was an unknown notion for me (in retrospect, I could have searched it…).

From my experience, such stuff is often most easily presented via an example (like in the [wiki](https://github.com/Audiveris/audiveris/wiki/CLI-Arguments#-option)).
