### ISSUE TITLE
problem to transcribe a good quality score with compressed notation format

### ISSUE THREAD

**Issue by Bacchushlg** [Audiveris/audiveris#693]
The appended score is of rather good quality, but is uses a unusual compressed format.
Is it possible to improve transcription by modifying certain parameters? What is especially unclear to me is that it does not recognize most of the beams.

[So soll es bleiben.pdf](https://github.com/Audiveris/audiveris/files/13256247/So.soll.es.bleiben.pdf)

**Comment by hbitteur** [comment]
I just checked your input image.

Running the SCALE step gives a measured beam height of 6 pixels:

![image](https://github.com/Audiveris/audiveris/assets/22053634/7cef1a5a-30a6-451a-b5f5-d3d17c605026)

Looking at the image, we can see:
- very few beams
- many rather horizontal and thick lines (lyrics and wedges)

In other words, the contribution of these thick "lines" will outperform the contribution of beams into the scaling black histogram.
Here is the histogram, via `Sheet | Display scale plots`:

![image](https://github.com/Audiveris/audiveris/assets/22053634/3ced0bd9-cc77-4191-98d3-cac97a7ee7fb)

Beam scale should be set to 9 instead of 6.
For confirmation, you can manually measure the real height of any concrete beam:

![image](https://github.com/Audiveris/audiveris/assets/22053634/81ca1fec-9697-444e-8697-cf2283ba8a59)

You cannot change the input image, but you can tell Audiveris to use a specific beam height.
This is done via `Book | Set book parameters`.
Select the book tab, because the beam specification will apply equally well to all sheets of the book:

![image](https://github.com/Audiveris/audiveris/assets/22053634/294550ad-6e81-41b4-bef2-a74a71a661d1)

Specify the value 9 for beam height.
Press Ok or Apply.
You can also save the book, this will save the specification.

Then restart your transcription from scratch.

Happy transcription!

**Comment by hbitteur** [comment]
FYI, I'm working on broader specifications for 5.4.
They will address:
- Interline (for snippet images without multi-line staves)
- Barline height (2 or 4 interlines)
- Beam thickness (feature that you already have)

**Comment by Bacchushlg** [comment]
It seems that the beam thickness algorithm has problems...
In all sheets it results in thickness 6, although the other pages are full of beams.
Setting the value to 9 does not allow to transcribe all sheets, unfortunately

**Comment by hbitteur** [comment]
> In all sheets it results in thickness 6

Pay attention to set the beam specification at book level, so that all sheets can benefit of the spec.

I get an IndexOutOfBoundsException in BeamLinker class for sheets 3, 4 and 5.
I had checked sheets 1 and 6 only. This is really bad luck! :-)

Apart from this problem, beams are correctly processed.

I'll try to push a bug fix tonight.

**Comment by hbitteur** [comment]
The IndexOutOfBoundsException cases have been fixed by commit eb837d6a5d23a0f91ccf8dc0c371dc9ec8aedf89 in development branch.
Please pull and retry the whole book on your own.

**Comment by Bacchushlg** [comment]
Transcription now was performed without severe errors.
Thank you!
