### ISSUE TITLE
wrong tick placement for whole notes in case of chords with interleaved note heads

### ISSUE THREAD

**Issue by Bacchushlg** [Audiveris/audiveris#70]
![clipboard 2](https://user-images.githubusercontent.com/33522630/36111334-0ee9881e-1026-11e8-8f79-8382d89b9ad6.jpg)

In the example above (complete score in #68 ) the bass chords are not evaluated correctly. Two of the notes go to tick 5 (!?).

**Comment by hbitteur** [comment]
Well, not an easy case...
OMR engine has detected 3 chords  near the beginning of measure number 2:
1. Quarter A in upper staff
2. Wholes G + A at top of lower staff
3. Whole D at middle of lower staff
And it has not assigned all of them to the same time slot, because of the abscissa shift between center of chord 2 vs center of chord 1 and of chord 3.
This "adjacency" detection algorithm is a bit touchy, because in the case of crowded scores, we don't want to merge chords that are close to one another. I will check this further.

**Comment by Bacchushlg** [comment]
just a little comment concerning 2. and 3.: 
If you mean to split notes to voices: there is no need to separate the notes of the lower staff to different voices.
programs like MuseScore use this separation to voices if there are chords with (partly) different rhythm. For the referenced score there would be no need to split note. But it's no problem to do so, and esp. at measure 8 it is not obvious if this should be split or not...

**Comment by hbitteur** [comment]
Trying to reproduce the case, measure 2 was OK for me but not measure 6 (for just one pixel above the maxSlotDx threshold!).
It was not a question of adjacency after all (because there was no vertical overlap) but simply a just too wide horizontal gap.
I very slightly increased the threshold, because we have to avoid possible collateral damages...

Done in commit 7ef5c47d6faeaf380ffec69af9ee839f7b9d9a09
Bye

**Comment by hbitteur** [comment]
Our messages just crossed.

The problem was just a question of chords sharing or not the same time slots.
Regarding chords (and voices) definition, is is easy to detect separate chords in measure 8 bottom staff, simply because we have two stems.

It's more complex when we have no stem:
1. For measure 1, the engine gives one chord (all whole notes slightly overlap vertically).
2. For measure 2, it gives 2 chords (one with 2 wholes, one with 1 whole).
