### ISSUE TITLE
First measure not recognized as pickup

### ISSUE THREAD

**Issue by olin256** [Audiveris/audiveris#713]
It is the first measure of the following file:
[201.zip](https://github.com/Audiveris/audiveris/files/14025466/201.zip)
When exporting into MusicXML, the first measure gets number 1 instead of 0.

**Comment by hbitteur** [comment]
In the very first measure, a note was not correctly recognized, it was mistaken for an 8th rest.
The other notes in this measure were correctly recognized as quarter notes.

When this first measure was tested by the engine for being a pickup, it exhibited non-consistent durations between the measure voices (3 voices with 1/4 duration and 1 voice with 1/8 duration), therefore the measure was **not** set as pickup.

Later, you corrected the note, replacing the 8th rest with a quarter note (inter 3580 manual). _But this did not trigger a new measure  numbering._

[Note that to manually fix this, you could have launched the command  `Page | Reprocess rhythm` via a right click. This would have forced measure numbering.]

I'm going to correct this in the code, so that such a manual correction that impacts voices, would also trigger the measures numbering.

**Comment by hbitteur** [comment]
Bug fixed today via commit 21b150e21e9d04e7c1cad01d5a60e776008d3ee5 on "development" branch.
Please pull

**Comment by olin256** [comment]
Thanks for the quick fix! I somehow had the (false) impression that this (together with measure numbers) is decided at the moment of exporting, but this way it makes more sense.
