### ISSUE TITLE
I can't open the software on win11, but the same configuration works on a virtual machine on win10.

### ISSUE THREAD

**Issue by philogos** [Audiveris/audiveris#768]
I wonder if win11 is missing something critical

**Comment by hbitteur** [comment]
I don't know.

Problem: Microsoft has decided that my PC (14 years old) is not allowed to run Windows 11.
In other words, I cannot test Audiveris on Windows 11.

**Comment by Christtj14** [comment]
my too,win11 not working.

**Comment by JosephCHEYNET** [comment]
Same for me, it crashes as soon as it lanches. What could I do to help ?

**Comment by JosephCHEYNET** [comment]
I will download the sources and try to run with intellij Idea

**Comment by JosephCHEYNET** [comment]
I downloaded the windows installer, then lanched the program. A windows appears and disapears straight away with no error message.

**Comment by hbitteur** [comment]
But you have executed the installer program? (to actually install Audiveris)

**Comment by JosephCHEYNET** [comment]
Yes the installer program ran without any problem

**Comment by hbitteur** [comment]
Assuming you have installed Audiveris (via its installer), a common error is to use a non-compatible Java environment.
The problem (fixed in the coming 5.4 release) is that the terminal window closes before you have time to read the error messages!

With current 5.3, you will have to:

1. Open a terminal window
2. Launch Audiveris from the command line

Typically Audiveris is installed in the folder: C:\Program Files\Audiveris\bin
So, you should try this command:

"C:\Program Files\Audiveris\bin\Audiveris.bat"

The quotes may be needed because of the space between Program and Files

Then post the error messages you get

**Comment by JosephCHEYNET** [comment]
Thanks, i will try

**Comment by JosephCHEYNET** [comment]
C:\Program Files\Audiveris\bin>java -version
java version "1.8.0_411"
Java(TM) SE Runtime Environment (build 1.8.0_411-b09)
Java HotSpot(TM) Client VM (build 25.411-b09, mixed mode)
C:\Program Files\Audiveris\bin>Audiveris.bat
Unrecognized option: --add-exports=java.desktop/sun.awt.image=ALL-UNNAMED
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

**Comment by hbitteur** [comment]
Yep!
You are using Java 8.

Audiveris (master branch, the one related to the installer) requires Java 17. (Java 21 for the development branch)
You can pick up Java 17 from [this Oracle site](https://www.oracle.com/java/technologies/javase/jdk17-archive-downloads.html).
Make sure to choose the Windows x64 Installer

**Comment by JosephCHEYNET** [comment]
Thank you, installing Java 17 solved the problem. Have a great day.

**Comment by JosephCHEYNET** [comment]
J'ai pu tester sur mes partitions scannées. Il y a un très bon taux de reconnaissance. C'est super !

**Comment by hbitteur** [comment]
In French in ze text :-)
