### ISSUE TITLE
control of position of aug.dots and staccato dots

### ISSUE THREAD

**Issue by Bacchushlg** [Audiveris/audiveris#87]
in cases of non-optimal scans the program often "detects" aug.dots and staccato dots somewhere between the note heads.
We should provide a position check for these both dot-types:

aug.dots are either:
- at a line with the center of the note head, if note head is between lines
- half a noteline distance ABOVE the note head, if note head is on a line 
this also applies to notes that are placed on ledgers.
(correction: there are rare cases, where the dots are BELOW the note head - so both is possible)

staccato dots are always horizontally in line the the note head.
Normally they are above the note heads. Exception: notes with beams over the heads: here the dots are under the heads. (This rule applies to all articulations)

Only dots that are conform with the conditions above should be considered as valid. All the rest is clutter...

**Comment by hbitteur** [comment]
Minor correction: Staccato dots are _vertically_ aligned with the related chord, rather than _horizontally_.

An augmentation dot should horizontally aligned with the related head. But there is a problem when the head is located right on a stff line or ledger, the score writer is obliged to shift the dot a bit. Sometimes, it is shifted so much that it gets located right in the middle of the interline, and then we don't know it it applies to the head above or the head below...

I could add a check in the OMR engine to make sure that the dot candidate is "far enough" from the line.

**Comment by Bacchushlg** [comment]
in all my scores, the aug.point is exactly positioned in the middle between the notation lines, or other speaking: half a note-line distance away from the middle of the note head. This means that the check for a correct position could be stronger than "anywhere between the note lines".
About the distance: it is typically ca. 1,5 * noteline distance from the center of the right-most notehead of a chord, so maybe a range from 1 - 2 * nl-distance is a good value.
If against all note heads is too complicated, the range must be 1 - 3 nl-distance from the actual note head (always middle to middle of the glyph)

**Comment by hbitteur** [comment]
Sorry, I'm lost. Could you tell me the meaning of "noteline distance". How does it compare with the "interline" value, which is the vertical distance between one staff line and the next (center to center).

I was talking about the vertical shift sometimes imposed by the staff line (or ledger line), and proposing a kind of minimal vertical distance for the dot WRT the horizontal line.
But it seems that you are talking of **horizontal** distance. Could you clarify your point?

**Comment by Bacchushlg** [comment]
Yes, I meant interline distance. 
But you are right, this maybe not a good reference.
If you have a value for the "typical note head size" (HS), then I would propose:

ca. 1,5 * HS from the center of the right-most notehead of a chord, so maybe a range from 1 - 2 * HS-distance is a good value.
If checking against all note heads is too complicated, the range should be 1 - 2,5 HS-distance from the actual note head (always middle to middle of the glyph)

**Comment by hbitteur** [comment]
I'm still lost :-(
When you write "1 - 2 * HS-distance", what are the meanings of the two "-" characters?
Perhaps a drawing could clarify this?

**Comment by hbitteur** [comment]
![image](https://user-images.githubusercontent.com/22053634/36804844-02ac8d7e-1cbc-11e8-874c-98c513115186.png)

I'm beginning to understand:
1. You were talking about horizontal distance (hence the need for right-most head as in the figure above)
2. I was still concerned by vertical distance (as in the lower staff)

**Comment by Bacchushlg** [comment]
![image](https://user-images.githubusercontent.com/33522630/36806866-b61ff364-1cc1-11e8-9c22-3ca6a04e6fd2.png)

**Comment by hbitteur** [comment]
![image](https://user-images.githubusercontent.com/22053634/36840435-447e4466-1d45-11e8-8a32-241e4929b9af.png)
![image](https://user-images.githubusercontent.com/22053634/36840475-611fcc7a-1d45-11e8-8142-7cd1835019a7.png)
Here above are two cases I'm fighting with. As you can see in both cases we have a note head (located on a staff line) linked to 2 augmentation dots, so which dot should be chosen?
My proposal is as follows, processing chord heads from top to bottom:
1. Look at dot above first. If dot is not linked to a head located between lines, select it.
2. Otherwise, look at dot below. If dot is not linked to a head located between lines, select it.
The strategy would also correctly work with @Bacchushlg examples (normal and interleaved)

**Comment by Bacchushlg** [comment]
I agree. This should works this way. I understand that you first (step 0) link dots to heads between lines. They should always be unambiguous.
What about cases with a common dot for 2 voices (#75 )? Do you have this in focus, too?

**Comment by hbitteur** [comment]
Case #75 is a bit different. We have one glyph (with note head shape) which gives 2 **mirrored** NoteHeadInter instances, one for each headChord.

But, I have no clear strategy for the scope of a potential augmentation dot:
1. If we have 1 augmentation dot, does it apply to both NoteHeadInter instances? We have both examples and counter-examples. In current engine version, it applies to the chord with shorter duration.
2. If we have 2 augmentation dots, we could safely assign one dot per NoteHeadInter

**Comment by Bacchushlg** [comment]
According to my opinion, an aug. dot after a common note head for 2 voices does always concern both voices. 
I just tried in MuseScore: if I have 2 voices with same note head and aug.point, they only set 1 aug.point.
The case that appears in my score of #75 (with 2 points) is unusual.

If note heads shall not share an aug.point, then the score must display 2 different note heads:
![image](https://user-images.githubusercontent.com/33522630/36843596-b538bc9a-1d4f-11e8-943c-308da5c01d38.png)

**Comment by hbitteur** [comment]
The risk in this example is that the first 2 chords get considered as sequential  (2 different time slots) rather than adjacent (same time slot).
Detecting adjacency is touchy.

**Comment by Bacchushlg** [comment]
But that's the way how notation works. I did nothing manually in the example, the arrangement of the notes is done by the program.

**Comment by hbitteur** [comment]
Yes, this is MuseScore output.
I was concerned by Audiveris trying to transcribe this output...

**Comment by Bacchushlg** [comment]
I just tried your latest commit: it seems to work good, but I have 2 scores where now too many aug.dots are ignored. 
I have incremented "AugmentationRelation.xOutGapMax" from 1.0  to 1.2, and with this it's ok. I propose to set the value to 1.3, to be sure

**Comment by hbitteur** [comment]
Yes, this max gap was initially set to 2.0 (interline fractions).
Thanks to the new algorithm which takes into account the existence of note heads on both side of the chord stem, I was able to reduce it from 2.0 down to 1.0.
Please forward your example, so that I can make sure that the non-detection was really due to the max gap value.

**Comment by Bacchushlg** [comment]
![abschied vom walde](https://user-images.githubusercontent.com/33522630/36947097-dea7df82-1fc7-11e8-9570-f100d79fcd16.jpg)

example 1 concerning "AugmentationRelation.xOutGapMax"

**Comment by hbitteur** [comment]
OK, xOutGapMax now relaxed from1.0 to 1.3 for AugmentationRelation, commit 504131d51dc1f77c1a7bdc8aa8227c3da577c1a6

I noticed also many wrong "text" entities with very large font size in this example. IIRC, there is a max font size threshold, I'll double-check this.

**Comment by hbitteur** [comment]
Yep, a typo in recent modification prevented engine validation of text lines. Sorry for that.
Fix in commit 3b3d2395cd4cdd4fea1f4013ed3677ee4974ce1c

**Comment by Bacchushlg** [comment]
I got some scores where yGapMax = 0.8 is too strong. 
0.9 works for me with these score. Seems to be better as default.
