### ISSUE TITLE
Random accidentals in MusicXML export

### ISSUE THREAD

**Issue by maximumspatium** [Audiveris/audiveris#92]
During MusicXML export, audiveris seems to sometimes add random accidentals that are not present in the recognized music.

The book that triggers the error can be downloaded [here.](https://github.com/Audiveris/audiveris/files/1752917/BarP.-.Sweet.Georgia.Brown.2.omr.zip)

The above mentioned book was exported to MusicXML and then imported in two different music editors: MuseScore and [PriMus](http://www.columbussoft.de/primus-free.php). Both of them shows additional accidentals as depicted in the attachments.

![error1 audiveris score](https://user-images.githubusercontent.com/6561800/36613470-e7f9e426-18d9-11e8-854e-7c9b141fd829.png)
![error1 import in musescore](https://user-images.githubusercontent.com/6561800/36613471-e8272f8a-18d9-11e8-8c46-ee1694830e36.png)
![error1 import in primus](https://user-images.githubusercontent.com/6561800/36613472-e84db1b4-18d9-11e8-8493-9172c01d2f65.png)
![error2 audiveris score](https://user-images.githubusercontent.com/6561800/36613474-e88af344-18d9-11e8-9330-66f613b9956c.png)
![error2 import in musescore](https://user-images.githubusercontent.com/6561800/36613475-e8c7c2a6-18d9-11e8-858c-ecbe4bd02ec7.png)
![error2 import in primus](https://user-images.githubusercontent.com/6561800/36613476-e8fe8912-18d9-11e8-8aec-ed1d50577e0d.png)

**Comment by maximumspatium** [comment]
Here is the XML code for the 1st wrong note:

```xml
<measure number="11" width="240">
  ...
  <note default-x="186">
    <pitch>
      <step>B</step>
      <octave>3</octave>
    </pitch>
    <duration>12</duration>
    <voice>2</voice>
    <type>quarter</type>
    <stem default-y="-30">down</stem>
    <staff>2</staff>
  </note>
</measure>
```

Here is the XML code for the 2nd wrong note:

```xml
<measure number="19" width="259">
  <note default-x="200">
    <pitch>
      <step>F</step>
      <alter>1</alter>
      <octave>3</octave>
    </pitch>
    <duration>12</duration>
    <voice>2</voice>
    <type>quarter</type>
    <stem default-y="-44">down</stem>
    <staff>2</staff>
  </note>
</measure>
```

**Comment by Bacchushlg** [comment]
As I understand, the problem is triggered from the the notes in the top note line in both cases:
case1: there is a F# in the top line, and so the algorithm assumes that this is valid for the note 2 ticks later in the bottom line, too
case2: the B (natural for first note top) triggers that there is assumed a natural for B in in the bottom line.

**Comment by maximumspatium** [comment]
Yes, that's correct. The last check in the previous comment fixes the issue but it's just a quick-n-dirty fix. I'm not really happy with it.

My proposal is to iterate over the notes of the same voice, not over the time slots as it's currently implemented. So the method need to be changed to the following algorithm:

- locate the time slot where the source note resides (this is probably easily obtained from @this)
- extract chords/notes from the measure start until the source time slot and keep only the notes that belong to the same voice as the source note
- iterate over these chords/notes and look up for previous accidentals

**Comment by maximumspatium** [comment]
And the funny thing is that the fixed check **does actually fix our extra bar issue.** It isn't there anymore! Did you noticed that? I'm going to elaborate why...

**Comment by maximumspatium** [comment]
Moreover, we need to ensure that the fixed code behaves correctly for the case where one staff contains two or more voices. A test piano score with several voices and a lot of accidentals would be helpful...

**Comment by Bacchushlg** [comment]
[BarP - What a Wonderful World 2.zip](https://github.com/Audiveris/audiveris/files/1754302/BarP.-.What.a.Wonderful.World.2.zip)

Maybe this score is good for testing...

**Comment by Bacchushlg** [comment]
What about this code change? I used it for a week (about 20 trials), and I got no new problems due to it.
Should we commit it?

**Comment by hbitteur** [comment]
I'm getting into this discussion a bit late, sorry I'm back from a few days off.
I understand that step equality is not enough, we should test octave equality as well, OK.

And then the fix should be OK in the 2 cases above (please correct me if I'm wrong):
- First case, **B**: it is a B3 in both staves, so the natural sign should apply to the second B as well
- Second case, **F**: we have a F4 in upper staff and a F3 in lower staff, so the sharp should **not** apply to the second F

There is no need to call voices to the rescue, and this is fortunate because voices assignment is still so unreliable!...
Maxim's fix  looks OK to me.

**Comment by Bacchushlg** [comment]
> First case, B: it is a B3 in both staves, so the natural sign should apply to the second B as well

No, I don't agree: the natural before the B3 in the upper staff must not apply to the other staff(s). Notation is always by staff. Even sometimes notation even repeat an accidental per voice (e.g. for vocals with two voices in a system), because the singers are focused on "their" voice and might not notice accidentals from other voices - but this is not mandatory).

**Comment by hbitteur** [comment]
I'm a poor musician, and could play guitar only (just one staff!)
But my understanding is that for some instruments (piano is the most typical case) the score needs 2 staves to conveniently cover the range of all possible note heights. But, this is just for display: it's the same instrument on the 2 staves, a voice can move from one staff to another!

This applies for a multi-staff part only (often marked by a brace in the left margin), not for 2 separate parts (each with its own staff).

**Comment by hbitteur** [comment]
The test for belonging to the same part (instrument) is already implemented by line 241 (see source above):
```
for (AbstractChordInter chord : slot.getChords()) { 
         if (chord.isRest() || (chord.getMeasure() != measure)) { 
             continue; 
         }
```
Because a measure is delimited by barlines (horizontally) and containing part (vertically)

**Comment by maximumspatium** [comment]
To get an unopinionated answer, let's consult [Behind Bars](http://www.fabermusicstore.com/Behind-Bars-The-Definitive-Guide-To-Music-Notation-0571514561.aspx) - the definitive guide on Common Western Musical Notation.
Quoting the section "Using accidentals" on page 79:

> TWO OR MORE STAVES FOR ONE PLAYER
> An accidental holds good only for the stave in which it's written. It should be confirmed or cancelled when it occurs in another stave in the same bar. When a note with an accidental is taken with the other hand in the same stave, the accidental holds good and does not need to be repeated.

So the first case (B) need to be fixed because we actually got two different pitches in two different staves...

**Comment by hbitteur** [comment]
So, Behind Bars tells us that the accidental is kept local to the current staff and bar (measure).
Fine, now we have to fix this B example, by using the containing staff (rather than the containing part)
Rather than:
```java
} else if (started && (note.getStep() == getStep()) &&
              (note.getOctave() == getOctave())) {
```
we could use:
```java
} else if (started && (note.getStaff() == getStaff()) && (note.getStep() == getStep()) &&
              (note.getOctave() == getOctave())) {
```
Nota: we cannot use chord.getStaff() because a chord may belong to 2 staves, hence we use note.getStaff()

@maximumspatium: If this is OK, could you complete the commit?

**Comment by hbitteur** [comment]
I  noticed also that I left a TODO  near the end of this getAlter() method. 
I'll try to address this (rare) case when Maxim has committed his modifs

**Comment by maximumspatium** [comment]
No objections, no complains so I'm closing this issue.
