### ISSUE TITLE
missing tool to split glyphs

### ISSUE THREAD

**Issue by Bacchushlg** [Audiveris/audiveris#96]
In the "old" documentation a function to split glyphs is described. It seems to be no more present, but I think we should have it.
I had several problems in the past that I could not solve, but that might be solved with such a tool.
E.g.:
- a double beam (16th) was not recognized a double, but as wide single beam. I helped myself by setting 2 16th flag at the stems - worked, but not a real solution
- a note head and its stem (bad scan) were considered as one glyph. I was unable to define the stem, because I could not select the vertical part separately.
- a chord with notes on both sides (interval of a second): the note heads are considered as one glyph sometimes.

**Comment by maximumspatium** [comment]
> In the "old" documentation a function to split glyphs is described. It seems to be no more present, but I think we should have it.

I'm not sure if it's the right way to solve segmentation issues. That glyph splitting feature was the most criticized UI component of Audiveris EG - users were complaining about its unintuitive, pixel-oriented nature making the score correction process unnecessarily slow and leading to the conclusion that slow and clumsy OMR can be better replaced with rapid reentering in Musescore.
We should consider alternatives instead of reanimating obsolete features. For me, it's the possibility to inject missing score objects manually. That's how it works in Photoscore. It's not currently fully implemented in audiveris - for example, one need to build a note incrementally by adding the head first, then the stem etc.  - but we're speaking about the **basic UI**, that's an early stage that can be improved later.

BTW, did you try to drag the stem onto the score? It worked for me quite well. Otherwise, I'd like to see the score it doesn't work for...

**Comment by Bacchushlg** [comment]
It appears e.g. in the score of #89 , 2nd measure in the melody.

And: I never can drag-n-drop stems, nor bars (red cross). Only way to define them is to select the glyph(s) and then define by double-click.

**Comment by Bacchushlg** [comment]
another example where splitting of glyphs would help:

![liebling dein herz 1-1](https://user-images.githubusercontent.com/33522630/36836737-7e71169a-1d3a-11e8-809d-37265ce469fe.jpg)

Last system, 2nd measure (one long stem instead of 2 separate) and last measure (try to set the stems for the last chord).

**Comment by hbitteur** [comment]
User edition can now fix this easily.
Closing

**Comment by BrunoVernay** [comment]
Would be nice to have an exemple in the documentation. "Best practice to deal with conflated glyph"  
![Screenshot From 2024-12-31 10-11-11](https://github.com/user-attachments/assets/2448db11-1fb5-4284-8737-11eb8690da47)

If I understood correctly, you would simply put the "inter" (the shapes) where they fits. That is 2 quarters notes (one up, one down), 2 flags and 2 noteheads.   (And **not** trying to select a glyph, assign the glyph to its interpretation, then select another glyph ... which is long and painful.)
Result is as below (I did both sides, it is quick once the shapes are in the cache.)
![image](https://github.com/user-attachments/assets/e3fa0129-ad9c-414a-9a3b-446e0e947f16)

**Comment by oli-ver** [comment]
Sorry, perhaps this is just something on my side: can someone please show with a screenshot also showing the audiveris tools how to exactly do that? Also did not find it in the docs.

If I have a misinterpreted single glyph from a chord containing 2-3 note heads adding more than one element leads to exceptions. As far as I understood audiveris does not allow to freely insert notes without mapping to glyphs, so after adding the first I am stuck.

Edit: I now found a way to handle this. On this short clip I show what the issue for me is: Adding just the note head is not working, only adding a note with stem works, but then I end up with too many stems and need to remove them. Not sure why adding only the note head is not possible:

https://github.com/user-attachments/assets/a0859e6f-45e6-4d6d-84a3-c759232afe29
